#!/usr/bin/env python3
"""Emit yah_npu_unpack: the NPU GEMM's C into the GPU output's column slice.

C (gen_npu_gemm): [col][M block][mp][np][chain mh, nh][8 rows][8 cols] f32, 64 x 64 per (col, M block).
out: f32 [tokens][stride]; C column j goes to out column off + j.
One work item per 8 consecutive C columns of one token: a 32-byte read and a 32-byte write.
"""
import sys

WG = 256


def gen(tokens, cols, stride, off):
    assert tokens % 64 == 0 and off + 64 * cols <= stride
    items = tokens * cols * 8
    c_elems = tokens * cols * 64
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_npu_unpack.py (tokens={tokens} cols={cols} stride={stride} off={off}) -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("kernel.def target(@yah_wave32) @yah_npu_unpack() {")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgs = index.constant {items // WG} : index")
    e(f"  %wgsz = index.constant {WG} : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    e("} launch(%c: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    e(f"  %nc = index.constant {c_elems} : index")
    e(f"  %no = index.constant {tokens * stride} : index")
    e("  %c_na, %out_na = buffer.assume.noalias %c, %out : buffer, buffer")
    e("  %cv = buffer.view %c_na[%base] : buffer -> view<[%nc]xf32>")
    e("  %ov = buffer.view %out_na[%base] : buffer -> view<[%no]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    for nm, v in (("cwg", WG), ("c8", 8), ("c2", 2), ("c4", 4), ("c16", 16), ("c64", 64), ("cmb", tokens // 64),
                  ("cstride", stride), ("coff", off)):
        e(f"  %{nm} = index.constant {v} : index")
    # item = C element index / 8 in C order: ((((col * nb + blk) * 4 + mp) * 4 + np) * 4 + chain) * 8 + row
    e("  %i0 = index.mul %wg, %cwg : index")
    e("  %item = index.add %i0, %tid : index")
    e("  %row = index.rem %item, %c8 : index")
    e("  %q1 = index.div %item, %c8 : index")
    e("  %chain = index.rem %q1, %c4 : index")
    e("  %q2 = index.div %q1, %c4 : index")
    e("  %npi = index.rem %q2, %c4 : index")
    e("  %q3 = index.div %q2, %c4 : index")
    e("  %mpi = index.rem %q3, %c4 : index")
    e("  %q4 = index.div %q3, %c4 : index")
    e("  %blk = index.rem %q4, %cmb : index")
    e("  %col = index.div %q4, %cmb : index")
    e("  %mh = index.div %chain, %c2 : index")
    e("  %nh = index.rem %chain, %c2 : index")
    e("  %t0 = index.mul %blk, %c64 : index")
    e("  %t1 = index.mul %mpi, %c16 : index")
    e("  %t2 = index.mul %mh, %c8 : index")
    e("  %t3 = index.add %t0, %t1 : index")
    e("  %t4 = index.add %t3, %t2 : index")
    e("  %tok = index.add %t4, %row : index")
    e("  %j0 = index.mul %col, %c64 : index")
    e("  %j1 = index.mul %npi, %c16 : index")
    e("  %j2 = index.mul %nh, %c8 : index")
    e("  %j3 = index.add %j0, %j1 : index")
    e("  %j4 = index.add %j3, %j2 : index")
    e("  %jo = index.add %j4, %coff : index")
    e("  %tb = index.mul %tok, %cstride : index")
    e("  %oa = index.add %tb, %jo : index")
    e("  %ca = index.mul %item, %c8 : index")
    e("  %v = vector.load %cv[%ca] : view<[%nc]xf32> -> vector<8xf32>")
    e("  vector.store %v, %ov[%oa] : vector<8xf32>, view<[%no]xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    if len(sys.argv) < 5:
        sys.exit("usage: gen_npu_unpack.py <tokens> <cols> <stride> <off>")
    sys.stdout.write(gen(*(int(v) for v in sys.argv[1:5])))
