#!/usr/bin/env python3
"""Emit the DeltaNet postnorm over heads h0 .. h0 + nh - 1 that also writes the NPU's BFP16 input of ssm_out.

The same per-row math as yah_ssm_postnorm_gate_f16.loom (with emit_prefill_pp.postnorm_heads, and postnorm_g16 for an f16
gate): the sum of squares per (token, head) row keeps that kernel's lane order, and every output value takes the same
ops, so the f16 output is bit-identical (row-major, or fragment-major as postnorm_tiled stores it).
A workgroup takes one head of 8 tokens (wave w: token 8 g + w), so each k-block of the head is one 8-row fragment of the
stream (gen_bfp16_encode "act": 72 contiguous bytes). In the output pass lane l < 16 takes columns 8 l .. 8 l + 7: a
16-byte f16 store and one row block, staged in LDS in stream order; after a barrier the 16 fragments go out as 8-byte
stores. The stream is ssm_out's first NPU K chunk: k = head * 128 + column must be < 1024 * passes.
"""
import gen_bfp16_encode as GE
import gen_npu_unpack as GU


def gen(B, h0, nh, ks, passes, tiled=False, gate16=True):
    assert B % 16 == 0 and (h0 + nh) * 128 <= 1024 * passes
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_postnorm_bfp.py (B={B} heads {h0}..{h0 + nh - 1} tiled={int(tiled)} gate16={int(gate16)}) -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_ssm_postnorm_fp16.head_count : %value: index where [range(%value, 1, 1048576)]")
    e("")
    e("kernel.def target(@yah_wave32) @yah_ssm_postnorm_fp16() {")
    e("  %unit = index.constant 1 : index")
    e("  %head_count = config.get @yah_ssm_postnorm_fp16.head_count : index")
    e("  %c8w = index.constant 8 : index")
    e("  %workgroup_size = index.constant 256 : index")
    e("  %tiles = index.div %head_count, %c8w : index")
    e("  kernel.launch.config workgroups(%tiles, %unit, %unit) workgroup_size(%workgroup_size, %unit, %unit) : index")
    e("} launch(%raw: buffer, %weight: buffer, %gate: buffer, %out: buffer, %ab: buffer) {")
    e("  %base = index.constant 0 : offset")
    for nm, v in (("c0", 0), ("c1", 1), ("c4", 4), ("c8", 8), ("c9", 9), ("c16", 16), ("c32", 32), ("c48", 48), ("c72", 72),
                  ("c128", 128), ("c256", 256), ("c384", 384), ("ch0", h0), ("cnh", nh)):
        e(f"  %{nm} = index.constant {v} : index")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %negone = scalar.constant -1.0 : f32")
    e("  %epsilon = scalar.constant 0.000001 : f32")
    e("  %inv_dim = scalar.constant 0.0078125 : f32")
    e(f"  %io_total = index.constant {48 * B * 128} : index")
    gt = "f16" if gate16 else "f32"
    e("  %raw_na, %weight_na, %gate_na, %out_na = buffer.assume.noalias %raw, %weight, %gate, %out : buffer, buffer, buffer, buffer")
    e("  %raw_view = buffer.view %raw_na[%base] : buffer -> view<[%io_total]xf32>")
    e(f"  %gate_view = buffer.view %gate_na[%base] : buffer -> view<[%io_total]x{gt}>")
    e("  %weight_view = buffer.view %weight_na[%base] : buffer -> view<[%c128]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%io_total]xf16>")
    nab = GE.layout_bytes("act", B, ks, passes)
    e(f"  %nab = index.constant {nab} : index")
    e("  %abv = buffer.view %ab[%base] : buffer -> view<[%nab]xi8>")
    e("  %bs_bytes = index.constant 1152 : offset")   # 16 fragments x 72 bytes
    e("  %bs_buf = buffer.alloca<workgroup> align(16) %bs_bytes : buffer")
    e("  %bs_view = buffer.view %bs_buf[%base] : buffer -> view<1152xi8>")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %lane = index.rem %tid, %c32 : index")
    e("  %subgroup = index.div %tid, %c32 : index")
    e("  %hh = index.rem %wg, %cnh : index")
    e("  %tg = index.div %wg, %cnh : index")
    e("  %tg8 = index.mul %tg, %c8 : index")
    e("  %tok = index.add %tg8, %subgroup : index")
    e("  %hd = index.add %hh, %ch0 : index")
    e("  %tok48 = index.mul %tok, %c48 : index")
    e("  %head = index.add %tok48, %hd : index")
    e("  %head_base = index.mul %head, %c128 : index")
    # the sum of squares: yah_ssm_postnorm_fp16's per-lane chain over columns lane + 32 j, then the subgroup reduction
    e("  %partial = scf.for %j = [%c0 to %c4 step %c1](%acc = %zero : f32) -> (f32) {")
    e("    %stride = index.mul %j, %c32 : index")
    e("    %column0 = index.add %lane, %stride : index")
    e("    %off = index.add %head_base, %column0 : index")
    e("    %v = view.load %raw_view[%off] : view<[%io_total]xf32> -> f32")
    e("    %sq = scalar.mulf %v, %v : f32")
    e("    %sum = scalar.addf %acc, %sq : f32")
    e("    scf.yield %sum : f32")
    e("  }")
    e("  %total = kernel.subgroup.reduce<addf> %partial : f32")
    e("  %scaled = scalar.mulf %total, %inv_dim : f32")
    e("  %shifted = scalar.addf %scaled, %epsilon : f32")
    e("  %root = scalar.sqrtf %shifted : f32")
    e("  %inv = scalar.divf %one, %root : f32")
    # output: lane l < 16 takes columns 8 l .. 8 l + 7 with the same per-value ops
    e("  %out_lane = index.cmp ult, %lane, %c16 : index")
    e("  scf.if %out_lane {")
    e("    %col0 = index.mul %lane, %c8 : index")
    e("    %off2 = index.add %head_base, %col0 : index")
    e("    %vx = vector.load %raw_view[%off2] : view<[%io_total]xf32> -> vector<8xf32>")
    e("    %vw = vector.load %weight_view[%col0] : view<[%c128]xf32> -> vector<8xf32>")
    e(f"    %vg = vector.load %gate_view[%off2] : view<[%io_total]x{gt}> -> vector<8x{gt}>")
    hs = []
    for x in range(8):
        e(f"    %v2_{x} = vector.extract %vx[{x}] : vector<8xf32> -> f32")
        e(f"    %w_{x} = vector.extract %vw[{x}] : vector<8xf32> -> f32")
        e(f"    %normed_{x} = scalar.mulf %v2_{x}, %inv : f32")
        e(f"    %weighted_{x} = scalar.mulf %normed_{x}, %w_{x} : f32")
        if gate16:
            e(f"    %gh_{x} = vector.extract %vg[{x}] : vector<8xf16> -> f16")
            e(f"    %g_{x} = scalar.extf %gh_{x} : f16 to f32")
        else:
            e(f"    %g_{x} = vector.extract %vg[{x}] : vector<8xf32> -> f32")
        e(f"    %negative_{x} = scalar.mulf %g_{x}, %negone : f32")
        e(f"    %exponential_{x} = scalar.expf<afn> %negative_{x} : f32")
        e(f"    %denominator_{x} = scalar.addf %one, %exponential_{x} : f32")
        e(f"    %sigmoid_{x} = scalar.divf %one, %denominator_{x} : f32")
        e(f"    %gated_{x} = scalar.mulf %g_{x}, %sigmoid_{x} : f32")
        e(f"    %result_{x} = scalar.mulf %weighted_{x}, %gated_{x} : f32")
        e(f"    %half_{x} = scalar.fptrunc %result_{x} : f32 to f16")
        hs.append(f"%half_{x}")
    e(f"    %vh = vector.from_elements {', '.join(hs)} : vector<8xf16>")
    if tiled:   # postnorm_tiled: token tok, k = head * 128 + column into 16 x 16 tiles of a [B][6144] matrix
        e("    %pt_k0 = index.mul %hd, %c128 : index")
        e("    %pt_k = index.add %pt_k0, %col0 : index")
        e("    %pt_tt = index.div %tok, %c16 : index")
        e("    %pt_tr = index.rem %tok, %c16 : index")
        e("    %pt_kt = index.div %pt_k, %c16 : index")
        e("    %pt_kr = index.rem %pt_k, %c16 : index")
        e("    %pt_a = index.mul %pt_tt, %c384 : index")
        e("    %pt_b = index.add %pt_a, %pt_kt : index")
        e("    %pt_c = index.mul %pt_b, %c256 : index")
        e("    %pt_d = index.mul %pt_tr, %c16 : index")
        e("    %pt_e = index.add %pt_c, %pt_d : index")
        e("    %pt_off0 = index.add %pt_e, %pt_kr : index")
        e(f"    %pt_last = index.constant {48 * B * 128 - 8} : index")
        e("    %pt_off = index.min %pt_off0, %pt_last : index")   # always in range; for the bound proof
        e("    vector.store %vh, %out_view[%pt_off] : vector<8xf16>, view<[%io_total]xf16>")
    else:
        e("    vector.store %vh, %out_view[%off2] : vector<8xf16>, view<[%io_total]xf16>")
    # the row block into LDS: fragment (k-block) lane, row (token) subgroup
    e("    %sf = index.mul %lane, %c72 : index")
    e("    %sr = index.mul %subgroup, %c9 : index")
    e("    %sb = index.add %sf, %sr : index")

    def store(x, v):
        a = "%sb"
        if x:
            e(f"    %so{x} = index.constant {x} : index")
            e(f"    %sa{x} = index.add %sb, %so{x} : index")
            a = f"%sa{x}"
        e(f"    view.store {v}, %bs_view[{a}] : i8, view<1152xi8>")
    GU.bfp_block(e, hs, "bq_", store)
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # copy-out: word id = fragment * 9 + 8-byte word; fragment f is k-block head * 16 + f of tokens 8 g .. 8 g + 7
    e("  %cnw = index.constant 144 : index")
    e("  %cp_live = index.cmp ult, %tid, %cnw : index")
    e("  scf.if %cp_live {")
    for nm, v in (("c2", 2), ("c144", 144), ("c72", 72), ("csub", 4), ("cpk", sum(ks)), ("cpass", passes)):
        e(f"    %cp_{nm} = index.constant {v} : index")
    e("    %cp_f = index.div %tid, %c9 : index")
    e("    %cp_w = index.rem %tid, %c9 : index")
    e("    %cp_k0 = index.mul %hd, %c16 : index")
    e("    %cp_kbi = index.add %cp_k0, %cp_f : index")
    frag = GE.emit_offset(e, "act", B, list(ks), passes, 64, True, "%tg", "%cp_kbi", p="cp_", ind="    ")
    e("    %cp_wo = index.mul %cp_w, %c8 : index")
    e(f"    %cp_ga = index.add {frag}, %cp_wo : index")
    e("    %cp_fb = index.mul %cp_f, %c72 : index")
    e("    %cp_la = index.add %cp_fb, %cp_wo : index")
    e("    %cp_v = vector.load %bs_view[%cp_la] : view<1152xi8> -> vector<8xi8>")
    e("    vector.store %cp_v, %abv[%cp_ga] : vector<8xi8>, view<[%nab]xi8>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"
