#!/usr/bin/env python3
"""Emit the GPU BFP16 encoder: an f16 [rows][K] matrix to NPU bfp16ebs8 fragments in the cascade GEMM's stream layout.

Fragment = 8 rows x 8 consecutive k: per row [E u8][8 x int8 m], value = m * 2^(E - 133), 72 bytes.
E is the f32 exponent field of the row block's max |x| (0 for an all-zero block); m = clamp(roundeven(x * 2^(133 - E)), -128, 127).
A slab is 16 rows x KS k-blocks: per k-block the fragments of rows 0-7 then 8-15 (144 bytes), padded to 64 bytes.

The NPU GEMM splits K per pass over the column's rows (K-slices with ks[r] k-blocks each, PK = sum(ks) per pass).
  act: [slice][M block][pass][MP slabs]   rows = tokens, MP = TM / 16 slabs per M block
  wgt: [column][slice][pass][NP slabs]    rows = output features, NP = TN / 16 slabs per NPU column
One work item per fragment; adjacent items take adjacent k-blocks of the same 8 rows (coalesced 16-byte loads).
"""
import sys

WG = 256


def slab_bytes(ks, pad=True):
    return (144 * ks + 63) // 64 * 64 if pad else 144 * ks


def layout_bytes(layout, rows, ks, passes, tile=64, pad=True):
    sb = [slab_bytes(k, pad) for k in ks]
    if layout == "act":
        return sum((rows // tile) * passes * (tile // 16) * b for b in sb)
    return (rows // tile) * sum(passes * (tile // 16) * b for b in sb)


def gen(layout, rows, ks, passes, tile=64, pad=True):
    """layout: "act" | "wgt"; rows: tokens (act) or NPU output features (wgt); ks: k-blocks per K-slice."""
    assert layout in ("act", "wgt") and rows % tile == 0 and tile % 16 == 0
    pk = sum(ks)
    kb = passes * pk
    K = 8 * kb
    sb = [slab_bytes(k, pad) for k in ks]
    sub = tile // 16                                   # slabs per M block (act) / per NPU column (wgt)
    if layout == "act":
        nblk = rows // tile
        base = [sum(nblk * passes * sub * sb[j] for j in range(i)) for i in range(len(ks))]
    else:
        base = [sum(passes * sub * sb[j] for j in range(i)) for i in range(len(ks))]
        panel = sum(passes * sub * b for b in sb)
    start = [sum(ks[:i]) for i in range(len(ks))]
    items = (rows // 8) * kb
    total = layout_bytes(layout, rows, ks, passes, tile, pad)
    name = f"yah_bfp16_encode_{layout}"
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_bfp16_encode.py ({layout} rows={rows} ks={ks} passes={passes} tile={tile} pad={int(pad)})"
      " -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e(f"kernel.def target(@yah_wave32) @{name}() {{")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgs = index.constant {(items + WG - 1) // WG} : index")
    e(f"  %wgsz = index.constant {WG} : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    e("} launch(%x: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    e(f"  %nx = index.constant {rows * K} : index")
    e(f"  %nout = index.constant {total} : index")
    e("  %x_na, %out_na = buffer.assume.noalias %x, %out : buffer, buffer")
    e("  %xv = buffer.view %x_na[%base] : buffer -> view<[%nx]xf16>")
    e("  %ov = buffer.view %out_na[%base] : buffer -> view<[%nout]xi8>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e(f"  %cwg = index.constant {WG} : index")
    e("  %item0 = index.mul %wg, %cwg : index")
    e("  %item = index.add %item0, %tid : index")
    e(f"  %citems = index.constant {items} : index")
    e("  %live = index.cmp ult, %item, %citems : index")
    e("  scf.if %live {")
    for nm, v in (("ckb", kb), ("cK", K), ("c8", 8), ("c2", 2), ("c144", 144), ("c72", 72), ("csub", sub),
                  ("cpk", pk), ("cpass", passes)):
        e(f"    %{nm} = index.constant {v} : index")
    e("    %g8 = index.div %item, %ckb : index")
    e("    %kbi = index.rem %item, %ckb : index")
    e("    %g16 = index.div %g8, %c2 : index")
    e("    %h = index.rem %g8, %c2 : index")
    e("    %blk = index.div %g16, %csub : index")          # M block (act) / NPU column (wgt)
    e("    %slab = index.rem %g16, %csub : index")
    e("    %pass = index.div %kbi, %cpk : index")
    e("    %o = index.rem %kbi, %cpk : index")
    # K-slice of o: a compare chain over the cumulative starts
    sel_base, sel_start, sel_sb = f"%cb0", f"%cs0", f"%csb0"
    for i in range(len(ks)):
        e(f"    %cb{i} = index.constant {base[i]} : index")
        e(f"    %cs{i} = index.constant {start[i]} : index")
        e(f"    %csb{i} = index.constant {sb[i]} : index")
    for i in range(1, len(ks)):
        e(f"    %ge{i} = index.cmp uge, %o, %cs{i} : index")
        e(f"    %sb_{i} = scf.select %ge{i}, %cb{i}, {sel_base} : index")
        e(f"    %ss_{i} = scf.select %ge{i}, %cs{i}, {sel_start} : index")
        e(f"    %sz_{i} = scf.select %ge{i}, %csb{i}, {sel_sb} : index")
        sel_base, sel_start, sel_sb = f"%sb_{i}", f"%ss_{i}", f"%sz_{i}"
    e(f"    %kin = index.sub %o, {sel_start} : index")
    if layout == "act":
        e("    %r0 = index.mul %blk, %cpass : index")
        e("    %r1 = index.add %r0, %pass : index")
        e("    %r2 = index.mul %r1, %csub : index")
        e("    %rec = index.add %r2, %slab : index")
        e(f"    %slo = index.mul %rec, {sel_sb} : index")
        e(f"    %off0 = index.add {sel_base}, %slo : index")
    else:
        e(f"    %cpanel = index.constant {panel} : index")
        e("    %po = index.mul %blk, %cpanel : index")
        e("    %r1 = index.mul %pass, %csub : index")
        e("    %rec = index.add %r1, %slab : index")
        e(f"    %slo = index.mul %rec, {sel_sb} : index")
        e(f"    %off1 = index.add {sel_base}, %slo : index")
        e("    %off0 = index.add %po, %off1 : index")
    e("    %ko = index.mul %kin, %c144 : index")
    e("    %ho = index.mul %h, %c72 : index")
    e("    %off2 = index.add %off0, %ko : index")
    e("    %frag = index.add %off2, %ho : index")
    # inputs: 8 rows x 8 halves
    e("    %row0 = index.mul %g8, %c8 : index")
    e("    %rb = index.mul %row0, %cK : index")
    e("    %kc = index.mul %kbi, %c8 : index")
    e("    %xb = index.add %rb, %kc : index")
    e("    %zero = scalar.constant 0.0 : f32")
    e("    %i23 = scalar.constant 23 : i32")
    e("    %i255 = scalar.constant 255 : i32")
    e("    %i260 = scalar.constant 260 : i32")
    e("    %i0 = scalar.constant 0 : i32")
    e("    %fmin = scalar.constant -128.0 : f32")
    e("    %fmax = scalar.constant 127.0 : f32")
    byts = []
    for r in range(8):
        e(f"    %ro{r} = index.constant {r * K} : index")
        e(f"    %xa{r} = index.add %xb, %ro{r} : index")
        e(f"    %xh{r} = vector.load %xv[%xa{r}] : view<[%nx]xf16> -> vector<8xf16>")
        e(f"    %xf{r} = vector.extf %xh{r} : vector<8xf16> to vector<8xf32>")
        vals = []
        for i in range(8):
            e(f"    %v{r}_{i} = vector.extract %xf{r}[{i}] : vector<8xf32> -> f32")
            e(f"    %a{r}_{i} = scalar.absf %v{r}_{i} : f32")
            vals.append(f"%v{r}_{i}")
        cur = f"%a{r}_0"
        for i in range(1, 8):
            e(f"    %mx{r}_{i} = scalar.maxnumf {cur}, %a{r}_{i} : f32")
            cur = f"%mx{r}_{i}"
        e(f"    %mb{r} = scalar.bitcast {cur} : f32 to i32")
        e(f"    %ms{r} = scalar.shrui %mb{r}, %i23 : i32")
        e(f"    %E{r} = scalar.andi %ms{r}, %i255 : i32")            # exponent field (0 for an all-zero block)
        e(f"    %ie{r} = scalar.subi %i260, %E{r} : i32")
        e(f"    %ib{r} = scalar.shli %ie{r}, %i23 : i32")
        e(f"    %iq0{r} = scalar.bitcast %ib{r} : i32 to f32")          # 2^(133 - E)
        e(f"    %z{r} = scalar.cmpi eq, %E{r}, %i0 : i32")
        e(f"    %iq{r} = scf.select %z{r}, %zero, %iq0{r} : f32")
        e(f"    %eb{r} = scalar.trunci %E{r} : i32 to i8")
        byts.append(f"%eb{r}")
        for i in range(8):
            e(f"    %s{r}_{i} = scalar.mulf {vals[i]}, %iq{r} : f32")
            e(f"    %n{r}_{i} = scalar.roundevenf %s{r}_{i} : f32")
            e(f"    %c0{r}_{i} = scalar.maxnumf %n{r}_{i}, %fmin : f32")
            e(f"    %c{r}_{i} = scalar.minnumf %c0{r}_{i}, %fmax : f32")
            e(f"    %t{r}_{i} = scalar.fptosi %c{r}_{i} : f32 to i32")
            e(f"    %m{r}_{i} = scalar.trunci %t{r}_{i} : i32 to i8")
            byts.append(f"%m{r}_{i}")
    for j in range(9):   # 72 bytes = 9 aligned 8-byte stores
        e(f"    %w{j} = vector.from_elements {', '.join(byts[8 * j:8 * j + 8])} : vector<8xi8>")
        e(f"    %wo{j} = index.constant {8 * j} : index")
        e(f"    %wa{j} = index.add %frag, %wo{j} : index")
        e(f"    vector.store %w{j}, %ov[%wa{j}] : vector<8xi8>, view<[%nout]xi8>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    if len(sys.argv) < 5:
        sys.exit("usage: gen_bfp16_encode.py act|wgt <rows> <ks,ks,...> <passes> [tile] [pad]")
    layout, rows, ks, passes = sys.argv[1], int(sys.argv[2]), [int(v) for v in sys.argv[3].split(",")], int(sys.argv[4])
    tile = int(sys.argv[5]) if len(sys.argv) > 5 else 64
    pad = (sys.argv[6] != "0") if len(sys.argv) > 6 else True
    sys.stdout.write(gen(layout, rows, ks, passes, tile, pad))


if __name__ == "__main__":
    main()
