#!/usr/bin/env python3
"""Emit yah_npu_unpack: the NPU GEMM's C into the GPU output's column slice.

C (gen_npu_gemm): [col][M block][mp][np][chain mh, nh][8 rows][8 cols] bf16, 64 x TN per (col, M block).
out: f32 [tokens][stride], or f16 with out16 (rounded as the f16-output GEMMs round, emit_prefill_pp.O16_MT); C column j
goes to out column off + j.
One work item per 8 consecutive C columns of one token: a 32-byte read and a 32-byte write.
A run of NJ = TN / 8 items takes one token's TN columns of an NPU column (TN * 4 contiguous bytes); each chunk's 4 tokens
read 128 contiguous bytes of C.
The next waves take the next columns, so 4 output rows fill left to right (DRAM-page friendly).
"""
import sys

import gen_bfp16_encode as GE
import gen_gemm_tile as TG
import gen_npu_gemm as GN

WG = 256


def gen(tokens, cols, stride, off, out16=False, resid=False, parts=1, swiglu=False, tiled=False, qg=False, rem=False,
        bfp=None):
    """resid: out = resid + C (f32; bindings c, resid, out), the kres GEMMs. parts: C is that many consecutive partial C
    blocks (the K chunks of one GEMM), summed in order. swiglu: C is the gate block then the up block; out =
    f16(silu(gate) * up) with the swiglu epilogue's scalar ops. tiled: f16 out fragment-major ([token / 16][column / 16]
    [token % 16][column % 16], an afrag GEMM's input). qg: the attention q projection's rows (heads x [256 q | 256
    gate], off = first NPU head * 512): C column j goes to q or gate (f32 [token][stride], bindings c, q, gate) at
    head * 256 + j % 256. rem (with resid): the GPU's f32 [token][TN * cols] partial over the rest of K (the NPU split's K
    remainder) is added to the C chunks before the residual (bindings c, resid, rem, out). bfp = (ks, passes, chunk_k,
    chunks) with swiglu: also the NPU's BFP16 activation stream of the next GEMM (ffn_down, whose input columns these are) for
    the columns in its K chunks (chunk_k columns each, gen_bfp16_encode "act" layout, one stream per chunk back to back;
    binding a after out): an item's 8 columns of one token are one bfp16ebs8 row block, encoded from the f16 values
    (stage_bfp: a workgroup takes 8 tokens x 32 column chunks, so each chunk's row blocks are one stream fragment)."""
    assert not (resid and (swiglu or tiled or out16)) and not (swiglu and parts > 1) and (resid or not rem)
    assert not bfp or swiglu
    assert not qg or not (resid or swiglu or tiled or out16)
    out16 = out16 or swiglu or tiled
    TN, NJ = GN.TN, GN.TN // 8
    assert tokens % 64 == 0 and off + TN * cols <= (2 if qg else 1) * stride
    items = tokens * cols * NJ
    c_elems = tokens * cols * TN
    L = []
    e = L.append
    flags = "".join(f" {k}" for k, v in (("resid", resid), ("rem", rem), ("swiglu", swiglu), ("tiled", tiled), ("qg", qg),
                                          ("bfp", bool(bfp))) if v) + (f" parts={parts}" if parts > 1 else "")
    e(f"// GENERATED by tools/gen_npu_unpack.py (tokens={tokens} cols={cols} stride={stride} off={off} out16={int(out16)}{flags})"
      " -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("kernel.def target(@yah_wave32) @yah_npu_unpack() {")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgs = index.constant {items // WG} : index")
    e(f"  %wgsz = index.constant {WG} : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    nblk = parts * (2 if swiglu else 1)
    if resid and rem:
        e("} launch(%c: buffer, %resid: buffer, %rem: buffer, %out: buffer) {")
    elif resid:
        e("} launch(%c: buffer, %resid: buffer, %out: buffer) {")
    elif qg:
        e("} launch(%c: buffer, %out: buffer, %gate: buffer) {")
    elif bfp:
        e("} launch(%c: buffer, %out: buffer, %ab: buffer) {")
    else:
        e("} launch(%c: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    e(f"  %nc = index.constant {c_elems * nblk // 2} : index")   # bf16 pairs
    e(f"  %no = index.constant {tokens * stride} : index")
    if resid and rem:
        e("  %c_na, %res_na, %rem_na, %out_na = buffer.assume.noalias %c, %resid, %rem, %out : buffer, buffer, buffer, buffer")
        e("  %rv = buffer.view %res_na[%base] : buffer -> view<[%no]xf32>")
        e(f"  %nrem = index.constant {tokens * cols * TN} : index")
        e("  %remv = buffer.view %rem_na[%base] : buffer -> view<[%nrem]xf32>")
    elif resid:
        e("  %c_na, %res_na, %out_na = buffer.assume.noalias %c, %resid, %out : buffer, buffer, buffer")
        e("  %rv = buffer.view %res_na[%base] : buffer -> view<[%no]xf32>")
    elif qg:
        e("  %c_na, %out_na, %gate_na = buffer.assume.noalias %c, %out, %gate : buffer, buffer, buffer")
        e("  %gv = buffer.view %gate_na[%base] : buffer -> view<[%no]xf32>")
    elif bfp:
        bks, bpasses, bck, bnck = bfp
        bcb = GE.layout_bytes("act", tokens, bks, bpasses)
        e("  %c_na, %out_na, %ab_na = buffer.assume.noalias %c, %out, %ab : buffer, buffer, buffer")
        e(f"  %nab = index.constant {bcb * bnck} : index")
        e("  %abv = buffer.view %ab_na[%base] : buffer -> view<[%nab]xi8>")
        e("  %bs_bytes = index.constant 2304 : offset")   # 32 column chunks x 8 tokens x 9 bytes
        e("  %bs_buf = buffer.alloca<workgroup> align(16) %bs_bytes : buffer")
        e("  %bs_view = buffer.view %bs_buf[%base] : buffer -> view<2304xi8>")
    else:
        e("  %c_na, %out_na = buffer.assume.noalias %c, %out : buffer, buffer")
    e("  %cv = buffer.view %c_na[%base] : buffer -> view<[%nc]xi32>")
    e("  %c16i = scalar.constant 16 : i32")
    e("  %chii = scalar.constant -65536 : i32")
    ot = "f16" if out16 else "f32"
    e(f"  %ov = buffer.view %out_na[%base] : buffer -> view<[%no]x{ot}>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    for nm, v in (("cwg", WG), ("c8", 8), ("c2", 2), ("c4", 4), ("c16", 16), ("c64", 64), ("cnj", NJ), ("cnp", GN.NP),
                  ("ctn", TN), ("ctile", 64 * TN), ("cmb", tokens // 64), ("ccols", cols), ("cstride", stride), ("coff", off)):
        e(f"  %{nm} = index.constant {v} : index")
    if tiled:
        e("  %c256t = index.constant 256 : index")
    if qg:
        e("  %c512q = index.constant 512 : index")
        e("  %c256q = index.constant 256 : index")
    if bfp:   # a workgroup takes 8 tokens x 32 column chunks, token fastest: each chunk's 8 row blocks are one stream fragment
        nq = cols * NJ // 32
        assert cols * NJ % 32 == 0 and tokens % 8 == 0 and WG == 256
        e(f"  %cnq = index.constant {nq} : index")
        e("  %c32b = index.constant 32 : index")
        e("  %tr = index.rem %tid, %c8 : index")
        e("  %cl = index.div %tid, %c8 : index")
        e("  %wq = index.rem %wg, %cnq : index")
        e("  %wp = index.div %wg, %cnq : index")
        e("  %tg8 = index.mul %wp, %c8 : index")
        e("  %tokg = index.add %tg8, %tr : index")
        e("  %jq = index.mul %wq, %c32b : index")
        e("  %jg = index.add %jq, %cl : index")
        e("  %col = index.div %jg, %cnj : index")
        e("  %j = index.rem %jg, %cnj : index")
        e("  %blk = index.div %tokg, %c64 : index")
        e("  %r = index.rem %tokg, %c64 : index")
    else:   # item = (((blk * 16 + r4) * cols + col) * 4 + rr) * NJ + j: token blk * 64 + r4 * 4 + rr, j = 8-column chunk
        e("  %i0 = index.mul %wg, %cwg : index")
        e("  %item = index.add %i0, %tid : index")
        e("  %j = index.rem %item, %cnj : index")
        e("  %q1 = index.div %item, %cnj : index")
        e("  %rr = index.rem %q1, %c4 : index")
        e("  %q2 = index.div %q1, %c4 : index")
        e("  %col = index.rem %q2, %ccols : index")
        e("  %q3 = index.div %q2, %ccols : index")
        e("  %r4 = index.rem %q3, %c16 : index")
        e("  %blk = index.div %q3, %c16 : index")
        e("  %r0 = index.mul %r4, %c4 : index")
        e("  %r = index.add %r0, %rr : index")
    e("  %tc = index.mul %col, %cmb : index")
    e("  %tile = index.add %tc, %blk : index")
    e("  %mpi = index.div %r, %c16 : index")
    e("  %r16 = index.rem %r, %c16 : index")
    e("  %mh = index.div %r16, %c8 : index")
    e("  %row = index.rem %r, %c8 : index")
    e("  %npi = index.div %j, %c2 : index")
    e("  %nh = index.rem %j, %c2 : index")
    # C element: tile * 64 * TN + ((mp * NP + np) * 4 + mh * 2 + nh) * 64 + row * 8
    e("  %a0 = index.mul %mpi, %cnp : index")
    e("  %a1 = index.add %a0, %npi : index")
    e("  %a2 = index.mul %a1, %c4 : index")
    e("  %a3 = index.mul %mh, %c2 : index")
    e("  %a4 = index.add %a2, %a3 : index")
    e("  %a5 = index.add %a4, %nh : index")
    e("  %a6 = index.mul %a5, %c64 : index")
    e("  %a7 = index.mul %row, %c8 : index")
    e("  %a8 = index.add %a6, %a7 : index")
    e("  %a9 = index.mul %tile, %ctile : index")
    e("  %ca = index.add %a9, %a8 : index")
    # out: token blk * 64 + r, column col * TN + 8 * j + off
    e("  %t0 = index.mul %blk, %c64 : index")
    e("  %tok = index.add %t0, %r : index")
    e("  %j0 = index.mul %col, %ctn : index")
    e("  %j1 = index.mul %j, %c8 : index")
    e("  %j2 = index.add %j0, %j1 : index")
    e("  %jo = index.add %j2, %coff : index")
    if tiled:   # 8 columns of one 16-column tile: contiguous inside the tile
        e(f"  %ctc = index.constant {stride // 16} : index")
        e("  %ot0 = index.div %tok, %c16 : index")
        e("  %otr = index.rem %tok, %c16 : index")
        e("  %oj0 = index.div %jo, %c16 : index")
        e("  %ojr = index.rem %jo, %c16 : index")
        e("  %ot1 = index.mul %ot0, %ctc : index")
        e("  %ot2 = index.add %ot1, %oj0 : index")
        e("  %ot3 = index.mul %ot2, %c256t : index")
        e("  %ot4 = index.mul %otr, %c16 : index")
        e("  %ot5 = index.add %ot3, %ot4 : index")
        e("  %oa0 = index.add %ot5, %ojr : index")
        e(f"  %olast = index.constant {tokens * stride - 8} : index")
        e("  %oa = index.min %oa0, %olast : index")   # always in range; for the bound proof
    elif qg:   # j -> head jo / 512, half (jo / 256) % 2, d = jo % 256
        e("  %qh = index.div %jo, %c512q : index")
        e("  %qw = index.rem %jo, %c512q : index")
        e("  %qd = index.rem %qw, %c256q : index")
        e("  %qisq = index.cmp ult, %qw, %c256q : index")
        e("  %qc0 = index.mul %qh, %c256q : index")
        e("  %qc = index.add %qc0, %qd : index")
        e("  %tb = index.mul %tok, %cstride : index")
        e("  %oa0 = index.add %tb, %qc : index")
        e(f"  %olast = index.constant {tokens * stride - 8} : index")
        e("  %oa = index.min %oa0, %olast : index")   # always in range; for the bound proof
    else:
        e("  %tb = index.mul %tok, %cstride : index")
        e("  %oa = index.add %tb, %jo : index")
    load_c(e, "%v", "%ca")
    val = "%v"
    for p in range(1, parts):   # the K chunks' partial sums
        e(f"  %cpo{p} = index.constant {p * c_elems} : index")
        e(f"  %cpa{p} = index.add %ca, %cpo{p} : index")
        load_c(e, f"%cp{p}", f"%cpa{p}")
        e(f"  %cs{p} = vector.addf {val}, %cp{p} : vector<8xf32>")
        val = f"%cs{p}"
    if rem:   # token tok, NPU column j2 of the [tokens][TN * cols] partial
        e(f"  %cremw = index.constant {cols * TN} : index")
        e("  %rmb = index.mul %tok, %cremw : index")
        e("  %rma = index.add %rmb, %j2 : index")
        e("  %rmv = vector.load %remv[%rma] : view<[%nrem]xf32> -> vector<8xf32>")
        e(f"  %rms = vector.addf {val}, %rmv : vector<8xf32>")
        val = "%rms"
    if resid:
        e("  %rsv = vector.load %rv[%oa] : view<[%no]xf32> -> vector<8xf32>")
        e(f"  %rs = vector.addf %rsv, {val} : vector<8xf32>")
        val = "%rs"
    if swiglu:   # silu(gate) * up per element, the swiglu epilogue's ops (gen_gemm_tile)
        e(f"  %cuo = index.constant {c_elems} : index")
        e("  %cua = index.add %ca, %cuo : index")
        load_c(e, "%vu", "%cua")
        e("  %one = scalar.constant 1.0 : f32")
        e("  %negone = scalar.constant -1.0 : f32")
        TG.rcp_consts(e)
        hs = []
        for x in range(8):
            e(f"  %g_{x} = vector.extract %v[{x}] : vector<8xf32> -> f32")
            e(f"  %u_{x} = vector.extract %vu[{x}] : vector<8xf32> -> f32")
            e(f"  %ng_{x} = scalar.mulf %g_{x}, %negone : f32")
            e(f"  %ex_{x} = scalar.expf<afn> %ng_{x} : f32")
            e(f"  %dn_{x} = scalar.addf %one, %ex_{x} : f32")
            TG.recip1(e, f"%iv_{x}", f"%dn_{x}")
            e(f"  %sg_{x} = scalar.mulf %g_{x}, %iv_{x} : f32")
            e(f"  %ac_{x} = scalar.mulf %sg_{x}, %u_{x} : f32")
            e(f"  %h_{x} = scalar.fptrunc %ac_{x} : f32 to f16")
            hs.append(f"%h_{x}")
        e(f"  %vh = vector.from_elements {', '.join(hs)} : vector<8xf16>")
        e("  vector.store %vh, %ov[%oa] : vector<8xf16>, view<[%no]xf16>")
        if bfp:
            stage_bfp(e, hs, tokens, bfp)
    elif qg:
        e("  scf.if %qisq {")
        e(f"    vector.store {val}, %ov[%oa] : vector<8xf32>, view<[%no]xf32>")
        e("  } else {")
        e(f"    vector.store {val}, %gv[%oa] : vector<8xf32>, view<[%no]xf32>")
        e("  }")
    elif out16:
        e(f"  %vh = vector.fptrunc {val} : vector<8xf32> to vector<8xf16>")
        e("  vector.store %vh, %ov[%oa] : vector<8xf16>, view<[%no]xf16>")
    else:
        e(f"  vector.store {val}, %ov[%oa] : vector<8xf32>, view<[%no]xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def load_c(e, dst, idx):
    """The 8 C values from element idx (a multiple of 8) as vector<8xf32>: 4 words of bf16 pairs, the low half first."""
    n = dst[1:]
    e(f"  %{n}_w = index.div {idx}, %c2 : index")
    e(f"  %{n}_v = vector.load %cv[%{n}_w] : view<[%nc]xi32> -> vector<4xi32>")
    vals = []
    for w in range(4):
        e(f"  %{n}_e{w} = vector.extract %{n}_v[{w}] : vector<4xi32> -> i32")
        e(f"  %{n}_l{w} = scalar.shli %{n}_e{w}, %c16i : i32")
        e(f"  %{n}_h{w} = scalar.andi %{n}_e{w}, %chii : i32")
        e(f"  %{n}_lf{w} = scalar.bitcast %{n}_l{w} : i32 to f32")
        e(f"  %{n}_hf{w} = scalar.bitcast %{n}_h{w} : i32 to f32")
        vals += [f"%{n}_lf{w}", f"%{n}_hf{w}"]
    e(f"  {dst} = vector.from_elements {', '.join(vals)} : vector<8xf32>")


def stage_bfp(e, hs, tokens, bfp):
    """The bfp form's row blocks (the item's 8 f16 values of token %tokg, column %jo..) staged in LDS as
    [chunk %cl][token %tr][9 bytes]; after a barrier the workgroup copies each live chunk's fragment (8 tokens, 72 bytes)
    into the stream as 8-byte stores (one stream offset per fragment)."""
    bks, bpasses, bck, bnck = bfp
    bcb = GE.layout_bytes("act", tokens, bks, bpasses)
    for nm, v in (("ck", bck), ("nck", bnck), ("cb", bcb), ("c9", 9), ("c72", 72)):
        e(f"  %bs_{nm} = index.constant {v} : index")
    e("  %bs_ci = index.div %jo, %bs_ck : index")
    e("  %bs_live = index.cmp ult, %bs_ci, %bs_nck : index")
    e("  scf.if %bs_live {")
    e("    %bs_r0 = index.mul %cl, %c8 : index")
    e("    %bs_r1 = index.add %bs_r0, %tr : index")
    e("    %bs_sb = index.mul %bs_r1, %bs_c9 : index")

    def store(x, v):
        a = "%bs_sb"
        if x:
            e(f"    %bs_so{x} = index.constant {x} : index")
            e(f"    %bs_sa{x} = index.add %bs_sb, %bs_so{x} : index")
            a = f"%bs_sa{x}"
        e(f"    view.store {v}, %bs_view[{a}] : i8, view<2304xi8>")
    bfp_block(e, hs, "bq_", store)
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for i in range(2):   # 32 fragments x 9 words = 288 copies over 256 lanes
        q = f"bc{i}_"
        e(f"  %{q}d0 = index.constant {256 * i} : index")
        e(f"  %{q}d = index.add %tid, %{q}d0 : index")
        e(f"  %{q}n = index.constant 288 : index")
        e(f"  %{q}in = index.cmp ult, %{q}d, %{q}n : index")
        e(f"  scf.if %{q}in {{")
        e(f"    %{q}cl = index.div %{q}d, %bs_c9 : index")
        e(f"    %{q}w = index.rem %{q}d, %bs_c9 : index")
        e(f"    %{q}jg = index.add %jq, %{q}cl : index")
        e(f"    %{q}jo0 = index.mul %{q}jg, %c8 : index")
        e(f"    %{q}jo = index.add %{q}jo0, %coff : index")   # TN = 8 NJ: the chunk's first output column
        e(f"    %{q}ci = index.div %{q}jo, %bs_ck : index")
        e(f"    %{q}live = index.cmp ult, %{q}ci, %bs_nck : index")
        e(f"    scf.if %{q}live {{")
        for nm, v in (("c2", 2), ("c144", 144), ("c72", 72), ("csub", 4), ("cpk", sum(bks)), ("cpass", bpasses)):
            e(f"      %{q}{nm} = index.constant {v} : index")
        e(f"      %{q}kcol = index.rem %{q}jo, %bs_ck : index")
        e(f"      %{q}kbi = index.div %{q}kcol, %c8 : index")
        frag = GE.emit_offset(e, "act", tokens, list(bks), bpasses, 64, True, "%wp", f"%{q}kbi", p=q, ind="      ")
        e(f"      %{q}co = index.mul %{q}ci, %bs_cb : index")
        e(f"      %{q}wo = index.mul %{q}w, %c8 : index")
        e(f"      %{q}g0 = index.add {frag}, %{q}co : index")
        e(f"      %{q}ga = index.add %{q}g0, %{q}wo : index")
        e(f"      %{q}fb = index.mul %{q}cl, %bs_c72 : index")
        e(f"      %{q}la = index.add %{q}fb, %{q}wo : index")
        e(f"      %{q}v = vector.load %bs_view[%{q}la] : view<2304xi8> -> vector<8xi8>")
        e(f"      vector.store %{q}v, %abv[%{q}ga] : vector<8xi8>, view<[%nab]xi8>")
        e("    }")
        e("  }")


def bfp_block(e, hs, p, store):
    """One bfp16ebs8 row block of 8 f16 values hs (gen_bfp16_encode.emit_encode's arithmetic): store(0, exponent byte),
    then store(x + 1, mantissa byte x), each right after its value."""
    for nm, v in (("i23", 23), ("i255", 255), ("i260", 260), ("i0", 0)):
        e(f"    %{p}{nm} = scalar.constant {v} : i32")
    for nm, v in (("zero", "0.0"), ("fmin", "-128.0"), ("fmax", "127.0")):
        e(f"    %{p}{nm} = scalar.constant {v} : f32")
    cur = None
    for x, h in enumerate(hs):
        e(f"    %{p}v{x} = scalar.extf {h} : f16 to f32")
        e(f"    %{p}a{x} = scalar.absf %{p}v{x} : f32")
        if cur is None:
            cur = f"%{p}a{x}"
        else:
            e(f"    %{p}mx{x} = scalar.maxnumf {cur}, %{p}a{x} : f32")
            cur = f"%{p}mx{x}"
    e(f"    %{p}mb = scalar.bitcast {cur} : f32 to i32")
    e(f"    %{p}ms = scalar.shrui %{p}mb, %{p}i23 : i32")
    e(f"    %{p}E = scalar.andi %{p}ms, %{p}i255 : i32")
    e(f"    %{p}ie = scalar.subi %{p}i260, %{p}E : i32")
    e(f"    %{p}ib = scalar.shli %{p}ie, %{p}i23 : i32")
    e(f"    %{p}iq0 = scalar.bitcast %{p}ib : i32 to f32")
    e(f"    %{p}z = scalar.cmpi eq, %{p}E, %{p}i0 : i32")
    e(f"    %{p}iq = scf.select %{p}z, %{p}zero, %{p}iq0 : f32")
    e(f"    %{p}eb = scalar.trunci %{p}E : i32 to i8")
    store(0, f"%{p}eb")
    for x in range(8):
        e(f"    %{p}s{x} = scalar.mulf %{p}v{x}, %{p}iq : f32")
        e(f"    %{p}n{x} = scalar.roundevenf %{p}s{x} : f32")
        e(f"    %{p}c0{x} = scalar.maxnumf %{p}n{x}, %{p}fmin : f32")
        e(f"    %{p}cl{x} = scalar.minnumf %{p}c0{x}, %{p}fmax : f32")
        e(f"    %{p}t{x} = scalar.fptosi %{p}cl{x} : f32 to i32")
        e(f"    %{p}m{x} = scalar.trunci %{p}t{x} : i32 to i8")
        store(x + 1, f"%{p}m{x}")


if __name__ == "__main__":
    if len(sys.argv) < 5:
        sys.exit("usage: gen_npu_unpack.py <tokens> <cols> <stride> <off> [out16]")
    sys.stdout.write(gen(*(int(v) for v in sys.argv[1:5]), out16=len(sys.argv) > 5 and sys.argv[5] != "0"))
