#!/usr/bin/env python3
"""Generate the chunked (WY-form) Gated DeltaNet prefill kernel.

usage: gen_gdn_chunk.py [out.loom]

Same ABI and math as tools/gen_deltanet_hip.py (yah_deltanet).
With k_hat = inv_k k and q_hat = q_scale q (yah_deltanet_prep_kq), and value head h reading key head h mod 16:

    S_t = a_t S_{t-1} + b_t (v_t - a_t S_{t-1} k_hat_t) k_hat_t^T,  o_t = S_t q_hat_t

computed per chunk of C = 32 tokens in the WY / UT form (checked against the recurrence to 1e-15):

    G_i = sum_{j<=i} log2 a_j          (log-space decay: every factor <= 1)
    A   = tril(b_i (k_i . k_j) 2^(G_i - G_j), -1)      P = tril(q_i . k_j 2^(G_i - G_j))
    T   = (I + A)^-1                   (forward substitution, f32)
    W   = T diag(b 2^G) K              U = T diag(b) V
    Vn  = U - W S^T                    (S = the state at the chunk start)
    O   = diag(2^G) Q S^T + P Vn
    S  <- 2^G_C S + (diag(2^(G_C - G)) Vn)^T K

Matmul inputs are f16 (WMMA, f32 accumulate); the state is carried in f32 accumulators.
f16 inputs cost mean KLD 3e-6 end to end.

Workgroup = (64 value rows, one head): grid (2, num_heads) x 256 threads (8 wave32 waves), like yah_deltanet.
Wave w owns the state tiles of rows 16 (w % 4) and keys 64 (w / 4) .. +63 (4 tiles),
and the (token, row) tile (w / 4, w % 4) of U, Vn and O. batch must be a multiple of 32.

WMMA accumulator layout (RDNA3 wave32, 16x16 f32): lane l holds column l % 16 and rows 2 i + l / 16, i = 0..7 (interleaved).
"""
import sys

C, R, D = 32, 64, 128
V8 = "vector<8xf32>"
V4 = "vector<4xf32>"
V16H = "vector<16xf16>"
V8H = "vector<8xf16>"
V4H = "vector<4xf16>"
# LDS regions (bytes); Kr and Qr adjacent so one 64-row view serves both
KR, QR, KT, VT, AF, PP, T1, T2, SS, GA = (0, 8704, 17408, 27648, 32768, 37888, 40448, 43008,
                                          45568, 62976)
POOL = GA + 6 * 32 * 4          # LG, G2, BETA, BG, GC, GG
assert POOL <= 65536
LG, G2, BETA, BG, GC, GG = range(6)
# OLATE: a chunk's O stores go into the next iteration, after its decay scan and next-chunk loads are issued. The
# compiler drains every outstanding global store (s_waitcnt_vscnt 0) before the scan's ds_bpermute and before global
# loads (no alias tracking), so stores at the chunk end stalled wave 0, the critical wave, at the next chunk's start.
OLATE = True
# CONV16: the conv hands over f16 K, Q, V with K and Q already normalized: f16(k * inv_k), f16(q * q_scale), f16(v), the
# same f32 ops and rounding this kernel did on the f32 conv output, so the result is bit-identical; half the bytes,
# and phase 1 only moves them into LDS. The f16 rows are carried raw through the prefetch.
CONV16 = True
TPRE = 2   # phase 3 column loads this many steps ahead (0: at their step); 2: -5.2% (3 hits 256 VGPRs, 4 spills)


def gen(head_base=0, launch_heads=0):
    """launch_heads > 0: a head-range variant, grid (2, launch_heads) over heads head_base .. head_base + launch_heads - 1
    (buffers and strides stay those of all num_heads heads), so a layer can run as two dispatches."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_gdn_chunk.py -- edit the generator.")
    e("// Chunked (WY) Gated DeltaNet, C = 32; ABI of yah_deltanet.")
    e("amdgpu.target<gfx1151> @gdn_w32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_deltanet.batch : %value: index where [range(%value, 32, 1048576)]")
    e("config.decl @yah_deltanet.qkv_size : %value: index where [range(%value, 128, 1048576)]")
    e("config.decl @yah_deltanet.inner_size : %value: index where [range(%value, 128, 1048576)]")
    e("config.decl @yah_deltanet.num_key_heads : %value: index where [range(%value, 1, 4096)]")
    e("config.decl @yah_deltanet.num_heads : %value: index where [range(%value, 1, 4096)]")
    e("")
    e("kernel.def target(@gdn_w32) @yah_deltanet() {")
    e("  %unit = index.constant 1 : index")
    e("  %c2 = index.constant 2 : index")
    e("  %c256 = index.constant 256 : index")
    e("  %num_heads = config.get @yah_deltanet.num_heads : index")
    if launch_heads:
        e(f"  %launch_heads = index.constant {launch_heads} : index")
        e("  kernel.launch.config workgroups(%c2, %launch_heads, %unit) workgroup_size(%c256, %unit, %unit) : index")
    else:
        e("  kernel.launch.config workgroups(%c2, %num_heads, %unit) workgroup_size(%c256, %unit, %unit) : index")
    e("} launch(%conv: buffer, %kq: buffer, %ab: buffer, %state: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 3, 4, 8, 16, 31, 32, 40, 48, 64, 128, 136, 16384):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %x32 = scalar.constant 32 : i32")
    e(f"  %zeros8 = vector.constant 0.0 : {V8}")
    e(f"  %zh16 = vector.constant 0.0 : {V16H}")
    e("  %m = index.constant 16 : index")
    e("  %n = index.constant 16 : index")
    e("  %k = index.constant 16 : index")
    e("  %batch = config.get @yah_deltanet.batch : index")
    e("  %qkv_size = config.get @yah_deltanet.qkv_size : index")
    e("  %inner_size = config.get @yah_deltanet.inner_size : index")
    e("  %num_key_heads = config.get @yah_deltanet.num_key_heads : index")
    e("  %num_heads = config.get @yah_deltanet.num_heads : index")
    e("  %conv_total = index.mul %batch, %qkv_size : index")
    e("  %kq_t0 = index.mul %batch, %num_key_heads : index")
    e("  %kq_total = index.mul %kq_t0, %c3 : index")
    e("  %ab_t0 = index.mul %batch, %num_heads : index")
    e("  %ab_total = index.mul %ab_t0, %c2 : index")
    e("  %state_total = index.mul %num_heads, %c16384 : index")
    e("  %out_total = index.mul %batch, %inner_size : index")
    e("  %cv_na, %kq_na, %ab_na, %st_na, %out_na = buffer.assume.noalias %conv, %kq, %ab, %state, %out : buffer, buffer, buffer, buffer, buffer")
    e(f"  %conv_view = buffer.view %cv_na[%base] : buffer -> view<[%conv_total]x{'f16' if CONV16 else 'f32'}>")
    e("  %kq_view = buffer.view %kq_na[%base] : buffer -> view<[%kq_total]xf32>")
    e("  %ab_view = buffer.view %ab_na[%base] : buffer -> view<[%ab_total]xf32>")
    e("  %state_view = buffer.view %st_na[%base] : buffer -> view<[%state_total]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%out_total]xf32>")
    e(f"  %pool_bytes = index.constant {POOL} : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pool_bytes : buffer")

    def region(name, off):
        e(f"  %{name}_o = index.constant {off} : offset")
        return f"%{name}_o"
    def lay(name, pitch):
        e(f"  %{name}_lay = encoding.layout.strided [1, {pitch}] : encoding<layout>")
        return f"%{name}_lay"
    o = region("kr", KR)
    e(f"  %kq_l = buffer.view %pool[{o}] : buffer -> view<64x136xf16>")          # rows 0-31 K (later W), 32-63 Q
    l_ = lay("kr", 136)
    e(f"  %kr_r = buffer.view %pool[{o}] : buffer -> view<128x32xf16, {l_}>")      # B[key][tok] from K[tok][key]
    o = region("kt", KT)
    e(f"  %kt_w = buffer.view %pool[{o}] : buffer -> view<128x40xf16>")
    l_ = lay("kt", 40)
    e(f"  %kt_r = buffer.view %pool[{o}] : buffer -> view<32x128xf16, {l_}>")      # B[tok][key] from Kt[key][tok]
    o = region("vt", VT)
    e(f"  %vt_w = buffer.view %pool[{o}] : buffer -> view<64x40xf16>")
    l_ = lay("vt", 40)
    e(f"  %vt_r = buffer.view %pool[{o}] : buffer -> view<32x64xf16, {l_}>")       # B[tok][row] from Vt[row][tok]
    o = region("af", AF)
    e(f"  %a_v = buffer.view %pool[{o}] : buffer -> view<32x36xf32>")
    e(f"  %vnp_w = buffer.view %pool[{o}] : buffer -> view<64x40xf16>")              # Vn'^T [row][tok] (after the solve)
    o = region("pp", PP)
    e(f"  %p_v = buffer.view %pool[{o}] : buffer -> view<32x40xf16>")
    o = region("t1", T1)
    e(f"  %t1_v = buffer.view %pool[{o}] : buffer -> view<32x40xf16>")
    o = region("t2", T2)
    e(f"  %t2_v = buffer.view %pool[{o}] : buffer -> view<32x40xf16>")
    o = region("ss", SS)
    e(f"  %s_w = buffer.view %pool[{o}] : buffer -> view<64x136xf16>")
    l_ = lay("ss", 136)
    e(f"  %s_r = buffer.view %pool[{o}] : buffer -> view<128x64xf16, {l_}>")       # B[key][row] from S[row][key]
    o = region("vn", T1)
    e(f"  %vn_w = buffer.view %pool[{o}] : buffer -> view<64x40xf16>")              # Vn^T [row][tok] (T1|T2, dead after phase 4)
    l_ = lay("vn", 40)
    e(f"  %vn_r = buffer.view %pool[{o}] : buffer -> view<32x64xf16, {l_}>")       # B[tok][row]
    o = region("ga", GA)
    e(f"  %ga = buffer.view %pool[{o}] : buffer -> view<6x32xf32>")
    for i, nm in enumerate(("LG", "G2", "BETA", "BG", "GC", "GG")):
        e(f"  %ga{nm} = index.constant {i} : index")

    e("  %blk = kernel.workgroup.id<x> : index")
    if launch_heads:
        e("  %h_rel = kernel.workgroup.id<y> : index")
        e(f"  %h_base = index.constant {head_base} : index")
        e("  %h = index.add %h_rel, %h_base : index")
    else:
        e("  %h = kernel.workgroup.id<y> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %sg = kernel.subgroup.id : index")
    e("  %lane = index.rem %tid, %c32 : index")
    e("  %sub = index.rem %lane, %c16 : index")
    e("  %half = index.div %lane, %c16 : index")
    e("  %half8 = index.mul %half, %c8 : index")
    e("  %rowbase = index.mul %blk, %c64 : index")
    e("  %kh = index.rem %h, %num_key_heads : index")
    e("  %q_rel = index.mul %kh, %c128 : index")
    e("  %k_head = index.add %num_key_heads, %kh : index")
    e("  %k_rel = index.mul %k_head, %c128 : index")
    e("  %v_heads = index.mul %num_key_heads, %c2 : index")
    e("  %v_head = index.add %v_heads, %h : index")
    e("  %v_rel0 = index.mul %v_head, %c128 : index")
    e("  %v_rel = index.add %v_rel0, %rowbase : index")
    e("  %o_rel0 = index.mul %h, %c128 : index")
    e("  %o_rel = index.add %o_rel0, %rowbase : index")
    e("  %s_head = index.mul %h, %c16384 : index")
    # wave roles
    e("  %w4 = index.rem %sg, %c4 : index")          # state row tile / U-O row tile
    e("  %wd4 = index.div %sg, %c4 : index")         # state key-tile group / U-O token tile
    e("  %srow0 = index.mul %w4, %c16 : index")      # state rows (within the block)
    e("  %skey0 = index.mul %wd4, %c64 : index")     # state keys
    e("  %ut0 = index.mul %wd4, %c16 : index")       # U / O tokens (within the chunk)
    e("  %ur0 = index.mul %w4, %c16 : index")        # U / O rows (within the block)
    e("  %isw0 = index.cmp eq, %sg, %c0 : index")
    e("  %isqk = index.cmp uge, %sg, %c4 : index")
    e("  %iskk = index.cmp ult, %sg, %c4 : index")
    e("  %my_row0 = index.add %srow0, %half : index")    # state acc element i: row my_row0 + 2 i
    e("  %kq_rel = index.add %rowbase, %my_row0 : index")
    e("  %ur_row = index.add %ur0, %sub : index")        # U/O acc column: row ur0 + sub
    e("  %ut_row0 = index.add %ut0, %half : index")      # U/O acc element i: token ut_row0 + 2 i

    # ---- initial state -> 4 accumulator tiles (element i: row my_row0 + i, key skey0 + 16 j + sub)
    st = []
    for j in range(4):
        e(f"  %sk{j}c = index.constant {16 * j} : index")
        e(f"  %sk{j}0 = index.add %skey0, %sk{j}c : index")
        e(f"  %sk{j} = index.add %sk{j}0, %sub : index")
        els = []
        for i in range(8):
            e(f"  %sr{j}_{i}c = index.constant {2 * i} : index")
            e(f"  %sr{j}_{i}0 = index.add %kq_rel, %sr{j}_{i}c : index")
            e(f"  %sr{j}_{i}1 = index.mul %sr{j}_{i}0, %c128 : index")
            e(f"  %sr{j}_{i}2 = index.add %sr{j}_{i}1, %sk{j} : index")
            e(f"  %sr{j}_{i}a = index.add %s_head, %sr{j}_{i}2 : index")
            e(f"  %sr{j}_{i} = view.load %state_view[%sr{j}_{i}a] : view<[%state_total]xf32> -> f32")
            els.append(f"%sr{j}_{i}")
        e(f"  %si{j}v = vector.from_elements {', '.join(els)} : {V8}")
        e(f"  %si{j} = vector.fragment<init> %si{j}v shape [%m, %n] : {V8}")
        st.append(f"%si{j}")
    e("  %nchunks = index.div %batch, %c32 : index")
    e("  %lastc = index.sub %nchunks, %c1 : index")
    # per-thread fetch map: token lt = tid / 8; K/Q dims (tid % 8) * 16 .. +15; V rows (tid % 8) * 8 .. +7
    # alpha / beta of token lane (wave 0 uses them)
    e("  %lt = index.div %tid, %c8 : index")
    e("  %seg8 = index.rem %tid, %c8 : index")
    e("  %dseg = index.mul %seg8, %c16 : index")
    e("  %rseg = index.mul %seg8, %c8 : index")
    e("  %qrow = index.add %lt, %c32 : index")

    def fetch(cidx, p, ind):
        e(f"{ind}%{p}t0 = index.mul {cidx}, %c32 : index")
        e(f"{ind}%{p}tok = index.add %{p}t0, %lt : index")
        e(f"{ind}%{p}crow = index.mul %{p}tok, %qkv_size : index")
        e(f"{ind}%{p}kqb0 = index.mul %{p}tok, %num_key_heads : index")
        e(f"{ind}%{p}kqb1 = index.add %{p}kqb0, %kh : index")
        e(f"{ind}%{p}kqb = index.mul %{p}kqb1, %c3 : index")
        e(f"{ind}%{p}kqb_1 = index.add %{p}kqb, %c1 : index")
        names = []
        if not CONV16:
            e(f"{ind}%{p}ik = view.load %kq_view[%{p}kqb] : view<[%kq_total]xf32> -> f32")
            e(f"{ind}%{p}qs = view.load %kq_view[%{p}kqb_1] : view<[%kq_total]xf32> -> f32")
            names = [f"%{p}ik", f"%{p}qs"]
        for nm, rel in (("k", "%k_rel"), ("q", "%q_rel")):
            e(f"{ind}%{p}{nm}base0 = index.add %{p}crow, {rel} : index")
            e(f"{ind}%{p}{nm}base = index.add %{p}{nm}base0, %dseg : index")
            for g in range(4):
                e(f"{ind}%{p}{nm}a{g}c = index.constant {4 * g} : index")
                e(f"{ind}%{p}{nm}a{g} = index.add %{p}{nm}base, %{p}{nm}a{g}c : index")
                if CONV16:
                    e(f"{ind}%{p}{nm}v{g} = vector.load %conv_view[%{p}{nm}a{g}] : view<[%conv_total]xf16> -> {V4H}")
                else:
                    e(f"{ind}%{p}{nm}v{g} = vector.load %conv_view[%{p}{nm}a{g}] : view<[%conv_total]xf32> -> {V4}")
                names.append(f"%{p}{nm}v{g}")
        e(f"{ind}%{p}va0 = index.add %{p}crow, %v_rel : index")
        e(f"{ind}%{p}va = index.add %{p}va0, %rseg : index")
        e(f"{ind}%{p}va4 = index.add %{p}va, %c4 : index")
        if CONV16:
            for q, a in ((0, "va"), (1, "va4")):
                e(f"{ind}%{p}vv{q} = vector.load %conv_view[%{p}{a}] : view<[%conv_total]xf16> -> {V4H}")
        else:
            e(f"{ind}%{p}vv0 = vector.load %conv_view[%{p}va] : view<[%conv_total]xf32> -> {V4}")
            e(f"{ind}%{p}vv1 = vector.load %conv_view[%{p}va4] : view<[%conv_total]xf32> -> {V4}")
        names += [f"%{p}vv0", f"%{p}vv1"]
        e(f"{ind}%{p}abt = index.add %{p}t0, %lane : index")
        e(f"{ind}%{p}ab0 = index.mul %{p}abt, %num_heads : index")
        e(f"{ind}%{p}ab1 = index.add %{p}ab0, %h : index")
        e(f"{ind}%{p}ab2 = index.mul %{p}ab1, %c2 : index")
        e(f"{ind}%{p}ab3 = index.add %{p}ab2, %c1 : index")
        e(f"{ind}%{p}al = view.load %ab_view[%{p}ab2] : view<[%ab_total]xf32> -> f32")
        e(f"{ind}%{p}be = view.load %ab_view[%{p}ab3] : view<[%ab_total]xf32> -> f32")
        names += [f"%{p}al", f"%{p}be"]
        return names
    def ostore(ind, t0, acc, p):
        """O tile (tokens ut_row0 + 2 i of the chunk at t0, row ur_row) -> out"""
        for i in range(8):
            e(f"{ind}%{p}e{i} = vector.extract {acc}[{i}] : {V8} -> f32")
            e(f"{ind}%{p}t{i}c = index.constant {2 * i} : index")
            e(f"{ind}%{p}t{i}0 = index.add {t0}, %ut_row0 : index")
            e(f"{ind}%{p}t{i}1 = index.add %{p}t{i}0, %{p}t{i}c : index")
            e(f"{ind}%{p}t{i}2 = index.mul %{p}t{i}1, %inner_size : index")
            e(f"{ind}%{p}t{i}3 = index.add %{p}t{i}2, %o_rel : index")
            e(f"{ind}%{p}t{i} = index.add %{p}t{i}3, %ur_row : index")
            e(f"{ind}view.store %{p}e{i}, %out_view[%{p}t{i}] : f32, view<[%out_total]xf32>")
    ftypes = ([] if CONV16 else ["f32", "f32"]) + [V4H if CONV16 else V4] * 10 + ["f32", "f32"]
    fnames = ([] if CONV16 else ["%inv_k", "%q_scale"]) + [f"%kv{g}" for g in range(4)] + [f"%qv{g}" for g in range(4)] + \
        ["%vv0", "%vv1", "%alpha", "%beta"]
    pre = fetch("%c0", "f0_", "  ")
    carried = ", ".join(f"%s{j} = {st[j]} : {V8}" for j in range(4))
    carried += ", " + ", ".join(f"{n} = {v} : {t}" for n, v, t in zip(fnames, pre, ftypes))
    res = ", ".join(f"%sf{j}" for j in range(4)) + ", " + ", ".join(f"%ff{i}" for i in range(len(fnames)))
    alltypes = ", ".join([V8] * 4 + ftypes)
    if OLATE:   # the previous chunk's O (8 f32 per lane), stored next iteration
        carried += f", %opv = %zeros8 : {V8}"
        res += ", %opf"
        alltypes += f", {V8}"
    e(f"  {res} = scf.for %ci = [%c0 to %nchunks step %c1]({carried}) -> ({alltypes}) {{")
    I = "    "
    e(f"{I}%t0 = index.mul %ci, %c32 : index")
    # ---- phase 1: K, Q (normalized, f16) -> Kr/Qr rows, Kt; V -> Vt; alpha / beta
    if not CONV16:
        e(f"{I}%ik4 = vector.splat %inv_k : {V4}")
        e(f"{I}%qs4 = vector.splat %q_scale : {V4}")
    for nm, rel, sc, row in (("k", "%k_rel", "%ik4", "%lt"), ("q", "%q_rel", "%qs4", "%qrow")):
        hs = []
        for g in range(4):
            if CONV16:
                hs.append(f"%{nm}v{g}")
                continue
            e(f"{I}%{nm}n{g} = vector.mulf %{nm}v{g}, {sc} : {V4}")
            e(f"{I}%{nm}h{g} = vector.fptrunc %{nm}n{g} : {V4} to {V4H}")
            hs.append(f"%{nm}h{g}")
        for p in range(2):
            e(f"{I}%{nm}c{p} = vector.concat<0> {hs[2 * p]}, {hs[2 * p + 1]} : {V4H}, {V4H} -> {V8H}")
            e(f"{I}%{nm}d{p} = index.add %dseg, %c{8 * p} : index")
            e(f"{I}vector.store %{nm}c{p}, %kq_l[{row}, %{nm}d{p}] : {V8H}, view<64x136xf16>")
        if nm == "k":   # transposed copy Kt[key][tok]
            for g in range(4):
                for i in range(4):
                    e(f"{I}%kt{g}{i}e = vector.extract {hs[g]}[{i}] : {V4H} -> f16")
                    e(f"{I}%kt{g}{i}c = index.constant {4 * g + i} : index")
                    e(f"{I}%kt{g}{i}r = index.add %dseg, %kt{g}{i}c : index")
                    e(f"{I}view.store %kt{g}{i}e, %kt_w[%kt{g}{i}r, %lt] : f16, view<128x40xf16>")
    # V: thread (token lt, rows (tid % 8) * 8 .. +7) -> Vt[row][tok]
    for p in range(2):
        vh = f"%vv{p}" if CONV16 else f"%vh{p}"   # f16 input: already the f16 the fptrunc would give
        if not CONV16:
            e(f"{I}%vh{p} = vector.fptrunc %vv{p} : {V4} to {V4H}")
        for i in range(4):
            e(f"{I}%vt{p}{i}e = vector.extract {vh}[{i}] : {V4H} -> f16")
            e(f"{I}%vt{p}{i}c = index.constant {4 * p + i} : index")
            e(f"{I}%vt{p}{i}r = index.add %rseg, %vt{p}{i}c : index")
            e(f"{I}view.store %vt{p}{i}e, %vt_w[%vt{p}{i}r, %lt] : f16, view<64x40xf16>")
    for j in range(4):    # state (f32 acc) -> S f16 [row][key]
        for i in range(8):
            e(f"{I}%se{j}{i} = vector.extract %s{j}[{i}] : {V8} -> f32")
            e(f"{I}%seh{j}{i} = scalar.fptrunc %se{j}{i} : f32 to f16")
            e(f"{I}%ser{j}{i}c = index.constant {2 * i} : index")
            e(f"{I}%ser{j}{i} = index.add %my_row0, %ser{j}{i}c : index")
            e(f"{I}%sek{j}{i}c = index.constant {16 * j} : index")
            e(f"{I}%sek{j}{i}0 = index.add %skey0, %sek{j}{i}c : index")
            e(f"{I}%sek{j}{i} = index.add %sek{j}{i}0, %sub : index")
            e(f"{I}view.store %seh{j}{i}, %s_w[%ser{j}{i}, %sek{j}{i}] : f16, view<64x136xf16>")
    # decay: wave 0, lane = token: G2 = inclusive scan of log2 alpha (one barrier)
    e(f"{I}scf.if %isw0 {{")
    # alpha can underflow to 0 (exp of a large negative): log2 gives -inf, and -inf - -inf = NaN in the decay differences.
    # Clamp at 2^-100 (= no carry-over).
    e(f"{I}  %lg0 = scalar.log2f<afn> %alpha : f32")
    e(f"{I}  %lgmin = scalar.constant -100.0 : f32")
    e(f"{I}  %lg = scalar.maxnumf %lg0, %lgmin : f32")
    e(f"{I}  %g2 = kernel.subgroup.scan<addf> %lg {{mode = inclusive, direction = forward}} : f32")
    e(f"{I}  %c31i = scalar.constant 31 : i32")
    e(f"{I}  %gtot = kernel.subgroup.broadcast %g2 from %c31i : f32, i32")
    e(f"{I}  %gg = scalar.exp2f<afn> %g2 : f32")
    e(f"{I}  %bg = scalar.mulf %beta, %gg : f32")
    e(f"{I}  %gcd = scalar.subf %gtot, %g2 : f32")
    e(f"{I}  %gc = scalar.exp2f<afn> %gcd : f32")
    e(f"{I}  view.store %g2, %ga[%gaG2, %lane] : f32, view<6x32xf32>")
    e(f"{I}  view.store %beta, %ga[%gaBETA, %lane] : f32, view<6x32xf32>")
    e(f"{I}  view.store %gg, %ga[%gaGG, %lane] : f32, view<6x32xf32>")
    e(f"{I}  view.store %bg, %ga[%gaBG, %lane] : f32, view<6x32xf32>")
    e(f"{I}  view.store %gc, %ga[%gaGC, %lane] : f32, view<6x32xf32>")
    e(f"{I}}}")
    # next chunk's inputs (clamped): in flight during phases 2-5
    e(f"{I}%cn0 = index.add %ci, %c1 : index")
    e(f"{I}%cn = index.min %cn0, %lastc : index")
    nxt = fetch("%cn", "nx_", I)
    if OLATE:
        # the previous chunk's O, unconditionally (a branch's join drains the loads just issued): at chunk 0 it stores
        # zeros to chunk 0's rows, which chunk 1 then overwrites with the real O (same wave, same addresses, in order)
        e(f"{I}%opc0 = index.max %ci, %c1 : index")
        e(f"{I}%opc = index.sub %opc0, %c1 : index")
        e(f"{I}%opt0 = index.mul %opc, %c32 : index")
        ostore(I, "%opt0", "%opv", "ox")
    e(f"{I}kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # ---- phase 2: KK^T (waves 0-3) -> A (f32), QK^T (waves 4-7) -> P (f16)
    e(f"{I}%p2t = index.rem %sg, %c4 : index")
    e(f"{I}%p2mi = index.div %p2t, %c2 : index")
    e(f"{I}%p2nj = index.rem %p2t, %c2 : index")
    e(f"{I}%p2m0 = index.mul %p2mi, %c16 : index")
    e(f"{I}%p2n0 = index.mul %p2nj, %c16 : index")
    e(f"{I}%p2qo = scf.select %isqk, %c32, %c0 : index")
    e(f"{I}%p2r = index.add %p2qo, %p2m0 : index")        # rows of the 64-row K|Q view
    e(f"{I}%zs = vector.fragment<init> %zeros8 shape [%m, %n] : {V8}")
    acc = "%zs"
    for c in range(8):
        e(f"{I}%p2k{c} = index.constant {16 * c} : index")
        e(f"{I}%p2a{c} = vector.fragment.load<lhs> %kq_l[%p2r, %p2k{c}] shape [%m, %k] : view<64x136xf16> -> {V16H}")
        e(f"{I}%p2b{c} = vector.fragment.load<rhs> %kr_r[%p2k{c}, %p2n0] shape [%k, %n] : view<128x32xf16, %kr_lay> -> {V16H}")
        e(f"{I}%p2c{c} = vector.mma %p2a{c}, %p2b{c}, {acc} : {V16H}, {V16H}, {V8}")
        acc = f"%p2c{c}"
    # element i: (m = p2m0 + half8 + i, n = p2n0 + sub)
    e(f"{I}%p2mr = index.add %p2m0, %half : index")     # element i: row p2mr + 2 i
    e(f"{I}%p2n = index.add %p2n0, %sub : index")
    e(f"{I}%gn = view.load %ga[%gaG2, %p2n] : view<6x32xf32> -> f32")
    gms, bms = [], []
    for i in range(8):
        e(f"{I}%p2e{i}c = index.constant {2 * i} : index")
        e(f"{I}%p2e{i} = index.add %p2mr, %p2e{i}c : index")
        e(f"{I}%gmx{i} = view.load %ga[%gaG2, %p2e{i}] : view<6x32xf32> -> f32")
        e(f"{I}%bmx{i} = view.load %ga[%gaBETA, %p2e{i}] : view<6x32xf32> -> f32")
        gms.append(f"%gmx{i}"); bms.append(f"%bmx{i}")
    e(f"{I}%gm8 = vector.from_elements {', '.join(gms)} : {V8}")
    e(f"{I}%bm8 = vector.from_elements {', '.join(bms)} : {V8}")
    e(f"{I}%gn8 = vector.splat %gn : {V8}")
    e(f"{I}%gd8 = vector.subf %gm8, %gn8 : {V8}")
    e(f"{I}%gd8c = vector.minnumf %gd8, %zeros8 : {V8}")
    e(f"{I}%ed8 = vector.exp2f<afn> %gd8c : {V8}")
    e(f"{I}%sd8 = vector.mulf {acc}, %ed8 : {V8}")
    e(f"{I}%ad8 = vector.mulf %sd8, %bm8 : {V8}")
    # A is stored negated: phase 3 (one wave) takes -A[i][j] t_j terms, so the negation runs here on every wave, 8 wide,
    # not 496 times on its critical path (negf is exact: the same bits)
    e(f"{I}%adn8 = vector.negf %ad8 : {V8}")
    e(f"{I}scf.if %iskk {{")
    for i in range(8):
        e(f"{I}  %am{i} = index.add %p2e{i}, %c0 : index")
        e(f"{I}  %agt{i} = index.cmp ugt, %am{i}, %p2n : index")
        e(f"{I}  %ae{i} = vector.extract %adn8[{i}] : {V8} -> f32")
        e(f"{I}  %av{i} = scf.select %agt{i}, %ae{i}, %zero : f32")
        e(f"{I}  view.store %av{i}, %a_v[%p2n, %am{i}] : f32, view<32x36xf32>")   # -A^T
    e(f"{I}}} else {{")
    for i in range(8):
        e(f"{I}  %pm{i} = index.add %p2e{i}, %c0 : index")
        e(f"{I}  %pge{i} = index.cmp uge, %pm{i}, %p2n : index")
        e(f"{I}  %pe{i} = vector.extract %sd8[{i}] : {V8} -> f32")
        e(f"{I}  %pv{i} = scf.select %pge{i}, %pe{i}, %zero : f32")
        e(f"{I}  %ph{i} = scalar.fptrunc %pv{i} : f32 to f16")
        e(f"{I}  view.store %ph{i}, %p_v[%pm{i}, %p2n] : f16, view<32x40xf16>")
    e(f"{I}}}")
    e(f"{I}kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # ---- phase 3: T = (I + A)^-1 by forward substitution, wave 0, lane = column
    e(f"{I}scf.if %isw0 {{")
    # right-looking: once t_j is final, every pending row i > j takes its -A[i][j] t_j term (independent fmas)
    # column j of -A = row j of -A^T (stored negated in phase 2)
    accs = []
    for i in range(C):
        e(f"{I}  %ti{i}c = index.constant {i} : index")
        e(f"{I}  %tie{i} = index.cmp eq, %ti{i}c, %lane : index")
        e(f"{I}  %td{i} = scf.select %tie{i}, %one, %zero : f32")
        accs.append(f"%td{i}")
    t = []

    def col_loads(j):
        for q in range((j + 1) // 4, 8):
            e(f"{I}  %tc{j}_{q}c = index.constant {4 * q} : index")
            e(f"{I}  %tc{j}_{q} = vector.load %a_v[%ti{j}c, %tc{j}_{q}c] : view<32x36xf32> -> {V4}")
    # The column loads go TPRE steps ahead, a fence keeping them above the step's fmas: the scheduler charges an LDS load
    # ~1 cycle and otherwise waits on each right before its fmas (2 in flight: the LDS latency 136 times per chunk on the
    # one wave every other waits for). Same fmas in the same order.
    for j in range(min(TPRE, C - 1)):
        col_loads(j)
    for j in range(C):
        t.append(accs[j])
        if j == C - 1:
            continue
        if TPRE:
            if j + TPRE < C - 1:
                col_loads(j + TPRE)
            e(f"{I}  scf.schedule.fence")
        else:
            col_loads(j)
        for i in range(j + 1, C):
            q = i // 4
            e(f"{I}  %tx{j}_{i} = vector.extract %tc{j}_{q}[{i % 4}] : {V4} -> f32")
            e(f"{I}  %tf{j}_{i} = scalar.fmaf %tx{j}_{i}, {t[j]}, {accs[i]} : f32")
            accs[i] = f"%tf{j}_{i}"
    e(f"{I}  %tbg = view.load %ga[%gaBG, %lane] : view<6x32xf32> -> f32")
    e(f"{I}  %tbe = view.load %ga[%gaBETA, %lane] : view<6x32xf32> -> f32")
    for i in range(C):
        e(f"{I}  %tw1_{i} = scalar.mulf {t[i]}, %tbg : f32")
        e(f"{I}  %tw2_{i} = scalar.mulf {t[i]}, %tbe : f32")
        e(f"{I}  %th1_{i} = scalar.fptrunc %tw1_{i} : f32 to f16")
        e(f"{I}  %th2_{i} = scalar.fptrunc %tw2_{i} : f32 to f16")
        e(f"{I}  view.store %th1_{i}, %t1_v[%ti{i}c, %lane] : f16, view<32x40xf16>")
        e(f"{I}  view.store %th2_{i}, %t2_v[%ti{i}c, %lane] : f16, view<32x40xf16>")
    e(f"{I}}}")
    e(f"{I}kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # ---- phase 4: W = T1 Kt (2 tiles / wave) -> rows 0-31 of the K|Q view; U = T2 Vt; S -> f16
    e(f"{I}%wm0 = index.mul %wd4, %c16 : index")
    for p in range(2):
        e(f"{I}%wn{p}c = index.constant {16 * p} : index")
        e(f"{I}%wn{p}a = index.mul %w4, %c32 : index")
        e(f"{I}%wnn{p} = index.add %wn{p}a, %wn{p}c : index")   # key tile 2 w4 + p
        acc = "%zs"
        for c in range(2):
            e(f"{I}%wk{p}{c} = index.constant {16 * c} : index")
            e(f"{I}%wa{p}{c} = vector.fragment.load<lhs> %t1_v[%wm0, %wk{p}{c}] shape [%m, %k] : view<32x40xf16> -> {V16H}")
            e(f"{I}%wb{p}{c} = vector.fragment.load<rhs> %kt_r[%wk{p}{c}, %wnn{p}] shape [%k, %n] : view<32x128xf16, %kt_lay> -> {V16H}")
            e(f"{I}%wc{p}{c} = vector.mma %wa{p}{c}, %wb{p}{c}, {acc} : {V16H}, {V16H}, {V8}")
            acc = f"%wc{p}{c}"
        e(f"{I}%wmr{p} = index.add %wm0, %half : index")
        e(f"{I}%wcol{p} = index.add %wnn{p}, %sub : index")
        for i in range(8):
            e(f"{I}%we{p}{i} = vector.extract {acc}[{i}] : {V8} -> f32")
            e(f"{I}%weh{p}{i} = scalar.fptrunc %we{p}{i} : f32 to f16")
            e(f"{I}%wr{p}{i}c = index.constant {2 * i} : index")
            e(f"{I}%wr{p}{i} = index.add %wmr{p}, %wr{p}{i}c : index")
            e(f"{I}view.store %weh{p}{i}, %kq_l[%wr{p}{i}, %wcol{p}] : f16, view<64x136xf16>")
    acc = "%zs"
    for c in range(2):
        e(f"{I}%uk{c} = index.constant {16 * c} : index")
        e(f"{I}%ua{c} = vector.fragment.load<lhs> %t2_v[%ut0, %uk{c}] shape [%m, %k] : view<32x40xf16> -> {V16H}")
        e(f"{I}%ub{c} = vector.fragment.load<rhs> %vt_r[%uk{c}, %ur0] shape [%k, %n] : view<32x64xf16, %vt_lay> -> {V16H}")
        e(f"{I}%uc{c} = vector.mma %ua{c}, %ub{c}, {acc} : {V16H}, {V16H}, {V8}")
        acc = f"%uc{c}"
    uacc = acc
    e(f"{I}kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # ---- phase 5: X = W S^T, O1 = Q S^T (tile tokens ut0, rows ur0); O1 shares the S fragment loads with X
    xa = "%zs"
    e(f"{I}%oq0 = index.add %ut0, %c32 : index")
    oa = "%zs"
    for c in range(8):
        e(f"{I}%xk{c} = index.constant {16 * c} : index")
        e(f"{I}%xb2{c} = vector.fragment.load<rhs> %s_r[%xk{c}, %ur0] shape [%k, %n] : view<128x64xf16, %ss_lay> -> {V16H}")
        e(f"{I}%xa{c} = vector.fragment.load<lhs> %kq_l[%ut0, %xk{c}] shape [%m, %k] : view<64x136xf16> -> {V16H}")
        e(f"{I}%xc{c} = vector.mma %xa{c}, %xb2{c}, {xa} : {V16H}, {V16H}, {V8}")
        xa = f"%xc{c}"
        e(f"{I}%oa{c} = vector.fragment.load<lhs> %kq_l[%oq0, %xk{c}] shape [%m, %k] : view<64x136xf16> -> {V16H}")
        e(f"{I}%oc{c} = vector.mma %oa{c}, %xb2{c}, {oa} : {V16H}, {V16H}, {V8}")
        oa = f"%oc{c}"
    e(f"{I}%vn8 = vector.subf {uacc}, {xa} : {V8}")
    gts, gcs = [], []
    for i in range(8):
        e(f"{I}%ux{i}c = index.constant {2 * i} : index")
        e(f"{I}%ux{i} = index.add %ut_row0, %ux{i}c : index")
        e(f"{I}%gtx{i} = view.load %ga[%gaGG, %ux{i}] : view<6x32xf32> -> f32")
        e(f"{I}%gcx{i} = view.load %ga[%gaGC, %ux{i}] : view<6x32xf32> -> f32")
        gts.append(f"%gtx{i}"); gcs.append(f"%gcx{i}")
    e(f"{I}%gt8 = vector.from_elements {', '.join(gts)} : {V8}")
    e(f"{I}%o18 = vector.mulf {oa}, %gt8 : {V8}")
    e(f"{I}%gc8 = vector.from_elements {', '.join(gcs)} : {V8}")
    e(f"{I}%vnp8 = vector.mulf %vn8, %gc8 : {V8}")
    for i in range(8):    # Vn^T, Vn'^T [row][tok]
        e(f"{I}%vne{i} = vector.extract %vn8[{i}] : {V8} -> f32")
        e(f"{I}%vnh{i} = scalar.fptrunc %vne{i} : f32 to f16")
        e(f"{I}%vpe{i} = vector.extract %vnp8[{i}] : {V8} -> f32")
        e(f"{I}%vph{i} = scalar.fptrunc %vpe{i} : f32 to f16")
        e(f"{I}%vtk{i} = index.add %ux{i}, %c0 : index")
        e(f"{I}view.store %vnh{i}, %vn_w[%ur_row, %vtk{i}] : f16, view<64x40xf16>")
        e(f"{I}view.store %vph{i}, %vnp_w[%ur_row, %vtk{i}] : f16, view<64x40xf16>")
    e(f"{I}kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # O = O1 + P Vn
    e(f"{I}%o1f = vector.fragment<init> %o18 shape [%m, %n] : {V8}")
    acc = "%o1f"
    for c in range(2):
        e(f"{I}%pk{c} = index.constant {16 * c} : index")
        e(f"{I}%pa{c} = vector.fragment.load<lhs> %p_v[%ut0, %pk{c}] shape [%m, %k] : view<32x40xf16> -> {V16H}")
        e(f"{I}%pb{c} = vector.fragment.load<rhs> %vn_r[%pk{c}, %ur0] shape [%k, %n] : view<32x64xf16, %vn_lay> -> {V16H}")
        e(f"{I}%pc{c} = vector.mma %pa{c}, %pb{c}, {acc} : {V16H}, {V16H}, {V8}")
        acc = f"%pc{c}"
    oacc = acc
    if not OLATE:
        ostore(I, "%t0", acc, "o")
    # S <- 2^G_C S + Vn'^T K
    e(f"{I}%gtot = view.load %ga[%gaGC, %c0] : view<6x32xf32> -> f32")   # 2^(G_31 - G_0)
    e(f"{I}%gg0 = view.load %ga[%gaGG, %c0] : view<6x32xf32> -> f32")
    e(f"{I}%gall = scalar.mulf %gtot, %gg0 : f32")                       # 2^(G_31 - G_0) 2^G_0 = 2^G_31
    e(f"{I}%gall8 = vector.splat %gall : {V8}")
    new = []
    for j in range(4):
        e(f"{I}%sd{j} = vector.mulf %s{j}, %gall8 : {V8}")
        e(f"{I}%sdf{j} = vector.fragment<init> %sd{j} shape [%m, %n] : {V8}")
        acc = f"%sdf{j}"
        for c in range(2):
            e(f"{I}%uk{j}{c} = index.constant {16 * c} : index")
            e(f"{I}%uka{j}{c} = vector.fragment.load<lhs> %vnp_w[%srow0, %uk{j}{c}] shape [%m, %k] : view<64x40xf16> -> {V16H}")
            e(f"{I}%ukn{j}{c}c = index.constant {16 * j} : index")
            e(f"{I}%ukn{j}{c} = index.add %skey0, %ukn{j}{c}c : index")
            e(f"{I}%ukb{j}{c} = vector.fragment.load<rhs> %kt_r[%uk{j}{c}, %ukn{j}{c}] shape [%k, %n] : view<32x128xf16, %kt_lay> -> {V16H}")
            e(f"{I}%ukc{j}{c} = vector.mma %uka{j}{c}, %ukb{j}{c}, {acc} : {V16H}, {V16H}, {V8}")
            acc = f"%ukc{j}{c}"
        new.append(acc)
    e(f"{I}kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e(f"{I}scf.yield {', '.join(new + nxt + ([oacc] if OLATE else []))} : {alltypes}")
    e("  }")
    if OLATE:   # the last chunk's O
        e("  %oplast = index.mul %lastc, %c32 : index")
        ostore("  ", "%oplast", "%opf", "ol")
    # ---- final state
    for j in range(4):
        for i in range(8):
            e(f"  %fe{j}{i} = vector.extract %sf{j}[{i}] : {V8} -> f32")
            e(f"  view.store %fe{j}{i}, %state_view[%sr{j}_{i}a] : f32, view<[%state_total]xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "yah_gdn_chunk_f32.loom"
    open(out, "w").write(gen())
    print(out)


if __name__ == "__main__":
    main()
