#!/usr/bin/env python3
"""Generate yah_ssm_conv_kq for the chunked DeltaNet (gen_gdn_chunk CONV16) reading the qkv GEMM's f16 output: the same
ops, roundings and summation orders as yah_ssm_conv_kq_f32.loom with emit_prefill_pp.conv_x16 / conv_n16, so the
output is bit-identical, but one workgroup per (256 channels, TB tokens) instead of per (256 channels, token).

usage: gen_conv_kq.py [out.loom]

Workgroup x < num_key_heads takes the q (lanes 0-127) and k (128-255) channels of key head x, the others 256 v channels;
workgroup y the tokens TB y .. TB y + TB - 1. Lane = channel: its 4 weights and the 3 previous inputs stay in registers,
each token's input is read once (the f32 kernel loaded 4 taps and 3 state values per output). For token t:
    s3 = x[t], s2 = x[t-1], s1 = x[t-2], s0 = x[t-3] (state[c][3], [2], [1] before token 0)
    dot = (s0 w0 + s1 w1) + (s2 w2 + s3 w3), result = dot * (1 / (1 + exp(-dot)))
v channels store f16(result). q / k workgroups keep the TB x 256 results in LDS; wave w takes tokens TB / 8 w ..:
lane l sums elements 4 l .. 4 l + 3 in order (k^2, q^2, k q), then a subgroup add, and lane 0 writes inv_k, q_scale
(1 / sqrt(sum + eps), times 1 / sqrt(128) for q) and k.q to scales [token][head][3] and to LDS; every lane then stores
f16(result * scale) of its channel.
Bindings: x (f16 [batch][qkv_dim]), conv_weights (f32 [qkv_dim][4]), state (f32 [qkv_dim][4]), conv_out
(f16 [batch][qkv_dim]), scales (f32 [batch][num_key_heads][3]).
"""
import sys

TB = 16   # tokens per workgroup (a multiple of 8, the batch a multiple of TB): 32 kept 3 workgroups per WGP (LDS)
D = 128   # channels per key head


def conv_steps(e, xs):
    """%r_t = silu(dot_t) for the tokens xs (f32 SSA names), window entering the first: %pw1, %pw2, %pw3 = x[-1], x[-2],
    x[-3]; weights %w0 .. %w3."""
    p1, p2, p3 = "%pw1", "%pw2", "%pw3"   # x[t-1], x[t-2], x[t-3]
    for t, x in enumerate(xs):
        s3, s2, s1, s0 = x, p1, p2, p3
        e(f"  %d0_{t} = scalar.mulf {s0}, %w0 : f32")
        e(f"  %d1_{t} = scalar.mulf {s1}, %w1 : f32")
        e(f"  %d2_{t} = scalar.mulf {s2}, %w2 : f32")
        e(f"  %d3_{t} = scalar.mulf {s3}, %w3 : f32")
        e(f"  %sa_{t} = scalar.addf %d0_{t}, %d1_{t} : f32")
        e(f"  %sb_{t} = scalar.addf %d2_{t}, %d3_{t} : f32")
        e(f"  %dot_{t} = scalar.addf %sa_{t}, %sb_{t} : f32")
        e(f"  %ng_{t} = scalar.mulf %dot_{t}, %negone : f32")
        e(f"  %ex_{t} = scalar.expf<afn> %ng_{t} : f32")
        e(f"  %dn_{t} = scalar.addf %one, %ex_{t} : f32")
        e(f"  %sg_{t} = scalar.divf %one, %dn_{t} : f32")
        e(f"  %r_{t} = scalar.mulf %dot_{t}, %sg_{t} : f32")
        p1, p2, p3 = s3, p1, p2


def gen(climit=None):
    """climit: only channels < climit (a NPU qkv split; gen_c takes the rest): v workgroups up to it, stores masked."""
    L = []
    e = L.append
    e("// GENERATED by tools/gen_conv_kq.py -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_ssm_conv_kq.batch : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_ssm_conv_kq.qkv_dim : %value: index where [range(%value, 1, 1048576)]")
    e("config.decl @yah_ssm_conv_kq.num_key_heads : %value: index where [range(%value, 1, 4096)]")
    e("")
    e("kernel.def target(@yah_wave32) @yah_ssm_conv_kq() {")
    e("  %unit = index.constant 1 : index")
    e("  %qkv_dim = config.get @yah_ssm_conv_kq.qkv_dim : index")
    e("  %batch = config.get @yah_ssm_conv_kq.batch : index")
    e("  %nkh = config.get @yah_ssm_conv_kq.num_key_heads : index")
    e("  %c256 = index.constant 256 : index")
    e(f"  %ctb = index.constant {TB} : index")
    e(f"  %cqk = index.constant {2 * D} : index")
    e("  %qk_dim = index.mul %nkh, %cqk : index")
    e("  %v_dim = index.sub %qkv_dim, %qk_dim : index")
    if climit:
        e(f"  %climit = index.constant {climit} : index")
        e("  %v_lim = index.sub %climit, %qk_dim : index")
        e("  %c255 = index.constant 255 : index")
        e("  %v_lim255 = index.add %v_lim, %c255 : index")
        e("  %vt = index.div %v_lim255, %c256 : index")
    else:
        e("  %vt = index.div %v_dim, %c256 : index")
    e("  %tiles = index.add %nkh, %vt : index")
    e("  %blocks = index.div %batch, %ctb : index")
    e("  kernel.launch.config workgroups(%tiles, %blocks, %unit) workgroup_size(%c256, %unit, %unit) : index")
    e("} launch(%x: buffer, %weights: buffer, %state: buffer, %out: buffer, %scales: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 3, 4, 32, 128, 256):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %ctb = index.constant {TB} : index")
    e("  %negone = scalar.constant -1.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %epsilon = scalar.constant 0.000001 : f32")
    e("  %batch = config.get @yah_ssm_conv_kq.batch : index")
    e("  %qkv_dim = config.get @yah_ssm_conv_kq.qkv_dim : index")
    e("  %nkh = config.get @yah_ssm_conv_kq.num_key_heads : index")
    e("  %x_total = index.mul %batch, %qkv_dim : index")
    e("  %w_total = index.mul %qkv_dim, %c4 : index")
    e("  %scale_cnt = index.mul %batch, %nkh : index")
    e("  %scale_total = index.mul %scale_cnt, %c3 : index")
    e("  %x_na, %w_na, %st_na, %out_na, %sc_na = buffer.assume.noalias %x, %weights, %state, %out, %scales : buffer, buffer, buffer, buffer, buffer")
    e("  %x_view = buffer.view %x_na[%base] : buffer -> view<[%x_total]xf16>")
    e("  %w_view = buffer.view %w_na[%base] : buffer -> view<[%w_total]xf32>")
    e("  %st_view = buffer.view %st_na[%base] : buffer -> view<[%w_total]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%x_total]xf16>")
    e("  %sc_view = buffer.view %sc_na[%base] : buffer -> view<[%scale_total]xf32>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %blk = kernel.workgroup.id<y> : index")
    e("  %lane = kernel.workitem.id<x> : index")
    e("  %t0 = index.mul %blk, %ctb : index")
    # channel map (the f32 kernel's)
    e("  %is_qk = index.cmp ult, %wg, %nkh : index")
    e("  %lane_hi = index.cmp uge, %lane, %c128 : index")
    e("  %lane_lo = index.rem %lane, %c128 : index")
    e("  %qh_base = index.mul %wg, %c128 : index")
    e("  %k_off = index.mul %nkh, %c128 : index")
    e("  %kh_base = index.add %k_off, %qh_base : index")
    e("  %qk_base = scf.select %lane_hi, %kh_base, %qh_base : index")
    e("  %qk_c = index.add %qk_base, %lane_lo : index")
    e("  %v_off = index.mul %k_off, %c2 : index")
    e("  %wg_v0 = index.max %wg, %nkh : index")
    e("  %wg_v = index.sub %wg_v0, %nkh : index")
    e("  %v_wb = index.mul %wg_v, %c256 : index")
    e("  %v_b = index.add %v_off, %v_wb : index")
    e("  %v_c = index.add %v_b, %lane : index")
    e("  %c = scf.select %is_qk, %qk_c, %v_c : index")
    e("  %c4i = index.mul %c, %c4 : index")
    for j in range(4):
        e(f"  %w{j}_off = index.add %c4i, %c{j} : index")
        e(f"  %w{j} = view.load %w_view[%w{j}_off] : view<[%w_total]xf32> -> f32")
    # the 3 inputs before t0: the state ring before token 0, else x (rows clamped, then selected: no branch)
    e("  %first = index.cmp eq, %blk, %c0 : index")
    for j in (1, 2, 3):
        e(f"  %st{j} = view.load %st_view[%w{j}_off] : view<[%w_total]xf32> -> f32")
        e(f"  %tp{j}0 = index.max %t0, %c{j} : index")
        e(f"  %tp{j} = index.sub %tp{j}0, %c{j} : index")
        e(f"  %tp{j}r = index.mul %tp{j}, %qkv_dim : index")
        e(f"  %xp{j}o = index.add %tp{j}r, %c : index")
        e(f"  %xp{j}h = view.load %x_view[%xp{j}o] : view<[%x_total]xf16> -> f16")
        e(f"  %xp{j} = scalar.extf %xp{j}h : f16 to f32")
    # window entering token t0: x[t0-1], x[t0-2], x[t0-3] (state 3, 2, 1 before token 0)
    e("  %pw1 = scf.select %first, %st3, %xp1 : f32")
    e("  %pw2 = scf.select %first, %st2, %xp2 : f32")
    e("  %pw3 = scf.select %first, %st1, %xp3 : f32")
    for t in range(TB):
        e(f"  %ct{t} = index.constant {t} : index")
        e(f"  %tk{t} = index.add %t0, %ct{t} : index")
        e(f"  %tr{t} = index.mul %tk{t}, %qkv_dim : index")
        e(f"  %xo{t} = index.add %tr{t}, %c : index")
        e(f"  %xh{t} = view.load %x_view[%xo{t}] : view<[%x_total]xf16> -> f16")
        e(f"  %x{t} = scalar.extf %xh{t} : f16 to f32")
    e("  %kq_bytes = index.constant " + str(TB * 256 * 4 + TB * 2 * 4) + " : offset")
    e("  %kq_l = buffer.alloca<workgroup> align(16) %kq_bytes : buffer")
    e(f"  %kq_lds = buffer.view %kq_l[%base] : buffer -> view<{TB * 256 + TB * 2}xf32>")
    conv_steps(e, [f"%x{t}" for t in range(TB)])
    # v channels: f16(result)
    e("  %is_v = index.cmp uge, %wg, %nkh : index")
    e("  scf.if %is_v {")
    if climit:
        e(f"    %climit_s = index.constant {climit} : index")
        e("    %in_lim = index.cmp ult, %c, %climit_s : index")
        e("    scf.if %in_lim {")
    for t in range(TB):
        e(f"    %rh{t} = scalar.fptrunc %r_{t} : f32 to f16")
        e(f"    view.store %rh{t}, %out_view[%xo{t}] : f16, view<[%x_total]xf16>")
    if climit:
        e("    }")
    e("  }")
    # q / k: the per-token norms (prep_kq) with the f32 kernel's order, then f16(result * scale)
    e("  scf.if %is_qk {")
    for t in range(TB):
        e(f"    %lo{t} = index.constant {256 * t} : index")
        e(f"    %la{t} = index.add %lo{t}, %lane : index")
        e(f"    view.store %r_{t}, %kq_lds[%la{t}] : f32, view<{TB * 256 + TB * 2}xf32>")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("    %wave = index.div %lane, %c32 : index")
    e("    %wl = index.rem %lane, %c32 : index")
    e("    %wquad = index.mul %wl, %c4 : index")
    e(f"    %ctpw = index.constant {TB // 8} : index")
    e("    %wt0 = index.mul %wave, %ctpw : index")   # wave w takes tokens TB / 8 * w ..
    e(f"    %cscl = index.constant {TB * 256} : index")
    for u in range(TB // 8):
        e(f"    %cu{u} = index.constant {u} : index")
        e(f"    %tu{u} = index.add %wt0, %cu{u} : index")         # token of this wave's step u
        e(f"    %rb{u} = index.mul %tu{u}, %c256 : index")
        e(f"    %eb{u} = index.add %rb{u}, %wquad : index")
        acc = ("%zero", "%zero", "%zero")
        for j in range(4):
            e(f"    %ej{u}_{j}c = index.constant {j} : index")
            e(f"    %ej{u}_{j} = index.add %eb{u}, %ej{u}_{j}c : index")
            e(f"    %ki{u}_{j} = index.add %ej{u}_{j}, %c128 : index")
            e(f"    %kv{u}_{j} = view.load %kq_lds[%ki{u}_{j}] : view<{TB * 256 + TB * 2}xf32> -> f32")
            e(f"    %qv{u}_{j} = view.load %kq_lds[%ej{u}_{j}] : view<{TB * 256 + TB * 2}xf32> -> f32")
            e(f"    %kk{u}_{j} = scalar.mulf %kv{u}_{j}, %kv{u}_{j} : f32")
            e(f"    %qq{u}_{j} = scalar.mulf %qv{u}_{j}, %qv{u}_{j} : f32")
            e(f"    %dq{u}_{j} = scalar.mulf %kv{u}_{j}, %qv{u}_{j} : f32")
            e(f"    %ka{u}_{j} = scalar.addf {acc[0]}, %kk{u}_{j} : f32")
            e(f"    %qa{u}_{j} = scalar.addf {acc[1]}, %qq{u}_{j} : f32")
            e(f"    %da{u}_{j} = scalar.addf {acc[2]}, %dq{u}_{j} : f32")
            acc = (f"%ka{u}_{j}", f"%qa{u}_{j}", f"%da{u}_{j}")
        e(f"    %ks{u} = kernel.subgroup.reduce<addf> {acc[0]} : f32")
        e(f"    %qs{u} = kernel.subgroup.reduce<addf> {acc[1]} : f32")
        e(f"    %kqs{u} = kernel.subgroup.reduce<addf> {acc[2]} : f32")
        e(f"    %l0_{u} = index.cmp ult, %wl, %c1 : index")
        e(f"    scf.if %l0_{u} {{")
        e(f"      %kse{u} = scalar.addf %ks{u}, %epsilon : f32")
        e(f"      %ksr{u} = scalar.sqrtf %kse{u} : f32")
        e(f"      %ik{u} = scalar.divf %one, %ksr{u} : f32")
        e(f"      %qse{u} = scalar.addf %qs{u}, %epsilon : f32")
        e(f"      %qsr{u} = scalar.sqrtf %qse{u} : f32")
        e(f"      %iq{u} = scalar.divf %one, %qsr{u} : f32")
        e(f"      %dim_i{u} = index.cast %c128 : index to i32")
        e(f"      %dim_f{u} = scalar.sitofp %dim_i{u} : i32 to f32")
        e(f"      %dim_r{u} = scalar.sqrtf %dim_f{u} : f32")
        e(f"      %idim{u} = scalar.divf %one, %dim_r{u} : f32")
        e(f"      %qsc{u} = scalar.mulf %iq{u}, %idim{u} : f32")
        e(f"      %tg{u} = index.add %t0, %tu{u} : index")
        e(f"      %sr{u} = index.mul %tg{u}, %nkh : index")
        e(f"      %sh{u} = index.add %sr{u}, %wg : index")
        e(f"      %sb{u} = index.mul %sh{u}, %c3 : index")
        e(f"      %sb1_{u} = index.add %sb{u}, %c1 : index")
        e(f"      %sb2_{u} = index.add %sb{u}, %c2 : index")
        e(f"      view.store %ik{u}, %sc_view[%sb{u}] : f32, view<[%scale_total]xf32>")
        e(f"      view.store %qsc{u}, %sc_view[%sb1_{u}] : f32, view<[%scale_total]xf32>")
        e(f"      view.store %kqs{u}, %sc_view[%sb2_{u}] : f32, view<[%scale_total]xf32>")
        e(f"      %ls{u}0 = index.mul %tu{u}, %c2 : index")
        e(f"      %ls{u} = index.add %cscl, %ls{u}0 : index")
        e(f"      %ls{u}q = index.add %ls{u}, %c1 : index")
        e(f"      view.store %ik{u}, %kq_lds[%ls{u}] : f32, view<{TB * 256 + TB * 2}xf32>")
        e(f"      view.store %qsc{u}, %kq_lds[%ls{u}q] : f32, view<{TB * 256 + TB * 2}xf32>")
        e("    }")
    e("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for t in range(TB):
        e(f"    %so{t} = index.constant {TB * 256 + 2 * t} : index")
        e(f"    %so{t}q = index.constant {TB * 256 + 2 * t + 1} : index")
        e(f"    %ksv{t} = view.load %kq_lds[%so{t}] : view<{TB * 256 + TB * 2}xf32> -> f32")
        e(f"    %qsv{t} = view.load %kq_lds[%so{t}q] : view<{TB * 256 + TB * 2}xf32> -> f32")
        e(f"    %osc{t} = scf.select %lane_hi, %ksv{t}, %qsv{t} : f32")
        e(f"    %on{t} = scalar.mulf %r_{t}, %osc{t} : f32")
        e(f"    %oh{t} = scalar.fptrunc %on{t} : f32 to f16")
        e(f"    view.store %oh{t}, %out_view[%xo{t}] : f16, view<[%x_total]xf16>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def tiles(climit, qk_dim=4096):
    """Workgroups along x of gen(climit): the q / k heads (16) and the v channels up to climit."""
    return 16 + (climit - qk_dim + 255) // 256


CW = 160   # gen_c lanes per workgroup: two NPU columns of gen_npu_gemm.TN
TC = 32    # gen_c tokens per workgroup


def gen_c(first, cols, batch, qkv_dim=10240):
    """yah_ssm_conv_kq_c: the conv for the v channels first .. first + cols * TN - 1 of a NPU qkv split, its input
    read straight from the NPU's C. Bit-identical to the f16 unpack (gen_npu_unpack) + gen.
    A workgroup takes CW channels x TC tokens. Staging: lanes take the unpack's work items (8 C columns of one token,
    token fastest, so a wave reads whole 128-byte C blocks), sum the C partials and round to f16 with the unpack's ops,
    into LDS as [token][channel], for the TC tokens and the 8 before them. Then lane = channel: its weights and the
    window in registers, the conv as gen, f16 out.
    Bindings: c (bf16 pairs), conv_weights, state (as gen), conv_out (f16 [batch][qkv_dim])."""
    import gen_npu_gemm as GN
    import gen_npu_unpack as GU
    n = cols * GN.TN
    assert n % CW == 0 and batch % TC == 0 and first >= 4096   # v channels only
    nwords = batch * n * GU.CG // 2
    rows = TC + 8   # LDS rows: tokens t0 - 8 .. t0 + TC - 1
    items = CW // 8   # 8-column items per token row
    L = []
    e = L.append
    e("// GENERATED by tools/gen_conv_kq.py gen_c -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("kernel.def target(@yah_wave32) @yah_ssm_conv_kq_c() {")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgx = index.constant {n // CW} : index")
    e(f"  %wgy = index.constant {batch // TC} : index")
    e(f"  %wgsz = index.constant {CW} : index")
    e("  kernel.launch.config workgroups(%wgx, %wgy, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    e("} launch(%cbuf: buffer, %weights: buffer, %state: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 3, 4, 8):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %c16i = scalar.constant 16 : i32")
    e("  %chii = scalar.constant -65536 : i32")
    e("  %negone = scalar.constant -1.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %qkv_dim = index.constant {qkv_dim} : index")
    e(f"  %x_total = index.constant {batch * qkv_dim} : index")
    e(f"  %w_total = index.constant {qkv_dim * 4} : index")
    e(f"  %nc = index.constant {nwords} : index")
    e(f"  %cgs = index.constant {batch * GN.TN} : index")   # C group stride (gen_npu_unpack.load_cg)
    e("  %c_na, %w_na, %st_na, %out_na = buffer.assume.noalias %cbuf, %weights, %state, %out : buffer, buffer, buffer, buffer")
    e("  %cv = buffer.view %c_na[%base] : buffer -> view<[%nc]xi32>")
    e("  %w_view = buffer.view %w_na[%base] : buffer -> view<[%w_total]xf32>")
    e("  %st_view = buffer.view %st_na[%base] : buffer -> view<[%w_total]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%x_total]xf16>")
    e(f"  %xs_bytes = index.constant {rows * CW * 2} : offset")
    e("  %xs_buf = buffer.alloca<workgroup> align(16) %xs_bytes : buffer")
    e(f"  %xs = buffer.view %xs_buf[%base] : buffer -> view<{rows * CW}xf16>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %blk = kernel.workgroup.id<y> : index")
    e("  %lane = kernel.workitem.id<x> : index")
    e(f"  %ctc = index.constant {TC} : index")
    e("  %t0 = index.mul %blk, %ctc : index")
    e(f"  %ccw = index.constant {CW} : index")
    e("  %nc0 = index.mul %wg, %ccw : index")
    # staging: lane = item * 8 + token in its 8-token group; LDS row r holds token t0 - 8 + r (block 0: rows 0-7 hold
    # tokens 0-7 instead, which the window never reads)
    e("  %tr = index.rem %lane, %c8 : index")
    e("  %it = index.div %lane, %c8 : index")
    e("  %itc0 = index.mul %it, %c8 : index")
    e("  %itc = index.add %nc0, %itc0 : index")   # the item's first NPU column
    la = GU.c_lane(e, "cl_", "%itc", batch)
    e(f"  %nel = index.constant {2 * nwords - (GU.CG - 1) * batch * GN.TN - 8} : index")   # last group-0 item start
    e("  %t0m8 = index.max %t0, %c8 : index")
    e("  %tlo = index.sub %t0m8, %c8 : index")
    for g in range(rows // 8):
        p = f"s{g}_"
        e(f"  %{p}o = index.constant {8 * g} : index")
        if g == 0:
            e(f"  %{p}t0 = index.add %tlo, %c0 : index")
        else:
            e(f"  %{p}g = index.constant {8 * (g - 1)} : index")
            e(f"  %{p}t0 = index.add %t0, %{p}g : index")
        e(f"  %{p}tk = index.add %{p}t0, %tr : index")
        tb = GU.c_tok(e, f"{p}k_", f"%{p}tk")
        e(f"  %{p}i0 = index.add {la}, {tb} : index")
        e(f"  %{p}i = index.min %{p}i0, %nel : index")   # in range by construction; for the bound proof
        GU.load_cg(e, f"%{p}v", f"%{p}i")
        e(f"  %{p}h = vector.fptrunc %{p}v : vector<8xf32> to vector<8xf16>")
        e(f"  %{p}r = index.add %tr, %{p}o : index")
        e(f"  %{p}a0 = index.mul %{p}r, %ccw : index")
        e(f"  %{p}a = index.add %{p}a0, %itc0 : index")
        e(f"  vector.store %{p}h, %xs[%{p}a] : vector<8xf16>, view<{rows * CW}xf16>")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # conv: lane = channel
    e(f"  %cfirst = index.constant {first} : index")
    e("  %c0a = index.add %cfirst, %nc0 : index")
    e("  %c = index.add %c0a, %lane : index")
    e("  %c4i = index.mul %c, %c4 : index")
    for j in range(4):
        e(f"  %w{j}_off = index.add %c4i, %c{j} : index")
        e(f"  %w{j} = view.load %w_view[%w{j}_off] : view<[%w_total]xf32> -> f32")
    def lds(name, row):
        e(f"  %{name}o = index.constant {row * CW} : index")
        e(f"  %{name}a = index.add %{name}o, %lane : index")
        e(f"  %{name}h = view.load %xs[%{name}a] : view<{rows * CW}xf16> -> f16")
        e(f"  %{name} = scalar.extf %{name}h : f16 to f32")
    e("  %first = index.cmp eq, %blk, %c0 : index")
    for j in (1, 2, 3):
        e(f"  %st{j} = view.load %st_view[%w{j}_off] : view<[%w_total]xf32> -> f32")
        lds(f"xp{j}", 8 - j)
    # window entering token t0: x[t0-1], x[t0-2], x[t0-3] (state 3, 2, 1 before token 0)
    e("  %pw1 = scf.select %first, %st3, %xp1 : f32")
    e("  %pw2 = scf.select %first, %st2, %xp2 : f32")
    e("  %pw3 = scf.select %first, %st1, %xp3 : f32")
    for t in range(TC):
        lds(f"x{t}", 8 + t)
    conv_steps(e, [f"%x{t}" for t in range(TC)])
    for t in range(TC):
        e(f"  %ct{t} = index.constant {t} : index")
        e(f"  %tk{t} = index.add %t0, %ct{t} : index")
        e(f"  %tr{t} = index.mul %tk{t}, %qkv_dim : index")
        e(f"  %xo{t} = index.add %tr{t}, %c : index")
        e(f"  %rh{t} = scalar.fptrunc %r_{t} : f32 to f16")
        e(f"  view.store %rh{t}, %out_view[%xo{t}] : f16, view<[%x_total]xf16>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def main():
    text = gen()
    if len(sys.argv) > 1:
        open(sys.argv[1], "w").write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
