#!/usr/bin/env python3
"""Emit yah_npu_unpack: the NPU GEMM's C into the GPU output's column slice.

C (gen_npu_gemm): [col][M block][mp][np][chain mh, nh][8 rows][8 cols] f32, 64 x 64 per (col, M block).
out: f32 [tokens][stride], or f16 with out16 (rounded as the f16-output GEMMs round, emit_prefill_pp.O16_MT); C column j
goes to out column off + j.
One work item per 8 consecutive C columns of one token: a 32-byte read and a 32-byte write.
A wave takes 4 tokens x one column's 8 chunks: 8 lanes store a token's 64 columns (256 contiguous bytes) and each chunk's 4 tokens read 128 contiguous bytes of C.
The next waves take the next columns, so 4 output rows fill left to right (DRAM-page friendly).
"""
import sys

import gen_gemm_tile as TG

WG = 256


def gen(tokens, cols, stride, off, out16=False, resid=False, parts=1, swiglu=False, tiled=False, qg=False, rem=False):
    """resid: out = resid + C (f32; bindings c, resid, out), the kres GEMMs. parts: C is that many consecutive partial C
    blocks (the K chunks of one GEMM), summed in order. swiglu: C is the gate block then the up block; out =
    f16(silu(gate) * up) with the swiglu epilogue's scalar ops. tiled: f16 out fragment-major ([token / 16][column / 16]
    [token % 16][column % 16], an afrag GEMM's input). qg: the attention q projection's rows (heads x [256 q | 256
    gate], off = first NPU head * 512): C column j goes to q or gate (f32 [token][stride], bindings c, q, gate) at
    head * 256 + j % 256. rem (with resid): the GPU's f32 [token][64 * cols] partial over the rest of K (the NPU split's K
    remainder) is added to the C chunks before the residual (bindings c, resid, rem, out)."""
    assert not (resid and (swiglu or tiled or out16)) and not (swiglu and parts > 1) and (resid or not rem)
    assert not qg or not (resid or swiglu or tiled or out16)
    out16 = out16 or swiglu or tiled
    assert tokens % 64 == 0 and off + 64 * cols <= (2 if qg else 1) * stride
    items = tokens * cols * 8
    c_elems = tokens * cols * 64
    L = []
    e = L.append
    flags = "".join(f" {k}" for k, v in (("resid", resid), ("rem", rem), ("swiglu", swiglu), ("tiled", tiled), ("qg", qg)) if v) + (f" parts={parts}" if parts > 1 else "")
    e(f"// GENERATED by tools/gen_npu_unpack.py (tokens={tokens} cols={cols} stride={stride} off={off} out16={int(out16)}{flags})"
      " -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("kernel.def target(@yah_wave32) @yah_npu_unpack() {")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgs = index.constant {items // WG} : index")
    e(f"  %wgsz = index.constant {WG} : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    nblk = parts * (2 if swiglu else 1)
    if resid and rem:
        e("} launch(%c: buffer, %resid: buffer, %rem: buffer, %out: buffer) {")
    elif resid:
        e("} launch(%c: buffer, %resid: buffer, %out: buffer) {")
    elif qg:
        e("} launch(%c: buffer, %out: buffer, %gate: buffer) {")
    else:
        e("} launch(%c: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    e(f"  %nc = index.constant {c_elems * nblk} : index")
    e(f"  %no = index.constant {tokens * stride} : index")
    if resid and rem:
        e("  %c_na, %res_na, %rem_na, %out_na = buffer.assume.noalias %c, %resid, %rem, %out : buffer, buffer, buffer, buffer")
        e("  %rv = buffer.view %res_na[%base] : buffer -> view<[%no]xf32>")
        e(f"  %nrem = index.constant {tokens * cols * 64} : index")
        e("  %remv = buffer.view %rem_na[%base] : buffer -> view<[%nrem]xf32>")
    elif resid:
        e("  %c_na, %res_na, %out_na = buffer.assume.noalias %c, %resid, %out : buffer, buffer, buffer")
        e("  %rv = buffer.view %res_na[%base] : buffer -> view<[%no]xf32>")
    elif qg:
        e("  %c_na, %out_na, %gate_na = buffer.assume.noalias %c, %out, %gate : buffer, buffer, buffer")
        e("  %gv = buffer.view %gate_na[%base] : buffer -> view<[%no]xf32>")
    else:
        e("  %c_na, %out_na = buffer.assume.noalias %c, %out : buffer, buffer")
    e("  %cv = buffer.view %c_na[%base] : buffer -> view<[%nc]xf32>")
    ot = "f16" if out16 else "f32"
    e(f"  %ov = buffer.view %out_na[%base] : buffer -> view<[%no]x{ot}>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    for nm, v in (("cwg", WG), ("c8", 8), ("c2", 2), ("c4", 4), ("c16", 16), ("c64", 64), ("c4096", 4096),
                  ("cmb", tokens // 64), ("ccols", cols), ("cstride", stride), ("coff", off)):
        e(f"  %{nm} = index.constant {v} : index")
    if tiled:
        e("  %c256t = index.constant 256 : index")
    if qg:
        e("  %c512q = index.constant 512 : index")
        e("  %c256q = index.constant 256 : index")
    # item = (((blk * 16 + r4) * cols + col) * 4 + rr) * 8 + j: token blk * 64 + r4 * 4 + rr, j = 8-column chunk (np, nh)
    e("  %i0 = index.mul %wg, %cwg : index")
    e("  %item = index.add %i0, %tid : index")
    e("  %j = index.rem %item, %c8 : index")
    e("  %q1 = index.div %item, %c8 : index")
    e("  %rr = index.rem %q1, %c4 : index")
    e("  %q2 = index.div %q1, %c4 : index")
    e("  %col = index.rem %q2, %ccols : index")
    e("  %q3 = index.div %q2, %ccols : index")
    e("  %r4 = index.rem %q3, %c16 : index")
    e("  %blk = index.div %q3, %c16 : index")
    e("  %r0 = index.mul %r4, %c4 : index")
    e("  %r = index.add %r0, %rr : index")
    e("  %tc = index.mul %col, %cmb : index")
    e("  %tile = index.add %tc, %blk : index")
    e("  %mpi = index.div %r, %c16 : index")
    e("  %r16 = index.rem %r, %c16 : index")
    e("  %mh = index.div %r16, %c8 : index")
    e("  %row = index.rem %r, %c8 : index")
    e("  %npi = index.div %j, %c2 : index")
    e("  %nh = index.rem %j, %c2 : index")
    # C element: tile * 4096 + ((mp * 4 + np) * 4 + mh * 2 + nh) * 64 + row * 8
    e("  %a0 = index.mul %mpi, %c4 : index")
    e("  %a1 = index.add %a0, %npi : index")
    e("  %a2 = index.mul %a1, %c4 : index")
    e("  %a3 = index.mul %mh, %c2 : index")
    e("  %a4 = index.add %a2, %a3 : index")
    e("  %a5 = index.add %a4, %nh : index")
    e("  %a6 = index.mul %a5, %c64 : index")
    e("  %a7 = index.mul %row, %c8 : index")
    e("  %a8 = index.add %a6, %a7 : index")
    e("  %a9 = index.mul %tile, %c4096 : index")
    e("  %ca = index.add %a9, %a8 : index")
    # out: token blk * 64 + r, column col * 64 + 8 * j + off
    e("  %t0 = index.mul %blk, %c64 : index")
    e("  %tok = index.add %t0, %r : index")
    e("  %j0 = index.mul %col, %c64 : index")
    e("  %j1 = index.mul %j, %c8 : index")
    e("  %j2 = index.add %j0, %j1 : index")
    e("  %jo = index.add %j2, %coff : index")
    if tiled:   # 8 columns of one 16-column tile: contiguous inside the tile
        e(f"  %ctc = index.constant {stride // 16} : index")
        e("  %ot0 = index.div %tok, %c16 : index")
        e("  %otr = index.rem %tok, %c16 : index")
        e("  %oj0 = index.div %jo, %c16 : index")
        e("  %ojr = index.rem %jo, %c16 : index")
        e("  %ot1 = index.mul %ot0, %ctc : index")
        e("  %ot2 = index.add %ot1, %oj0 : index")
        e("  %ot3 = index.mul %ot2, %c256t : index")
        e("  %ot4 = index.mul %otr, %c16 : index")
        e("  %ot5 = index.add %ot3, %ot4 : index")
        e("  %oa0 = index.add %ot5, %ojr : index")
        e(f"  %olast = index.constant {tokens * stride - 8} : index")
        e("  %oa = index.min %oa0, %olast : index")   # always in range; for the bound proof
    elif qg:   # j -> head jo / 512, half (jo / 256) % 2, d = jo % 256
        e("  %qh = index.div %jo, %c512q : index")
        e("  %qw = index.rem %jo, %c512q : index")
        e("  %qd = index.rem %qw, %c256q : index")
        e("  %qisq = index.cmp ult, %qw, %c256q : index")
        e("  %qc0 = index.mul %qh, %c256q : index")
        e("  %qc = index.add %qc0, %qd : index")
        e("  %tb = index.mul %tok, %cstride : index")
        e("  %oa0 = index.add %tb, %qc : index")
        e(f"  %olast = index.constant {tokens * stride - 8} : index")
        e("  %oa = index.min %oa0, %olast : index")   # always in range; for the bound proof
    else:
        e("  %tb = index.mul %tok, %cstride : index")
        e("  %oa = index.add %tb, %jo : index")
    e("  %v = vector.load %cv[%ca] : view<[%nc]xf32> -> vector<8xf32>")
    val = "%v"
    for p in range(1, parts):   # the K chunks' partial sums
        e(f"  %cpo{p} = index.constant {p * c_elems} : index")
        e(f"  %cpa{p} = index.add %ca, %cpo{p} : index")
        e(f"  %cp{p} = vector.load %cv[%cpa{p}] : view<[%nc]xf32> -> vector<8xf32>")
        e(f"  %cs{p} = vector.addf {val}, %cp{p} : vector<8xf32>")
        val = f"%cs{p}"
    if rem:   # token tok, NPU column j2 of the [tokens][64 * cols] partial
        e(f"  %cremw = index.constant {cols * 64} : index")
        e("  %rmb = index.mul %tok, %cremw : index")
        e("  %rma = index.add %rmb, %j2 : index")
        e("  %rmv = vector.load %remv[%rma] : view<[%nrem]xf32> -> vector<8xf32>")
        e(f"  %rms = vector.addf {val}, %rmv : vector<8xf32>")
        val = "%rms"
    if resid:
        e("  %rsv = vector.load %rv[%oa] : view<[%no]xf32> -> vector<8xf32>")
        e(f"  %rs = vector.addf %rsv, {val} : vector<8xf32>")
        val = "%rs"
    if swiglu:   # silu(gate) * up per element, the swiglu epilogue's ops (gen_gemm_tile)
        e(f"  %cuo = index.constant {c_elems} : index")
        e("  %cua = index.add %ca, %cuo : index")
        e("  %vu = vector.load %cv[%cua] : view<[%nc]xf32> -> vector<8xf32>")
        e("  %one = scalar.constant 1.0 : f32")
        e("  %negone = scalar.constant -1.0 : f32")
        TG.rcp_consts(e)
        hs = []
        for x in range(8):
            e(f"  %g_{x} = vector.extract %v[{x}] : vector<8xf32> -> f32")
            e(f"  %u_{x} = vector.extract %vu[{x}] : vector<8xf32> -> f32")
            e(f"  %ng_{x} = scalar.mulf %g_{x}, %negone : f32")
            e(f"  %ex_{x} = scalar.expf<afn> %ng_{x} : f32")
            e(f"  %dn_{x} = scalar.addf %one, %ex_{x} : f32")
            TG.recip1(e, f"%iv_{x}", f"%dn_{x}")
            e(f"  %sg_{x} = scalar.mulf %g_{x}, %iv_{x} : f32")
            e(f"  %ac_{x} = scalar.mulf %sg_{x}, %u_{x} : f32")
            e(f"  %h_{x} = scalar.fptrunc %ac_{x} : f32 to f16")
            hs.append(f"%h_{x}")
        e(f"  %vh = vector.from_elements {', '.join(hs)} : vector<8xf16>")
        e("  vector.store %vh, %ov[%oa] : vector<8xf16>, view<[%no]xf16>")
    elif qg:
        e("  scf.if %qisq {")
        e(f"    vector.store {val}, %ov[%oa] : vector<8xf32>, view<[%no]xf32>")
        e("  } else {")
        e(f"    vector.store {val}, %gv[%oa] : vector<8xf32>, view<[%no]xf32>")
        e("  }")
    elif out16:
        e(f"  %vh = vector.fptrunc {val} : vector<8xf32> to vector<8xf16>")
        e("  vector.store %vh, %ov[%oa] : vector<8xf16>, view<[%no]xf16>")
    else:
        e(f"  vector.store {val}, %ov[%oa] : vector<8xf32>, view<[%no]xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    if len(sys.argv) < 5:
        sys.exit("usage: gen_npu_unpack.py <tokens> <cols> <stride> <off> [out16]")
    sys.stdout.write(gen(*(int(v) for v in sys.argv[1:5]), out16=len(sys.argv) > 5 and sys.argv[5] != "0"))
