#!/usr/bin/env python3
"""Small single-token decode kernels.

  rmsnorm   out[i] = (x[i] * rsqrt(sum(x^2) / D + eps)) * w[i], one 512-lane workgroup.
            Same math as the prefill yah_rmsnorm_f32; its one 32-lane subgroup per row is too slow for one row (~70 us).
  deltanet  one gated DeltaNet step (conv, recurrence, gated RMSNorm), one workgroup per value head.
  embed     dequantize the IQ4_XS token_embd row of the current token.
Usage: gen_decode_misc.py <rmsnorm|deltanet|embed> <out.loom>
"""
import sys


def gen_rmsnorm(D=5120, eps=1e-6, NT=512):
    assert D % NT == 0
    per = D // NT
    nw = NT // 32
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_misc.py (rmsnorm) -- edit the generator.")
    e("amdgpu.target<gfx1151> @dm32 {subgroup_size = 32}")
    e("kernel.def target(@dm32) @yah_dec_rmsnorm() {")
    e("  %u1 = index.constant 1 : index")
    e(f"  %nt = index.constant {NT} : index")
    e("  kernel.launch.config workgroups(%u1, %u1, %u1) workgroup_size(%nt, %u1, %u1) : index")
    e("} launch(%x: buffer, %w: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    e("  %c0 = index.constant 0 : index")
    e("  %c32 = index.constant 32 : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e(f"  %invd = scalar.constant {1.0 / D!r} : f32")
    e(f"  %eps = scalar.constant {eps!r} : f32")
    e("  %x_na, %w_na, %o_na = buffer.assume.noalias %x, %w, %out : buffer, buffer, buffer")
    e(f"  %xv = buffer.view %x_na[%base] : buffer -> view<{D}xf32>")
    e(f"  %wv = buffer.view %w_na[%base] : buffer -> view<{D}xf32>")
    e(f"  %ov = buffer.view %o_na[%base] : buffer -> view<{D}xf32>")
    e(f"  %pb = index.constant {nw * 4} : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e(f"  %pv = buffer.view %pool[%base] : buffer -> view<{nw}xf32>")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %wave = index.div %t, %c32 : index")
    e("  %ln = index.rem %t, %c32 : index")
    acc = "%zf"
    for i in range(per):
        e(f"  %o{i}c = index.constant {i * NT} : index")
        e(f"  %i{i} = index.add %t, %o{i}c : index")
        e(f"  %x{i} = view.load %xv[%i{i}] : view<{D}xf32> -> f32")
        e(f"  %s{i} = scalar.fmaf %x{i}, %x{i}, {acc} : f32")
        acc = f"%s{i}"
    e(f"  %wsum = kernel.subgroup.reduce<addf> {acc} : f32")
    e("  %l0 = index.cmp eq, %ln, %c0 : index")
    e("  scf.if %l0 {")
    e(f"    view.store %wsum, %pv[%wave] : f32, view<{nw}xf32>")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    cur = "%zf"
    for w in range(nw):
        e(f"  %pw{w}i = index.constant {w} : index")
        e(f"  %pw{w} = view.load %pv[%pw{w}i] : view<{nw}xf32> -> f32")
        e(f"  %ps{w} = scalar.addf {cur}, %pw{w} : f32")
        cur = f"%ps{w}"
    e(f"  %mean = scalar.mulf {cur}, %invd : f32")
    e("  %sh = scalar.addf %mean, %eps : f32")
    e("  %inv = scalar.rsqrtf %sh : f32")
    for i in range(per):
        e(f"  %w{i} = view.load %wv[%i{i}] : view<{D}xf32> -> f32")
        e(f"  %n{i} = scalar.mulf %x{i}, %inv : f32")
        e(f"  %y{i} = scalar.mulf %n{i}, %w{i} : f32")
        e(f"  view.store %y{i}, %ov[%i{i}] : f32, view<{D}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_deltanet(NH=48, NKH=16, D=128):
    """One gated DeltaNet decode step, one 512-lane workgroup per value head.

    alpha = exp(softplus(a + dt) * ssm_a), beta = sigmoid(b); S = alpha S; S += beta (v - S k) k^T; o = S q.
    out = rmsnorm(o) * ssm_norm * silu(gate). k, q are L2-normalized, q also scaled by 1 / sqrt(D).
    Lane t owns state row j = t / 4 and keys 32 (t % 4) .. +32; k_norm / q_norm in LDS; the row dots end with xor shuffles 1, 2.
    The conv (dot = s1 w0 + s2 w1 + s3 w2 + x w3, silu, state shift) runs here on the raw qkv projection.
    Lanes 0..127 convolve the head's v channels and q / k channels (key head kh = h % NKH, recomputed by each of its NH / NKH value heads).
    The conv state ping-pongs between a read and a write buffer (the caller swaps them every token).
    So a sibling head's reads never see this step's writes, and each channel is written once (q / k by head h < NKH).
    The row lanes issue their state loads before the norm phase.
    """
    NT = 512
    nw = NT // 32
    SN = NH * D * D
    CV = 2 * NKH * D + NH * D
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_misc.py (deltanet) -- edit the generator.")
    e("amdgpu.target<gfx1151> @dm32 {subgroup_size = 32}")
    e("kernel.def target(@dm32) @yah_dec_deltanet() {")
    e("  %u1 = index.constant 1 : index")
    e(f"  %nh = index.constant {NH} : index")
    e(f"  %nt = index.constant {NT} : index")
    e("  kernel.launch.config workgroups(%nh, %u1, %u1) workgroup_size(%nt, %u1, %u1) : index")
    e("} launch(%conv: buffer, %cw: buffer, %csr: buffer, %csw: buffer, %state: buffer, %alpha: buffer, %beta: buffer, %ssm_a: buffer, %ssm_dt: buffer, %ssm_norm: buffer, %gate: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 4, 32, 128):
        e(f"  %c{v} = index.constant {v} : index")
    e("  %c3_ = index.constant 3 : index")
    e(f"  %cnkh = index.constant {NKH} : index")
    e("  %zf = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e("  %twenty = scalar.constant 20.0 : f32")
    e("  %eps = scalar.constant 9.9999999999999995e-07 : f32")
    e("  %invd = scalar.constant 0.0078125 : f32")
    e("  %w1 = scalar.constant 1 : i32")
    e("  %w2 = scalar.constant 2 : i32")
    e("  %w32 = scalar.constant 32 : i32")
    e("  %c_na, %cw_na, %csr_na, %csw_na, %s_na, %a_na, %b_na, %sa_na, %dt_na, %n_na, %g_na, %o_na = buffer.assume.noalias %conv, %cw, %csr, %csw, %state, %alpha, %beta, %ssm_a, %ssm_dt, %ssm_norm, %gate, %out : buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer, buffer")
    e(f"  %cwv = buffer.view %cw_na[%base] : buffer -> view<{4 * CV}xf32>")
    e(f"  %csrv = buffer.view %csr_na[%base] : buffer -> view<{4 * CV}xf32>")
    e(f"  %cswv = buffer.view %csw_na[%base] : buffer -> view<{4 * CV}xf32>")
    e(f"  %cv = buffer.view %c_na[%base] : buffer -> view<{CV}xf32>")
    e(f"  %sv = buffer.view %s_na[%base] : buffer -> view<{SN}xf32>")
    for nm in ("a", "b", "sa", "dt"):
        e(f"  %{nm}v = buffer.view %{nm}_na[%base] : buffer -> view<{NH}xf32>")
    e(f"  %nv = buffer.view %n_na[%base] : buffer -> view<{D}xf32>")
    e(f"  %gv = buffer.view %g_na[%base] : buffer -> view<{NH * D}xf32>")
    e(f"  %ov = buffer.view %o_na[%base] : buffer -> view<{NH * D}xf32>")
    NL = 2 * D + 3 * nw + D     # + conv'd v at VB
    VB = 2 * D + 3 * nw
    LV = f"view<{NL}xf32>"
    e(f"  %pb = index.constant {NL * 4} : offset")
    e("  %pool = buffer.alloca<workgroup> align(16) %pb : buffer")
    e(f"  %lv = buffer.view %pool[%base] : buffer -> {LV}")
    e("  %h = kernel.workgroup.id<x> : index")
    e("  %t = kernel.workitem.id<x> : index")
    e("  %wave = index.div %t, %c32 : index")
    e("  %ln = index.rem %t, %c32 : index")
    e("  %l0 = index.cmp eq, %ln, %c0 : index")
    e("  %kh = index.rem %h, %cnkh : index")
    e("  %j = index.div %t, %c4 : index")
    e("  %p = index.rem %t, %c4 : index")
    e("  %p32 = index.mul %p, %c32 : index")
    e(f"  %hb = index.constant {D * D} : index")
    e("  %so0 = index.mul %h, %hb : index")
    e("  %so1 = index.mul %j, %c128 : index")
    e("  %so2 = index.add %so0, %so1 : index")
    e("  %so = index.add %so2, %p32 : index")
    for c in range(8):
        e(f"  %o{c}c = index.constant {4 * c} : index")
        e(f"  %sa{c} = index.add %so, %o{c}c : index")
        e(f"  %S{c} = vector.load %sv[%sa{c}] : view<{SN}xf32> -> vector<4xf32>")
    # decay / learning rate
    e("  %dt = view.load %dtv[%h] : view<" + str(NH) + "xf32> -> f32")
    e("  %aval = view.load %sav[%h] : view<" + str(NH) + "xf32> -> f32")
    e("  %ain = view.load %av[%h] : view<" + str(NH) + "xf32> -> f32")
    e("  %bin = view.load %bv[%h] : view<" + str(NH) + "xf32> -> f32")
    e("  %biased = scalar.addf %ain, %dt : f32")
    e("  %over = scalar.cmpf ogt, %biased, %twenty : f32")
    e("  %sp = scf.if %over -> (f32) {")
    e("    scf.yield %biased : f32")
    e("  } else {")
    e("    %eb = scalar.expf<afn> %biased : f32")
    e("    %op = scalar.addf %one, %eb : f32")
    e("    %lo = scalar.logf<afn> %op : f32")
    e("    scf.yield %lo : f32")
    e("  }")
    e("  %scaled = scalar.mulf %sp, %aval : f32")
    e("  %alph = scalar.expf<afn> %scaled : f32")
    e("  %nb = scalar.negf %bin : f32")
    e("  %be = scalar.expf<afn> %nb : f32")
    e("  %bd = scalar.addf %one, %be : f32")
    e("  %bet = scalar.divf %one, %bd : f32")
    # k, q L2 norms: lanes t < 128 hold one element each
    e("  %isel = index.cmp ult, %t, %c128 : index")
    e("  %te = index.min %t, %c128 : index")
    e(f"  %tc = index.constant {D - 1} : index")
    e("  %tee = index.min %te, %tc : index")
    e("  %qb = index.mul %kh, %c128 : index")
    e("  %qi = index.add %qb, %tee : index")
    e(f"  %kb0 = index.add %cnkh, %kh : index")
    e("  %kb = index.mul %kb0, %c128 : index")
    e("  %ki = index.add %kb, %tee : index")
    e(f"  %vb0 = index.constant {2 * NKH * D} : index")
    e("  %vh0 = index.mul %h, %c128 : index")
    e("  %vi1 = index.add %vb0, %vh0 : index")
    e("  %vci = index.add %vi1, %tee : index")
    e("  %ownqk = index.cmp ult, %h, %cnkh : index")
    for nm, ch, own in (("qx", "%qi", "%ownqk"), ("kx", "%ki", "%ownqk"), ("vx", "%vci", None)):
        e(f"  %{nm}c4 = index.mul {ch}, %c4 : index")
        ws, ss = [], []
        for k in range(4):
            e(f"  %{nm}o{k} = index.add %{nm}c4, %c{k} : index") if k in (0, 1, 2, 4) else \
                e(f"  %{nm}o{k} = index.add %{nm}c4, %c3_ : index")
            e(f"  %{nm}w{k} = view.load %cwv[%{nm}o{k}] : view<{4 * CV}xf32> -> f32")
            ws.append(f"%{nm}w{k}")
            if k:
                e(f"  %{nm}s{k} = view.load %csrv[%{nm}o{k}] : view<{4 * CV}xf32> -> f32")
                ss.append(f"%{nm}s{k}")
        e(f"  %{nm}in = view.load %cv[{ch}] : view<{CV}xf32> -> f32")
        e(f"  %{nm}t1 = scalar.mulf {ss[0]}, {ws[0]} : f32")
        e(f"  %{nm}t2 = scalar.mulf {ss[1]}, {ws[1]} : f32")
        e(f"  %{nm}t3 = scalar.mulf {ss[2]}, {ws[2]} : f32")
        e(f"  %{nm}t4 = scalar.mulf %{nm}in, {ws[3]} : f32")
        e(f"  %{nm}a1 = scalar.addf %{nm}t1, %{nm}t2 : f32")
        e(f"  %{nm}a2 = scalar.addf %{nm}a1, %{nm}t3 : f32")
        e(f"  %{nm}d = scalar.addf %{nm}a2, %{nm}t4 : f32")
        e(f"  %{nm}ng = scalar.negf %{nm}d : f32")
        e(f"  %{nm}e = scalar.expf<afn> %{nm}ng : f32")
        e(f"  %{nm}den = scalar.addf %one, %{nm}e : f32")
        e(f"  %{nm}sg = scalar.divf %one, %{nm}den : f32")
        e(f"  %{nm} = scalar.mulf %{nm}d, %{nm}sg : f32")
        cond = "%isel" if own is None else f"%{nm}wr"
        if own is not None:
            e(f"  %{nm}wr0 = index.cmp ult, %t, %c128 : index")
            e(f"  %{nm}wr = scf.if %{nm}wr0 -> (i1) {{")
            e(f"    scf.yield {own} : i1")
            e("  } else {")
            e("    %fls = index.cmp ult, %c1, %c0 : index")
            e("    scf.yield %fls : i1")
            e("  }")
        e(f"  scf.if {cond} {{")
        for k, v in enumerate(ss + [f"%{nm}in"]):
            e(f"    view.store {v}, %cswv[%{nm}o{k}] : f32, view<{4 * CV}xf32>")
        e("  }")
    e("  %vlb = index.constant " + str(VB) + " : index")
    e("  %vla = index.add %vlb, %tee : index")
    e("  scf.if %isel {")
    e(f"    view.store %vx, %lv[%vla] : f32, view<{NL}xf32>")
    e("  }")
    e("  %qq0 = scalar.mulf %qx, %qx : f32")
    e("  %kk0 = scalar.mulf %kx, %kx : f32")
    e("  %qq = scf.if %isel -> (f32) {")
    e("    scf.yield %qq0 : f32")
    e("  } else {")
    e("    scf.yield %zf : f32")
    e("  }")
    e("  %kk = scf.if %isel -> (f32) {")
    e("    scf.yield %kk0 : f32")
    e("  } else {")
    e("    scf.yield %zf : f32")
    e("  }")
    e("  %wq = kernel.subgroup.reduce<addf> %qq : f32")
    e("  %wk = kernel.subgroup.reduce<addf> %kk : f32")
    e(f"  %rqb = index.constant {2 * D} : index")
    e(f"  %rkb = index.constant {2 * D + nw} : index")
    e("  %rq = index.add %rqb, %wave : index")
    e("  %rk = index.add %rkb, %wave : index")
    e("  scf.if %l0 {")
    e(f"    view.store %wq, %lv[%rq] : f32, {LV}")
    e(f"    view.store %wk, %lv[%rk] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    sq, sk = "%zf", "%zf"
    for w in range(nw):
        e(f"  %rq{w}i = index.constant {2 * D + w} : index")
        e(f"  %rk{w}i = index.constant {2 * D + nw + w} : index")
        e(f"  %rq{w} = view.load %lv[%rq{w}i] : {LV} -> f32")
        e(f"  %rk{w} = view.load %lv[%rk{w}i] : {LV} -> f32")
        e(f"  %sq{w} = scalar.addf {sq}, %rq{w} : f32")
        e(f"  %sk{w} = scalar.addf {sk}, %rk{w} : f32")
        sq, sk = f"%sq{w}", f"%sk{w}"
    e(f"  %keps = scalar.addf {sk}, %eps : f32")
    e("  %kroot = scalar.sqrtf %keps : f32")
    e("  %invk = scalar.divf %one, %kroot : f32")
    e(f"  %qeps = scalar.addf {sq}, %eps : f32")
    e("  %qroot = scalar.sqrtf %qeps : f32")
    e("  %invq = scalar.divf %one, %qroot : f32")
    e(f"  %invdim = scalar.constant {1.0 / (D ** 0.5)!r} : f32")
    e("  %qscale = scalar.mulf %invdim, %invq : f32")
    e("  %kn = scalar.mulf %kx, %invk : f32")
    e("  %qn = scalar.mulf %qx, %qscale : f32")
    e("  scf.if %isel {")
    e(f"    %qsl = index.add %tee, %c128 : index")
    e(f"    view.store %kn, %lv[%tee] : f32, {LV}")
    e(f"    view.store %qn, %lv[%qsl] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # rows: j = t / 4, keys 32 p .. 32 p + 32
    e("  %as = vector.splat %alph : vector<4xf32>")
    srow, kn4, qn4 = [], [], []
    u = "%zf"
    for c in range(8):
        e(f"  %ka{c} = index.add %p32, %o{c}c : index")
        e(f"  %K{c} = vector.load %lv[%ka{c}] : {LV} -> vector<4xf32>")
        e(f"  %Sa{c} = vector.mulf %S{c}, %as : vector<4xf32>")
        e(f"  %uv{c} = vector.mulf %Sa{c}, %K{c} : vector<4xf32>")
        e(f"  %ur{c} = vector.reduce<addf> %uv{c}, {u} : vector<4xf32>, f32")
        u = f"%ur{c}"
    def xred(v, tag):
        cur = v
        for m in (1, 2):
            e(f"  %{tag}{m}i = scalar.bitcast {cur} : f32 to i32")
            e(f"  %{tag}{m}x, %{tag}{m}v = kernel.subgroup.shuffle<xor> %{tag}{m}i, %w{m}, %w32 : i32, i32, i32")
            e(f"  %{tag}{m}f = scalar.bitcast %{tag}{m}x : i32 to f32")
            e(f"  %{tag}{m} = scalar.addf {cur}, %{tag}{m}f : f32")
            cur = f"%{tag}{m}"
        return cur
    uj = xred(u, "ux")
    e("  %vh = index.mul %h, %c128 : index")
    e(f"  %vjl0 = index.constant {VB} : index")
    e("  %vjl = index.add %vjl0, %j : index")
    e(f"  %vj = view.load %lv[%vjl] : {LV} -> f32")
    e(f"  %dv = scalar.subf %vj, {uj} : f32")
    e("  %dj = scalar.mulf %dv, %bet : f32")
    e("  %ds = vector.splat %dj : vector<4xf32>")
    o = "%zf"
    for c in range(8):
        e(f"  %Sn{c} = vector.fmaf %ds, %K{c}, %Sa{c} : vector<4xf32>")
        e(f"  vector.store %Sn{c}, %sv[%sa{c}] : vector<4xf32>, view<{SN}xf32>")
        e(f"  %qa{c}0 = index.constant {D + 4 * c} : index")
        e(f"  %qa{c} = index.add %qa{c}0, %p32 : index")
        e(f"  %Q{c} = vector.load %lv[%qa{c}] : {LV} -> vector<4xf32>")
        e(f"  %ov{c} = vector.mulf %Sn{c}, %Q{c} : vector<4xf32>")
        e(f"  %or{c} = vector.reduce<addf> %ov{c}, {o} : vector<4xf32>, f32")
        o = f"%or{c}"
    oj = xred(o, "ox")
    # RMSNorm over the 128 outputs (lanes p == 0 contribute)
    e("  %p0 = index.cmp eq, %p, %c0 : index")
    e(f"  %o2a = scalar.mulf {oj}, {oj} : f32")
    e("  %o2 = scf.if %p0 -> (f32) {")
    e("    scf.yield %o2a : f32")
    e("  } else {")
    e("    scf.yield %zf : f32")
    e("  }")
    e("  %wo = kernel.subgroup.reduce<addf> %o2 : f32")
    e(f"  %rob = index.constant {2 * D + 2 * nw} : index")
    e("  %ro = index.add %rob, %wave : index")
    e("  scf.if %l0 {")
    e(f"    view.store %wo, %lv[%ro] : f32, {LV}")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    so_ = "%zf"
    for w in range(nw):
        e(f"  %ro{w}i = index.constant {2 * D + 2 * nw + w} : index")
        e(f"  %ro{w} = view.load %lv[%ro{w}i] : {LV} -> f32")
        e(f"  %so{w}s = scalar.addf {so_}, %ro{w} : f32")
        so_ = f"%so{w}s"
    e(f"  %ms = scalar.mulf {so_}, %invd : f32")
    e("  %mse = scalar.addf %ms, %eps : f32")
    e("  %rr = scalar.sqrtf %mse : f32")
    e("  %rms = scalar.divf %one, %rr : f32")
    e("  scf.if %p0 {")
    e(f"    %nj = view.load %nv[%j] : view<{D}xf32> -> f32")
    e("    %gi = index.add %vh, %j : index")
    e(f"    %g = view.load %gv[%gi] : view<{NH * D}xf32> -> f32")
    e("    %ng = scalar.negf %g : f32")
    e("    %eg = scalar.expf<afn> %ng : f32")
    e("    %dg = scalar.addf %one, %eg : f32")
    e("    %sg = scalar.divf %one, %dg : f32")
    e("    %silu = scalar.mulf %g, %sg : f32")
    e(f"    %y0 = scalar.mulf {oj}, %rms : f32")
    e("    %y1 = scalar.mulf %y0, %nj : f32")
    e("    %y = scalar.mulf %y1, %silu : f32")
    e(f"    view.store %y, %ov[%gi] : f32, view<{NH * D}xf32>")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


IQ4_KVALUES = [-127, -104, -83, -65, -49, -35, -22, -10, 1, 13, 25, 38, 53, 69, 89, 113]


def gen_embed_iq4xs(D=5120, V=248320, rows=1):
    """hidden[k] = dequant(token_embd row tok)[k], tok = tokens[0]; the caller binds the token stream at the step's offset.
    rows > 1 (the prefill, yah_embed): row r of hidden from tokens[r], one workgroup per row.

    IQ4_XS per 256-block: d f16, scales_h u16, scales_l[4], qs[128]; value = (d * (sc - 32)) * kvalues[nibble].
    One 320-lane workgroup per row; lane = 16-element sub-block.
    """
    NS = D // 16
    RB = D // 256 * 136
    L = []
    e = L.append
    e("// GENERATED by tools/gen_decode_misc.py (embed_iq4xs) -- edit the generator.")
    e("amdgpu.target<gfx1151> @dm32 {subgroup_size = 32}")
    e(f"kernel.def target(@dm32) @{'yah_dec_embed' if rows == 1 else 'yah_embed'}() {{")
    e("  %u1 = index.constant 1 : index")
    e(f"  %nt = index.constant {NS} : index")
    if rows > 1:
        e(f"  %nr = index.constant {rows} : index")
    e(f"  kernel.launch.config workgroups({'%u1' if rows == 1 else '%nr'}, %u1, %u1) workgroup_size(%nt, %u1, %u1) : index")
    e("} launch(%w: buffer, %tok: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    for v in (0, 1, 2, 3, 4, 8, 16, 136):
        e(f"  %c{v} = index.constant {v} : index")
    e(f"  %crb = index.constant {RB} : index")
    e(f"  %cvm = index.constant {V - 1} : index")
    e(f"  %wlim = index.constant {V * RB - 16} : index")
    e("  %w_na, %t_na, %o_na = buffer.assume.noalias %w, %tok, %out : buffer, buffer, buffer")
    e(f"  %wv = buffer.view %w_na[%base] : buffer -> view<{V * RB}xi8>")
    e(f"  %wh = buffer.view %w_na[%base] : buffer -> view<{V * RB // 2}xf16>")
    e(f"  %tv = buffer.view %t_na[%base] : buffer -> view<{rows}xi32>")
    e(f"  %ov = buffer.view %o_na[%base] : buffer -> view<{rows * D}xf32>")
    for i, v in enumerate(IQ4_KVALUES):
        e(f"  %kv{i} = scalar.constant {v} : i8")
    e("  %kvt = vector.from_elements " + ", ".join(f"%kv{i}" for i in range(16)) + " : vector<16xi8>")
    e("  %m15 = scalar.constant 15 : i8")
    e("  %m15v = vector.splat %m15 : vector<16xi8>")
    e("  %w15 = scalar.constant 252645135 : i32")
    e("  %w15v = vector.splat %w15 : vector<4xi32>")
    e("  %sb = kernel.workitem.id<x> : index")
    if rows > 1:
        e("  %row = kernel.workgroup.id<x> : index")
    e(f"  %ti = view.load %tv[{'%c0' if rows == 1 else '%row'}] : view<{rows}xi32> -> i32")
    e("  %t0 = index.cast %ti : i32 to index")
    e("  %tz = index.max %t0, %c0 : index")
    e("  %t = index.min %tz, %cvm : index")
    e("  %rowb = index.mul %t, %crb : index")
    e("  %blk = index.div %sb, %c16 : index")
    e("  %bo0 = index.mul %blk, %c136 : index")
    e("  %bo = index.add %rowb, %bo0 : index")
    e("  %l2 = index.div %sb, %c2 : index")
    e("  %s32 = index.rem %l2, %c8 : index")
    e("  %hlf = index.rem %sb, %c2 : index")
    e("  %s32i = index.cast %s32 : index to i32")
    e("  %hlfi = index.cast %hlf : index to i32")
    # nibbles: qs[s32 * 16 .. + 16] >> 4 * hlf
    e("  %qo0 = index.mul %s32, %c16 : index")
    e("  %qo1 = index.add %bo, %qo0 : index")
    e("  %qo2 = index.add %qo1, %c8 : index")
    e("  %qo = index.min %qo2, %wlim : index")
    e(f"  %qr = vector.load %wv[%qo] : view<{V * RB}xi8> -> vector<16xi8>")
    e("  %qw = vector.bitcast %qr : vector<16xi8> to vector<4xi32>")
    e("  %shi = scalar.shli %hlfi, %c2w : i32".replace("%c2w", "%w2"))
    L.insert(len(L) - 1, "  %w2 = scalar.constant 2 : i32")
    e("  %shv = vector.splat %shi : vector<4xi32>")
    e("  %qs = vector.shrui %qw, %shv : vector<4xi32>")
    e("  %qn = vector.andi %qs, %w15v : vector<4xi32>")
    e("  %nb0 = vector.bitcast %qn : vector<4xi32> to vector<16xi8>")
    e("  %nb = vector.andi %nb0, %m15v : vector<16xi8>")
    e("  %cv = vector.table.lookup %kvt[%nb] : vector<16xi8>, vector<16xi8> -> vector<16xi8>")
    e("  %cf = vector.sitofp %cv : vector<16xi8> to vector<16xf32>")
    # scale: d * (((scales_l[s32 / 2] >> 4 (s32 % 2)) & 15) | (((scales_h >> 2 s32) & 3) << 4)) - 32)
    e("  %sl0 = index.div %s32, %c2 : index")
    e("  %sla0 = index.add %bo, %sl0 : index")
    e("  %sla1 = index.add %sla0, %c4 : index")
    e(f"  %sla = index.min %sla1, %wlim : index")
    e(f"  %slb8 = view.load %wv[%sla] : view<{V * RB}xi8> -> i8")
    e("  %slb = scalar.extui %slb8 : i8 to i32")
    e("  %h0a0 = index.add %bo, %c2 : index")
    e("  %h0a = index.min %h0a0, %wlim : index")
    e("  %h1a0 = index.add %bo, %c3 : index")
    e("  %h1a = index.min %h1a0, %wlim : index")
    e(f"  %h08 = view.load %wv[%h0a] : view<{V * RB}xi8> -> i8")
    e(f"  %h18 = view.load %wv[%h1a] : view<{V * RB}xi8> -> i8")
    e("  %h0 = scalar.extui %h08 : i8 to i32")
    e("  %h1 = scalar.extui %h18 : i8 to i32")
    e("  %w8 = scalar.constant 8 : i32")
    e("  %w1 = scalar.constant 1 : i32")
    e("  %w4 = scalar.constant 4 : i32")
    e("  %w3 = scalar.constant 3 : i32")
    e("  %w15s = scalar.constant 15 : i32")
    e("  %w32 = scalar.constant 32 : i32")
    e("  %h1s = scalar.shli %h1, %w8 : i32")
    e("  %shw = scalar.ori %h0, %h1s : i32")
    e("  %sl1 = scalar.andi %s32i, %w1 : i32")
    e("  %sls = scalar.shli %sl1, %w2 : i32")
    e("  %lw = scalar.shrui %slb, %sls : i32")
    e("  %l4 = scalar.andi %lw, %w15s : i32")
    e("  %shs = scalar.shli %s32i, %w1 : i32")
    e("  %hw = scalar.shrui %shw, %shs : i32")
    e("  %h2 = scalar.andi %hw, %w3 : i32")
    e("  %h2s = scalar.shli %h2, %w4 : i32")
    e("  %s6 = scalar.ori %l4, %h2s : i32")
    e("  %sc = scalar.subi %s6, %w32 : i32")
    e("  %scf = scalar.sitofp %sc : i32 to f32")
    e("  %dh0 = index.div %bo, %c2 : index")
    e(f"  %dhl = index.constant {V * RB // 2 - 1} : index")
    e("  %dh = index.min %dh0, %dhl : index")
    e(f"  %dx = view.load %wh[%dh] : view<{V * RB // 2}xf16> -> f16")
    e("  %d = scalar.extf %dx : f16 to f32")
    e("  %dl = scalar.mulf %d, %scf : f32")
    e("  %dlv = vector.splat %dl : vector<16xf32>")
    e("  %val = vector.mulf %dlv, %cf : vector<16xf32>")
    # element index: block * 256 + s32 * 32 + hlf * 16 (= sb * 16)
    e("  %oi = index.mul %sb, %c16 : index")
    if rows > 1:
        e(f"  %cd = index.constant {D} : index")
        e("  %ro = index.mul %row, %cd : index")
        e("  %oi1 = index.add %ro, %oi : index")
    e(f"  vector.store %val, %ov[{'%oi' if rows == 1 else '%oi1'}] : vector<16xf32>, view<{rows * D}xf32>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    which, outp = sys.argv[1], sys.argv[2]
    open(outp, "w").write({"rmsnorm": gen_rmsnorm, "deltanet": gen_deltanet, "embed": gen_embed_iq4xs}[which]())
    print(outp)
