#!/usr/bin/env python3
"""Generate yah_half_norm, the fully unrolled RMS norm with f16 output, for one row width.

usage: gen_half_norm.py [out.loom] [dim=5120]

Grid (rows) x 32: one wave32 per row; lane l owns elements l, l+32, ...
Bindings: x (f32 [rows][dim]), weight (f32 [dim]), out (f16 [rows][dim]); residual and sum_out are not read.
Per lane the sum of squares is ((0 + v0*v0) + v1*v1) + ... (mulf then addf, not fma), then a subgroup reduction.
The output is f16((v * inv) * w).

Fully unrolled: each lane issues all dim/32 loads up front and keeps the values in registers,
so the second pass reads mostly the weight (a loop form makes ~160 dependent round trips per lane).
"""
import sys


def gen(dim=5120, wpr=1, tiled=False, resadd=False, keep=None, wlds=False):
    """tiled: the output fragment-major for the afrag GEMMs (gen_gemm_tile Tile.atiled): 16 x 16 tiles (row / 16,
    col / 16) of 256 halves, column fastest inside. Lane l's column l + 32k is tile column 2k + l / 16, offset l % 16.
    tiled="both": the row-major output to out and the fragment-major one to a sixth binding out_t.
    resadd: the residual add of the GEMM before it moves here: v = x + residual (the GEMM's f32 output, the same f32
    add the kres epilogue did), v is stored to sum_out (the new residual stream; x and residual are only read) and
    normalized as x was. Rows past `keep` reload x and residual and add again (no read of the stored v).
    wlds: the workgroup stages the weight vector in LDS once (16-byte loads); the output pass reads it from LDS
    instead of every row walking it through L2 two loads at a time."""
    both = tiled == "both"
    assert dim % 32 == 0
    n = dim // 32
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_half_norm.py (dim={dim}) -- edit the generator.")
    e("// Fully unrolled fp16 RMS norm (fused=0); see the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_half_norm.rows : %value: index where [range(%value, 1, 65536)]")
    e(f"config.decl @yah_half_norm.dim : %value: index where [range(%value, {dim}, {dim})]")
    e("config.def @yah_half_norm.eps = 0.0 : f32")
    e("config.def @yah_half_norm.fused = 0 : index")
    e("")
    e("kernel.def target(@yah_wave32) @yah_half_norm() {")
    e("  %unit = index.constant 1 : index")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %c32 = index.constant 32 : index")
    if wpr == 1:
        e("  kernel.launch.config workgroups(%rows, %unit, %unit) workgroup_size(%c32, %unit, %unit) : index")
    else:
        # wpr rows per workgroup, one wave each; the driver launches rows / wpr workgroups
        e(f"  %cwpr = index.constant {wpr} : index")
        e(f"  %cwgs = index.constant {32 * wpr} : index")
        e("  %wgs = index.div %rows, %cwpr : index")
        e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%cwgs, %unit, %unit) : index")
    e("} launch(%x: buffer, %residual: buffer, %weight: buffer, %sum_out: buffer, %out: buffer"
      + (", %out_t: buffer" if both else "") + ") {")
    e("  %base = index.constant 0 : offset")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %dim = index.constant {dim} : index")
    e("  %eps = config.get @yah_half_norm.eps : f32")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %total_elems = index.mul %rows, %dim : index")
    if resadd:
        assert not both
        e("  %x_na, %res_na, %weight_na, %nres_na, %out_na = buffer.assume.noalias %x, %residual, %weight, %sum_out, %out : buffer, buffer, buffer, buffer, buffer")
    elif both:
        e("  %x_na, %weight_na, %out_na, %out_t_na = buffer.assume.noalias %x, %weight, %out, %out_t : buffer, buffer, buffer, buffer")
    else:
        e("  %x_na, %weight_na, %out_na = buffer.assume.noalias %x, %weight, %out : buffer, buffer, buffer")
    e("  %x_view = buffer.view %x_na[%base] : buffer -> view<[%total_elems]xf32>")
    e("  %weight_view = buffer.view %weight_na[%base] : buffer -> view<[%dim]xf32>")
    if resadd:
        e("  %res_view = buffer.view %res_na[%base] : buffer -> view<[%total_elems]xf32>")
        e("  %nres_view = buffer.view %nres_na[%base] : buffer -> view<[%total_elems]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%total_elems]xf16>")
    if both:
        e("  %out_t_view = buffer.view %out_t_na[%base] : buffer -> view<[%total_elems]xf16>")
    if wpr == 1:
        e("  %row = kernel.workgroup.id<x> : index")
        e("  %lane = kernel.workitem.id<x> : index")
    else:
        e("  %wg = kernel.workgroup.id<x> : index")
        e("  %tid = kernel.workitem.id<x> : index")
        e("  %c32w = index.constant 32 : index")
        e(f"  %cwpr2 = index.constant {wpr} : index")
        e("  %wave = index.div %tid, %c32w : index")
        e("  %lane = index.rem %tid, %c32w : index")
        e("  %wgrow = index.mul %wg, %cwpr2 : index")
        e("  %row = index.add %wgrow, %wave : index")
    e("  %row_base = index.mul %row, %dim : index")
    e("  %lane_base = index.add %row_base, %lane : index")
    if tiled:
        e("  %c16t = index.constant 16 : index")
        e("  %c256t = index.constant 256 : index")
        e(f"  %ctiles = index.constant {dim // 16} : index")
        e("  %trow = index.div %row, %c16t : index")
        e("  %trr = index.rem %row, %c16t : index")
        e("  %tlh = index.div %lane, %c16t : index")
        e("  %tll = index.rem %lane, %c16t : index")
        e("  %tt0 = index.mul %trow, %ctiles : index")
        e("  %tt1 = index.add %tt0, %tlh : index")
        e("  %tt2 = index.mul %tt1, %c256t : index")
        e("  %tt3 = index.mul %trr, %c16t : index")
        e("  %tt4 = index.add %tt2, %tt3 : index")
        e("  %tbase = index.add %tt4, %tll : index")
    if wlds:
        assert wpr > 1 and dim % (4 * 32 * wpr) == 0
        e(f"  %wl_bytes = index.constant {dim * 4} : offset")
        e("  %wl_buf = buffer.alloca<workgroup> align(16) %wl_bytes : buffer")
        e(f"  %wl_view = buffer.view %wl_buf[%base] : buffer -> view<{dim}xf32>")
        e("  %wl_c4 = index.constant 4 : index")
        e("  %wl_t4 = index.mul %tid, %wl_c4 : index")
        for c in range(dim // (4 * 32 * wpr)):
            e(f"  %wl_o{c} = index.constant {c * 4 * 32 * wpr} : index")
            e(f"  %wl_i{c} = index.add %wl_t4, %wl_o{c} : index")
            e(f"  %wl_v{c} = vector.load %weight_view[%wl_i{c}] : view<[%dim]xf32> -> vector<4xf32>")
            e(f"  vector.store %wl_v{c}, %wl_view[%wl_i{c}] : vector<4xf32>, view<{dim}xf32>")
        e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    for k in range(n):
        e(f"  %o{k} = index.constant {32 * k} : index")
        e(f"  %a{k} = index.add %lane_base, %o{k} : index")
        if resadd:
            e(f"  %xa{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            e(f"  %ga{k} = view.load %res_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            e(f"  %x{k} = scalar.addf %xa{k}, %ga{k} : f32")
            e(f"  view.store %x{k}, %nres_view[%a{k}] : f32, view<[%total_elems]xf32>")
        else:
            e(f"  %x{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
    s = "%zero"
    for k in range(n):
        e(f"  %q{k} = scalar.mulf %x{k}, %x{k} : f32")
        e(f"  %s{k} = scalar.addf {s}, %q{k} : f32")
        s = f"%s{k}"
    e(f"  %sum_sq = kernel.subgroup.reduce<addf> {s} : f32")
    e(f"  %dim_i = scalar.constant {dim} : i32")
    e("  %dim_f = scalar.sitofp %dim_i : i32 to f32")
    e("  %mean = scalar.divf %sum_sq, %dim_f : f32")
    e("  %shifted = scalar.addf %mean, %eps : f32")
    e("  %root = scalar.sqrtf %shifted : f32")
    e("  %inv = scalar.divf %one, %root : f32")
    # Hold the first `keep` row values across the reduction and reload the rest for the output pass.
    # Fewer VGPRs give one more wave per SIMD: 56 is 8% faster than holding all 160 at dim 5120.
    if keep is None:
        keep = 56 if dim == 5120 else n
    for k in range(n):
        e(f"  %wi{k} = index.add %lane, %o{k} : index")
        if wlds:
            e(f"  %w{k} = view.load %wl_view[%wi{k}] : view<{dim}xf32> -> f32")
        else:
            e(f"  %w{k} = view.load %weight_view[%wi{k}] : view<[%dim]xf32> -> f32")
        xk = f"%x{k}"
        if k >= keep:
            if resadd:
                e(f"  %xra{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
                e(f"  %gra{k} = view.load %res_view[%a{k}] : view<[%total_elems]xf32> -> f32")
                e(f"  %xr{k} = scalar.addf %xra{k}, %gra{k} : f32")
            else:
                e(f"  %xr{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
            xk = f"%xr{k}"
        e(f"  %nm{k} = scalar.mulf {xk}, %inv : f32")
        e(f"  %wt{k} = scalar.mulf %nm{k}, %w{k} : f32")
        e(f"  %h{k} = scalar.fptrunc %wt{k} : f32 to f16")
        if tiled:
            e(f"  %to{k} = index.constant {512 * k} : index")
            e(f"  %ta{k} = index.add %tbase, %to{k} : index")
            if both:
                e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
            e(f"  view.store %h{k}, %{'out_t_view' if both else 'out_view'}[%ta{k}] : f16, view<[%total_elems]xf16>")
        else:
            e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def gen_split(dim=5120, wpr=4, split=2, tiled=False, wlds=True, bfp=None):
    """The same norm with each row split over `split` waves (part p holds k in [p n/S, (p+1) n/S), all in registers).
    bfp = (tokens, ks, passes): also the NPU's BFP16 activation stream of the output (gen_bfp16_encode "act", binding ab after
    the outputs), encoded from the f16 values; see split_bfp_out.
    Lane l's sum of squares stays one chain in k order: part p continues it from part p-1's partial (LDS, barrier
    between steps), so the bits are those of gen(). Branch-free: at step p every wave runs its chain from its
    predecessor's partial, only part p's result is used. Fewer values per wave: more waves and loads in flight."""
    both = tiled == "both"
    assert dim % 32 == 0 and (dim // 32) % split == 0
    n = dim // 32
    m = n // split
    NTH = 32 * wpr * split
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_half_norm.py gen_split (dim={dim}, split={split}) -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e("config.decl @yah_half_norm.rows : %value: index where [range(%value, 1, 65536)]")
    e(f"config.decl @yah_half_norm.dim : %value: index where [range(%value, {dim}, {dim})]")
    e("config.def @yah_half_norm.eps = 0.0 : f32")
    e("config.def @yah_half_norm.fused = 0 : index")
    e("")
    e("kernel.def target(@yah_wave32) @yah_half_norm() {")
    e("  %unit = index.constant 1 : index")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e(f"  %cwpr = index.constant {wpr} : index")
    e(f"  %cwgs = index.constant {NTH} : index")
    e("  %wgs = index.div %rows, %cwpr : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%cwgs, %unit, %unit) : index")
    e("} launch(%x: buffer, %residual: buffer, %weight: buffer, %sum_out: buffer, %out: buffer"
      + (", %out_t: buffer" if both else "") + (", %ab: buffer" if bfp else "") + ") {")
    e("  %base = index.constant 0 : offset")
    e("  %zero = scalar.constant 0.0 : f32")
    e("  %one = scalar.constant 1.0 : f32")
    e(f"  %dim = index.constant {dim} : index")
    e("  %eps = config.get @yah_half_norm.eps : f32")
    e("  %rows = config.get @yah_half_norm.rows : index")
    e("  %total_elems = index.mul %rows, %dim : index")
    if both:
        e("  %x_na, %weight_na, %out_na, %out_t_na = buffer.assume.noalias %x, %weight, %out, %out_t : buffer, buffer, buffer, buffer")
    else:
        e("  %x_na, %weight_na, %out_na = buffer.assume.noalias %x, %weight, %out : buffer, buffer, buffer")
    e("  %x_view = buffer.view %x_na[%base] : buffer -> view<[%total_elems]xf32>")
    e("  %weight_view = buffer.view %weight_na[%base] : buffer -> view<[%dim]xf32>")
    e("  %out_view = buffer.view %out_na[%base] : buffer -> view<[%total_elems]xf16>")
    if both:
        e("  %out_t_view = buffer.view %out_t_na[%base] : buffer -> view<[%total_elems]xf16>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e("  %c32w = index.constant 32 : index")
    e(f"  %csplit = index.constant {split} : index")
    e(f"  %cm32 = index.constant {32 * m} : index")
    e("  %wave = index.div %tid, %c32w : index")
    e("  %lane = index.rem %tid, %c32w : index")
    e("  %rwg = index.div %wave, %csplit : index")
    e("  %part = index.rem %wave, %csplit : index")
    e(f"  %cwprb = index.constant {wpr} : index")
    e("  %wgrow = index.mul %wg, %cwprb : index")
    e("  %row = index.add %wgrow, %rwg : index")
    e("  %row_base = index.mul %row, %dim : index")
    e("  %pk0 = index.mul %part, %cm32 : index")          # element offset of the part: 32 * m * part
    e("  %lane_base0 = index.add %row_base, %lane : index")
    e("  %lane_base = index.add %lane_base0, %pk0 : index")
    # LDS: chain partials [wave][lane], inv [wave], weights
    e(f"  %pl_bytes = index.constant {NTH * 4} : offset")
    e("  %pl_buf = buffer.alloca<workgroup> align(16) %pl_bytes : buffer")
    e(f"  %pl_view = buffer.view %pl_buf[%base] : buffer -> view<{NTH}xf32>")
    e(f"  %iv_bytes = index.constant {wpr * split * 4} : offset")
    e("  %iv_buf = buffer.alloca<workgroup> align(16) %iv_bytes : buffer")
    e(f"  %iv_view = buffer.view %iv_buf[%base] : buffer -> view<{wpr * split}xf32>")
    if wlds:
        assert dim % (4 * NTH) == 0
        e(f"  %wl_bytes = index.constant {dim * 4} : offset")
        e("  %wl_buf = buffer.alloca<workgroup> align(16) %wl_bytes : buffer")
        e(f"  %wl_view = buffer.view %wl_buf[%base] : buffer -> view<{dim}xf32>")
        e("  %wl_c4 = index.constant 4 : index")
        e("  %wl_t4 = index.mul %tid, %wl_c4 : index")
        for c in range(dim // (4 * NTH)):
            e(f"  %wl_o{c} = index.constant {c * 4 * NTH} : index")
            e(f"  %wl_i{c} = index.add %wl_t4, %wl_o{c} : index")
            e(f"  %wl_v{c} = vector.load %weight_view[%wl_i{c}] : view<[%dim]xf32> -> vector<4xf32>")
            e(f"  vector.store %wl_v{c}, %wl_view[%wl_i{c}] : vector<4xf32>, view<{dim}xf32>")
    for k in range(m):
        e(f"  %o{k} = index.constant {32 * k} : index")
        e(f"  %a{k} = index.add %lane_base, %o{k} : index")
        e(f"  %x{k} = view.load %x_view[%a{k}] : view<[%total_elems]xf32> -> f32")
    for k in range(m):
        e(f"  %q{k} = scalar.mulf %x{k}, %x{k} : f32")
    # step 0: every wave chains from 0 (part 0's result is the real one)
    e("  %pwave = index.sub %wave, %c32w : index")  # placeholder, replaced below
    L.pop()
    e("  %pidx0 = index.mul %wave, %c32w : index")
    e("  %pidx = index.add %pidx0, %lane : index")     # own partial slot
    e("  %one_i = index.constant 1 : index")
    e("  %prev0 = index.max %wave, %one_i : index")
    e("  %prev1 = index.sub %prev0, %one_i : index")      # the previous wave of the row (part p-1) for p > 0
    e("  %prevs0 = index.mul %prev1, %c32w : index")
    e("  %prevs = index.add %prevs0, %lane : index")
    e("  %is0 = index.cmp eq, %part, %c0i : index")
    start = "%zero"
    for p in range(split):
        if p:
            e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
            e(f"  %sin{p}a = view.load %pl_view[%prevs] : view<{NTH}xf32> -> f32")
            e(f"  %sin{p} = scf.select %is0, %zero, %sin{p}a : f32")
            start = f"%sin{p}"
        prev = start
        for k in range(m):
            e(f"  %s{p}_{k} = scalar.addf {prev}, %q{k} : f32")
            prev = f"%s{p}_{k}"
        if p < split - 1:
            # only part p's chain is final at this step; store it where part p+1 reads it
            e(f"  %isp{p} = index.cmp eq, %part, %c{p}i : index")
            e(f"  scf.if %isp{p} {{")
            e(f"    view.store {prev}, %pl_view[%pidx] : f32, view<{NTH}xf32>")
            e("  }")
    e(f"  %sum_sq = kernel.subgroup.reduce<addf> {prev} : f32")
    e(f"  %dim_i = scalar.constant {dim} : i32")
    e("  %dim_f = scalar.sitofp %dim_i : i32 to f32")
    e("  %mean = scalar.divf %sum_sq, %dim_f : f32")
    e("  %shifted = scalar.addf %mean, %eps : f32")
    e("  %root = scalar.sqrtf %shifted : f32")
    e("  %inv0 = scalar.divf %one, %root : f32")
    # the last part's inv is the real one: broadcast through LDS
    e(f"  %lastp = index.constant {split - 1} : index")
    e("  %islast = index.cmp eq, %part, %lastp : index")
    e("  %islane0 = index.cmp eq, %lane, %c0i : index")
    e("  %ivw = index.and %islast, %islane0 : i1")
    L.pop()
    e("  scf.if %islast {")
    e("    view.store %inv0, %iv_view[%wave] : f32, view<" + str(wpr * split) + "xf32>")
    e("  }")
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    e("  %ivr0 = index.mul %rwg, %csplit : index")
    e("  %ivr = index.add %ivr0, %lastp : index")
    e(f"  %inv = view.load %iv_view[%ivr] : view<{wpr * split}xf32> -> f32")
    if bfp:
        split_bfp_out(e, dim, wpr, split, tiled, wlds, bfp)
        return split_finish(L, split)
    if tiled:
        e("  %c16t = index.constant 16 : index")
        e("  %c256t = index.constant 256 : index")
        e(f"  %ctiles = index.constant {dim // 16} : index")
        e("  %trow = index.div %row, %c16t : index")
        e("  %trr = index.rem %row, %c16t : index")
        e("  %tlh = index.div %lane, %c16t : index")
        e("  %tll = index.rem %lane, %c16t : index")
        e("  %tt0 = index.mul %trow, %ctiles : index")
        e("  %tt1 = index.add %tt0, %tlh : index")
        e("  %tt2 = index.mul %tt1, %c256t : index")
        e("  %tt3 = index.mul %trr, %c16t : index")
        e("  %tt4 = index.add %tt2, %tt3 : index")
        e("  %tbase0 = index.add %tt4, %tll : index")
        e(f"  %cpt = index.constant {512 * m} : index")      # tiled offset of the part: 512 per k
        e("  %pto = index.mul %part, %cpt : index")
        e("  %tbase = index.add %tbase0, %pto : index")
    e("  %lane_w = index.add %lane, %pk0 : index")
    for k in range(m):
        e(f"  %wi{k} = index.add %lane_w, %o{k} : index")
        if wlds:
            e(f"  %w{k} = view.load %wl_view[%wi{k}] : view<{dim}xf32> -> f32")
        else:
            e(f"  %w{k} = view.load %weight_view[%wi{k}] : view<[%dim]xf32> -> f32")
        e(f"  %nm{k} = scalar.mulf %x{k}, %inv : f32")
        e(f"  %wt{k} = scalar.mulf %nm{k}, %w{k} : f32")
        e(f"  %h{k} = scalar.fptrunc %wt{k} : f32 to f16")
        if tiled:
            e(f"  %to{k} = index.constant {512 * k} : index")
            e(f"  %ta{k} = index.add %tbase, %to{k} : index")
            if both:
                e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
            e(f"  view.store %h{k}, %{'out_t_view' if both else 'out_view'}[%ta{k}] : f16, view<[%total_elems]xf16>")
        else:
            e(f"  view.store %h{k}, %out_view[%a{k}] : f16, view<[%total_elems]xf16>")
    e("  kernel.return")
    e("}")
    text = "\n".join(L) + "\n"
    consts = "".join(f"  %c{p}i = index.constant {p} : index\n" for p in range(split))
    return text.replace("  %unit = index.constant 1 : index\n  %rows = config.get @yah_half_norm.rows : index\n  %cwpr",
                        "  %unit = index.constant 1 : index\n  %rows = config.get @yah_half_norm.rows : index\n  %cwpr", 1) \
               .replace("  %base = index.constant 0 : offset\n", "  %base = index.constant 0 : offset\n" + consts, 1)


def split_bfp_out(e, dim, wpr, split, tiled, wlds, bfp):
    """gen_split's output pass with 8 consecutive columns per lane: thread t = part * 32 + lane of a row takes columns
    8 (t + 32 split j), re-reads their x (cached), applies the same per-element ops (same f16 bits) and stores 16 bytes
    per layout.
    The 8 halves are one bfp16ebs8 row block (gen_npu_unpack.bfp_block), staged in LDS as [k-block][row][9 bytes]:
    a k-block's 4 rows are 36 contiguous stream bytes (half a fragment), copied out as dwords after a barrier."""
    import gen_bfp16_encode as GE
    import gen_npu_unpack as GU
    tokens, ks, passes = bfp
    both = tiled == "both"
    assert wpr == 4, "4 rows per workgroup: half a fragment per k-block"
    nkb, nth = dim // 8, 32 * wpr * split
    nab = GE.layout_bytes("act", tokens, ks, passes)
    e(f"  %nab4 = index.constant {nab // 4} : index")
    e("  %abv = buffer.view %ab[%base] : buffer -> view<[%nab4]xi32>")
    e(f"  %bs_bytes = index.constant {nkb * wpr * 9} : offset")
    e("  %bs_buf = buffer.alloca<workgroup> align(16) %bs_bytes : buffer")
    e(f"  %bs_view = buffer.view %bs_buf[%base] : buffer -> view<{nkb * wpr * 9}xi8>")
    e(f"  %bs_view4 = buffer.view %bs_buf[%base] : buffer -> view<{nkb * wpr * 9 // 4}xi32>")
    e("  %c8 = index.constant 8 : index")
    e("  %c9 = index.constant 9 : index")
    e(f"  %cwpr4 = index.constant {wpr} : index")
    e("  %bt0 = index.mul %part, %c32w : index")
    e("  %bt = index.add %bt0, %lane : index")
    if tiled:
        e("  %c16t = index.constant 16 : index")
        e("  %c256t = index.constant 256 : index")
        e(f"  %ctiles = index.constant {dim // 16} : index")
        e("  %trow = index.div %row, %c16t : index")
        e("  %trr = index.rem %row, %c16t : index")
        e("  %tt0 = index.mul %trow, %ctiles : index")
        e("  %tt3 = index.mul %trr, %c16t : index")
        e(f"  %tlast = index.constant {tokens * dim - 8} : index")
    for j in range(nkb // (32 * split)):
        e(f"  %bgo{j} = index.constant {32 * split * j} : index")
        e(f"  %bg{j} = index.add %bt, %bgo{j} : index")
        e(f"  %bc{j} = index.mul %bg{j}, %c8 : index")
        e(f"  %bxa{j} = index.add %row_base, %bc{j} : index")
        e(f"  %bx{j} = vector.load %x_view[%bxa{j}] : view<[%total_elems]xf32> -> vector<8xf32>")
        if wlds:
            e(f"  %bw{j} = vector.load %wl_view[%bc{j}] : view<{dim}xf32> -> vector<8xf32>")
        else:
            e(f"  %bw{j} = vector.load %weight_view[%bc{j}] : view<[%dim]xf32> -> vector<8xf32>")
        hs = []
        for x in range(8):
            e(f"  %bxs{j}_{x} = vector.extract %bx{j}[{x}] : vector<8xf32> -> f32")
            e(f"  %bws{j}_{x} = vector.extract %bw{j}[{x}] : vector<8xf32> -> f32")
            e(f"  %bnm{j}_{x} = scalar.mulf %bxs{j}_{x}, %inv : f32")
            e(f"  %bwt{j}_{x} = scalar.mulf %bnm{j}_{x}, %bws{j}_{x} : f32")
            e(f"  %bh{j}_{x} = scalar.fptrunc %bwt{j}_{x} : f32 to f16")
            hs.append(f"%bh{j}_{x}")
        e(f"  %bvh{j} = vector.from_elements {', '.join(hs)} : vector<8xf16>")
        if not tiled or both:
            e(f"  vector.store %bvh{j}, %out_view[%bxa{j}] : vector<8xf16>, view<[%total_elems]xf16>")
        if tiled:   # 8 columns of one 16-column tile: (row / 16, col / 16) x 256 + (row % 16) x 16 + col % 16
            e(f"  %btc{j} = index.div %bc{j}, %c16t : index")
            e(f"  %btr{j} = index.rem %bc{j}, %c16t : index")
            e(f"  %bt1{j} = index.add %tt0, %btc{j} : index")
            e(f"  %bt2{j} = index.mul %bt1{j}, %c256t : index")
            e(f"  %bt4{j} = index.add %bt2{j}, %tt3 : index")
            e(f"  %bta0{j} = index.add %bt4{j}, %btr{j} : index")
            e(f"  %bta{j} = index.min %bta0{j}, %tlast : index")   # always in range; for the bound proof
            e(f"  vector.store %bvh{j}, %{'out_t_view' if both else 'out_view'}[%bta{j}] : vector<8xf16>, view<[%total_elems]xf16>")
        # LDS byte (k-block * 4 + row of the workgroup) * 9 + i
        e(f"  %bl0{j} = index.mul %bg{j}, %cwpr4 : index")
        e(f"  %bl1{j} = index.add %bl0{j}, %rwg : index")
        e(f"  %bl{j} = index.mul %bl1{j}, %c9 : index")

        def store(x, v, j=j):
            a = f"%bl{j}"
            if x:
                e(f"    %bn{j}_so{x} = index.constant {x} : index")
                e(f"    %bn{j}_sa{x} = index.add %bl{j}, %bn{j}_so{x} : index")
                a = f"%bn{j}_sa{x}"
            e(f"    view.store {v}, %bs_view[{a}] : i8, view<{nkb * wpr * 9}xi8>")
        GU.bfp_block(e, hs, f"bn{j}_", store)
    e("  kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    # copy-out: dword d = k-block d / 9, word d % 9 of the workgroup's 36 bytes at stream fragment (row0 / 8, k-block) +
    # 36 * (row0 / 4 % 2)
    e("  %row0 = index.mul %wg, %cwprb : index")
    e("  %bo_g8 = index.div %row0, %c8 : index")
    e("  %bo_h0 = index.div %row0, %cwpr4 : index")
    e("  %c2o = index.constant 2 : index")
    e("  %bo_h = index.rem %bo_h0, %c2o : index")
    e("  %c36o = index.constant 36 : index")
    e("  %bo_ho = index.mul %bo_h, %c36o : index")
    e("  %c4o = index.constant 4 : index")
    nd = nkb * wpr * 9 // 4
    for i in range((nd + nth - 1) // nth):
        q = f"bo{i}_"
        e(f"  %{q}d0 = index.constant {nth * i} : index")
        e(f"  %{q}d = index.add %tid, %{q}d0 : index")
        guard = nth * (i + 1) > nd
        ind = "  "
        if guard:
            e(f"  %{q}nd = index.constant {nd} : index")
            e(f"  %{q}live = index.cmp ult, %{q}d, %{q}nd : index")
            e(f"  scf.if %{q}live {{")
            ind = "    "
        for nm, v in (("c2", 2), ("c144", 144), ("c72", 72), ("csub", 4), ("cpk", sum(ks)), ("cpass", passes)):
            e(f"{ind}%{q}{nm} = index.constant {v} : index")
        e(f"{ind}%{q}kb = index.div %{q}d, %c9 : index")
        e(f"{ind}%{q}w = index.rem %{q}d, %c9 : index")
        frag = GE.emit_offset(e, "act", tokens, list(ks), passes, 64, True, "%bo_g8", f"%{q}kb", p=q, ind=ind)
        e(f"{ind}%{q}b0 = index.add {frag}, %bo_ho : index")
        e(f"{ind}%{q}b1 = index.mul %{q}w, %c4o : index")
        e(f"{ind}%{q}b2 = index.add %{q}b0, %{q}b1 : index")
        e(f"{ind}%{q}gw = index.div %{q}b2, %c4o : index")
        e(f"{ind}%{q}v = view.load %bs_view4[%{q}d] : view<{nd}xi32> -> i32")
        e(f"{ind}view.store %{q}v, %abv[%{q}gw] : i32, view<[%nab4]xi32>")
        if guard:
            e("  }")

def split_finish(L, split):
    """gen_split's closing lines and its per-part index constants."""
    L.append("  kernel.return")
    L.append("}")
    text = "\n".join(L) + "\n"
    consts = "".join(f"  %c{p}i = index.constant {p} : index\n" for p in range(split))
    return text.replace("  %base = index.constant 0 : offset\n", "  %base = index.constant 0 : offset\n" + consts, 1)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "yah_half_norm_unrolled.loom"
    dim = int(sys.argv[2]) if len(sys.argv) > 2 else 5120
    open(out, "w").write(gen(dim))
    print(out)


if __name__ == "__main__":
    main()
