#!/usr/bin/env python3
"""Emit the GPU BFP16 encoder: an f16 [rows][K] matrix to NPU bfp16ebs8 fragments in the cascade GEMM's stream layout.

Fragment = 8 rows x 8 consecutive k: per row [E u8][8 x int8 m], value = m * 2^(E - 133), 72 bytes.
E is the f32 exponent field of the row block's max |x| (0 for an all-zero block); m = clamp(roundeven(x * 2^(133 - E)), -128, 127).
A slab is 16 rows x KS k-blocks: per k-block the fragments of rows 0-7 then 8-15 (144 bytes), padded to 64 bytes.

The NPU GEMM splits K per pass over the column's rows (K-slices with ks[r] k-blocks each, PK = sum(ks) per pass).
Its memory tiles replay the passes of a call in groups (GROUPS: all M blocks over passes 0-1, then over 2-4), so both
streams are group-major:
  act: [slice][group][M block][pass in group][MP slabs]   rows = tokens, MP = TM / 16 slabs per M block
  wgt: [column][group][slice][pass in group][NP slabs]    rows = output features, NP = TN / 16 slabs per NPU column
A call of other pass counts is one group (the layouts without the group level).
One work item per fragment; a lane pair takes rows 0-7 and 8-15 of one k-block (its 144 contiguous bytes), adjacent pairs
adjacent k-blocks: a wave writes whole lines (half records left partial lines for other waves: read-modify-write in DRAM).
"""
import sys

WG = 256
GROUPS = (2, 3)   # passes per replay group of a 5-pass call (gen_npu_gemm)
# The k-block order of the activation stream when the NPU decodes the weights itself (gen_npu_dec: its panels hold the
# k-blocks of each sub-block group in the order its decoder computes them): None (k ascending), "p4" (per 4 k-blocks
# 0, 2, 1, 3: IQ4_XS, IQ3_S, IQ3_XXS), "pk" (per 8: 0, 4, 1, 5, 2, 6, 3, 7: Q4_K). Panel position p holds k-block
# perm[p], so k-block kb goes to position perm^-1[kb]: p4 swaps kb's two low bits, pk rotates its three low bits.
ACT_PERM = None



def pass_groups(passes):
    return GROUPS if sum(GROUPS) == passes else (passes,)


def slab_bytes(ks, pad=True):
    return (144 * ks + 63) // 64 * 64 if pad else 144 * ks


def layout_bytes(layout, rows, ks, passes, tile=64, pad=True):
    sb = [slab_bytes(k, pad) for k in ks]
    if layout == "act":
        return sum((rows // tile) * passes * (tile // 16) * b for b in sb)
    return (rows // tile) * sum(passes * (tile // 16) * b for b in sb)


def gen(layout, rows, ks, passes, tile=64, pad=True, tiled=False, k_off=0, k_src=None, kb_count=None):
    """layout: "act" | "wgt"; rows: tokens (act) or NPU output features (wgt); ks: k-blocks per K-slice.
    The input is f16 [rows][k_src] (default K), or fragment-major with tiled ([row / 16][k / 16][row % 16][k % 16], the
    afrag GEMMs' input); the encoded K columns are k_off .. k_off + K of it (a K chunk of a wider matrix).
    kb_count: only the stream's first kb_count k-blocks (the rest written by another kernel, gen_npu_unpack bfp)."""
    assert layout in ("act", "wgt") and rows % tile == 0 and tile % 16 == 0
    pk = sum(ks)
    kb = passes * pk
    K = 8 * kb
    sub = tile // 16                                   # slabs per M block (act) / per NPU column (wgt)
    kbe = kb if kb_count is None else kb_count
    assert 0 < kbe <= kb
    items = (rows // 8) * kbe
    total = layout_bytes(layout, rows, ks, passes, tile, pad)
    name = f"yah_bfp16_encode_{layout}"
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_bfp16_encode.py ({layout} rows={rows} ks={ks} passes={passes} tile={tile} pad={int(pad)}"
      + (f" kb_count={kb_count}" if kb_count is not None else "") + ")"
      " -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e(f"kernel.def target(@yah_wave32) @{name}() {{")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgs = index.constant {(items + WG - 1) // WG} : index")
    e(f"  %wgsz = index.constant {WG} : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    e("} launch(%x: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    ksrc = k_src or K
    assert k_off % 16 == 0 and k_off + K <= ksrc and (not tiled or (rows % 16 == 0 and ksrc % 16 == 0))
    e(f"  %nx = index.constant {rows * ksrc} : index")
    e(f"  %nout = index.constant {total} : index")
    e("  %x_na, %out_na = buffer.assume.noalias %x, %out : buffer, buffer")
    e("  %xv = buffer.view %x_na[%base] : buffer -> view<[%nx]xf16>")
    e("  %ov = buffer.view %out_na[%base] : buffer -> view<[%nout]xi8>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e(f"  %cwg = index.constant {WG} : index")
    e("  %item0 = index.mul %wg, %cwg : index")
    e("  %item = index.add %item0, %tid : index")
    e(f"  %citems = index.constant {items} : index")
    e("  %live = index.cmp ult, %item, %citems : index")
    e("  scf.if %live {")
    for nm, v in (("ckb", kb), ("cK", ksrc), ("c8", 8), ("c2", 2), ("c144", 144), ("c72", 72), ("csub", sub),
                  ("cpk", pk), ("cpass", passes)):
        e(f"    %{nm} = index.constant {v} : index")
    # item = (16-row group * kb + k-block) * 2 + half: a lane pair writes one k-block's 144 contiguous bytes
    e("    %ihalf = index.rem %item, %c2 : index")
    e("    %ipair = index.div %item, %c2 : index")
    ckbe = "%ckb"
    if kb_count is not None:
        e(f"    %ckbe = index.constant {kbe} : index")
        ckbe = "%ckbe"
    e(f"    %g16i = index.div %ipair, {ckbe} : index")
    e(f"    %kbi = index.rem %ipair, {ckbe} : index")
    e("    %g16x2 = index.mul %g16i, %c2 : index")
    e("    %g8 = index.add %g16x2, %ihalf : index")
    # ACT_PERM: this encoder permutes its source instead (position kbi reads k-block perm[kbi]; destination offsets keep
    # their range proofs, which a permuted destination loses for partial streams)
    frag = emit_offset(e, layout, rows, ks, passes, tile, pad, "%g8", "%kbi", perm=False)
    kbs = "%kbi"
    if layout == "act" and ACT_PERM:
        kbs = emit_perm(e, "%kbi", ACT_PERM, "s_", forward=True)
        # the permutation stays inside its group of 4 / 8 k-blocks: state kbs < kbe for the bound proofs
        e(f"    %s_kbl = index.constant {kbe - 1} : index")
        e(f"    %s_kbm = index.min {kbs}, %s_kbl : index")
        kbs = "%s_kbm"
    # inputs: 8 rows x 8 halves
    e("    %row0 = index.mul %g8, %c8 : index")
    if not tiled:
        e("    %rb = index.mul %row0, %cK : index")
    e(f"    %kc = index.mul {kbs}, %c8 : index")
    if k_off:
        e(f"    %kco = index.constant {k_off} : index")
        e("    %kc0 = index.add %kc, %kco : index")
    kcol = "%kc0" if k_off else "%kc"
    if tiled:   # 8 rows of one 16-row tile, 8 halves of one 16-wide k tile: each row's 8 halves are contiguous
        e("    %c16 = index.constant 16 : index")
        e("    %c256 = index.constant 256 : index")
        e(f"    %ckt = index.constant {ksrc // 16} : index")
        e("    %t16 = index.div %row0, %c16 : index")
        e("    %tr = index.rem %row0, %c16 : index")
        e(f"    %k16 = index.div {kcol}, %c16 : index")
        e(f"    %kr = index.rem {kcol}, %c16 : index")
        e("    %tt0 = index.mul %t16, %ckt : index")
        e("    %tt1 = index.add %tt0, %k16 : index")
        e("    %tb = index.mul %tt1, %c256 : index")
        e("    %trr = index.mul %tr, %c16 : index")
        e("    %tb1 = index.add %tb, %trr : index")
        e("    %xb = index.add %tb1, %kr : index")
        e(f"    %xlast = index.constant {rows * ksrc - 8} : index")   # always in range; for the bound proof
    else:
        e(f"    %xb = index.add %rb, {kcol} : index")
    rstride = 16 if tiled else ksrc

    def load(r):
        e(f"    %ro{r} = index.constant {r * rstride} : index")
        e(f"    %xa{r} = index.add %xb, %ro{r} : index")
        xa = f"%xa{r}"
        if tiled:
            e(f"    %xm{r} = index.min %xa{r}, %xlast : index")
            xa = f"%xm{r}"
        e(f"    %xh{r} = vector.load %xv[{xa}] : view<[%nx]xf16> -> vector<8xf16>")
        return f"%xh{r}"

    emit_encode(e, load, frag, "%ov", "%nout")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def emit_offset(e, layout, rows, ks, passes, tile, pad, g8, kbi, p="", ind="    ", perm=True):
    """Emit the byte offset of the fragment of row group g8 (8 rows) and k-block kbi in the stream layout; returns its name.
    The caller defines the index constants %{p}c2, %{p}c144, %{p}c72, %{p}csub (tile / 16), %{p}cpk (sum(ks)) and %{p}cpass."""
    sb = [slab_bytes(k, pad) for k in ks]
    sub = tile // 16
    if layout == "act" and ACT_PERM and perm:
        kbi = emit_perm(e, kbi, ACT_PERM, p, ind)
    groups = pass_groups(passes)
    ga, gb = groups[0], groups[-1]
    if layout == "act":
        nblk = rows // tile
        base = [sum(nblk * passes * sub * sb[j] for j in range(i)) for i in range(len(ks))]
    else:
        # per group: the slices' bases inside the group's region of the column panel
        base = [sum(ga * sub * sb[j] for j in range(i)) for i in range(len(ks))]
        base_b = [sum(gb * sub * sb[j] for j in range(i)) for i in range(len(ks))]
        region_b = sum(ga * sub * b for b in sb)
        panel = sum(passes * sub * b for b in sb)
    start = [sum(ks[:i]) for i in range(len(ks))]

    def x(line):
        e(ind + line)
    x(f"%{p}g16 = index.div {g8}, %{p}c2 : index")
    x(f"%{p}h = index.rem {g8}, %{p}c2 : index")
    x(f"%{p}blk = index.div %{p}g16, %{p}csub : index")          # M block (act) / NPU column (wgt)
    x(f"%{p}slab = index.rem %{p}g16, %{p}csub : index")
    x(f"%{p}pass = index.div {kbi}, %{p}cpk : index")
    x(f"%{p}o = index.rem {kbi}, %{p}cpk : index")
    # replay group of the pass (its size; group offsets fold into non-negative constants, no subtraction to prove)
    x(f"%{p}cga = index.constant {ga} : index")
    x(f"%{p}cgb = index.constant {gb} : index")
    x(f"%{p}cz = index.constant 0 : index")
    x(f"%{p}gy = index.cmp uge, %{p}pass, %{p}cga : index")
    x(f"%{p}gsz = scf.select %{p}gy, %{p}cgb, %{p}cga : index")
    # K-slice of o: a compare chain over the cumulative starts
    sel_base, sel_start, sel_sb = f"%{p}cb0", f"%{p}cs0", f"%{p}csb0"
    for i in range(len(ks)):
        if layout == "act":
            x(f"%{p}cb{i} = index.constant {base[i]} : index")
        else:
            x(f"%{p}cba{i} = index.constant {base[i]} : index")
            x(f"%{p}cbb{i} = index.constant {base_b[i] + region_b - ga * sub * sb[i]} : index")
            x(f"%{p}cb{i} = scf.select %{p}gy, %{p}cbb{i}, %{p}cba{i} : index")
        x(f"%{p}cs{i} = index.constant {start[i]} : index")
        x(f"%{p}csb{i} = index.constant {sb[i]} : index")
    for i in range(1, len(ks)):
        x(f"%{p}ge{i} = index.cmp uge, %{p}o, %{p}cs{i} : index")
        x(f"%{p}sb_{i} = scf.select %{p}ge{i}, %{p}cb{i}, {sel_base} : index")
        x(f"%{p}ss_{i} = scf.select %{p}ge{i}, %{p}cs{i}, {sel_start} : index")
        x(f"%{p}sz_{i} = scf.select %{p}ge{i}, %{p}csb{i}, {sel_sb} : index")
        sel_base, sel_start, sel_sb = f"%{p}sb_{i}", f"%{p}ss_{i}", f"%{p}sz_{i}"
    x(f"%{p}kin = index.sub %{p}o, {sel_start} : index")
    if layout == "act":
        # record (gst * nblk + blk * gsz + pass - gst) * sub + slab of the slice, gst the group's first pass
        x(f"%{p}cgo = index.constant {ga * (nblk - 1)} : index")
        x(f"%{p}r0 = scf.select %{p}gy, %{p}cgo, %{p}cz : index")
        x(f"%{p}r1a = index.mul %{p}blk, %{p}gsz : index")
        x(f"%{p}r1b = index.add %{p}r0, %{p}r1a : index")
        x(f"%{p}r1 = index.add %{p}r1b, %{p}pass : index")
        x(f"%{p}r2 = index.mul %{p}r1, %{p}csub : index")
        x(f"%{p}rec = index.add %{p}r2, %{p}slab : index")
        x(f"%{p}slo = index.mul %{p}rec, {sel_sb} : index")
        x(f"%{p}off0 = index.add {sel_base}, %{p}slo : index")
    else:
        x(f"%{p}cpanel = index.constant {panel} : index")
        x(f"%{p}po = index.mul %{p}blk, %{p}cpanel : index")
        x(f"%{p}r1 = index.mul %{p}pass, %{p}csub : index")
        x(f"%{p}rec = index.add %{p}r1, %{p}slab : index")
        x(f"%{p}slo = index.mul %{p}rec, {sel_sb} : index")
        x(f"%{p}off1 = index.add {sel_base}, %{p}slo : index")
        x(f"%{p}off0 = index.add %{p}po, %{p}off1 : index")
    x(f"%{p}ko = index.mul %{p}kin, %{p}c144 : index")
    x(f"%{p}ho = index.mul %{p}h, %{p}c72 : index")
    x(f"%{p}off2 = index.add %{p}off0, %{p}ko : index")
    x(f"%{p}frag = index.add %{p}off2, %{p}ho : index")
    return f"%{p}frag"


def emit_perm(e, kbi, perm, p="", ind="    ", forward=False):
    """Emit k-block kbi's position in the permuted stream (ACT_PERM), or with forward the k-block at position kbi;
    returns its name."""
    def x(line):
        e(ind + line)
    n = {"p4": 4, "pk": 8}[perm]
    x(f"%{p}pn = index.constant {n} : index")
    x(f"%{p}p2 = index.constant 2 : index")
    x(f"%{p}pj = index.rem {kbi}, %{p}pn : index")
    x(f"%{p}pq = index.div {kbi}, %{p}pn : index")
    x(f"%{p}pg = index.mul %{p}pq, %{p}pn : index")   # (kbi / n) n: no subtraction for the range proofs
    x(f"%{p}p4 = index.constant 4 : index")
    if perm == "p4":     # j = 2 b1 + b0 -> 2 b0 + b1 (its own inverse)
        x(f"%{p}pb0 = index.rem %{p}pj, %{p}p2 : index")
        x(f"%{p}pb1 = index.div %{p}pj, %{p}p2 : index")
        mul = "%{p}p2".format(p=p)
    elif not forward:    # k-block j = 4 b2 + l (l < 4) -> position 2 l + b2
        x(f"%{p}pb0 = index.rem %{p}pj, %{p}p4 : index")
        x(f"%{p}pb1 = index.div %{p}pj, %{p}p4 : index")
        mul = "%{p}p2".format(p=p)
    else:                # position j = 2 l + b -> k-block l + 4 b
        x(f"%{p}pb0 = index.rem %{p}pj, %{p}p2 : index")
        x(f"%{p}pb1 = index.div %{p}pj, %{p}p2 : index")
        mul = "%{p}p4".format(p=p)
    x(f"%{p}pt = index.mul %{p}pb0, {mul} : index")
    x(f"%{p}pu = index.add %{p}pt, %{p}pb1 : index")
    x(f"%{p}pkb = index.add %{p}pg, %{p}pu : index")
    return f"%{p}pkb"


def emit_encode(e, load, frag, ov, nout, p="", ind="    "):
    """Encode one fragment: load(r) emits row r's 8 halves (vector<8xf16>) and returns its name; 72 bytes go to ov at frag."""
    def x(line):
        e(ind + line)
    x(f"%{p}zero = scalar.constant 0.0 : f32")
    x(f"%{p}i23 = scalar.constant 23 : i32")
    x(f"%{p}i255 = scalar.constant 255 : i32")
    x(f"%{p}i260 = scalar.constant 260 : i32")
    x(f"%{p}i0 = scalar.constant 0 : i32")
    x(f"%{p}fmin = scalar.constant -128.0 : f32")
    x(f"%{p}fmax = scalar.constant 127.0 : f32")
    byts = []
    for r in range(8):
        xh = load(r)
        x(f"%{p}xf{r} = vector.extf {xh} : vector<8xf16> to vector<8xf32>")
        vals = []
        for i in range(8):
            x(f"%{p}v{r}_{i} = vector.extract %{p}xf{r}[{i}] : vector<8xf32> -> f32")
            x(f"%{p}a{r}_{i} = scalar.absf %{p}v{r}_{i} : f32")
            vals.append(f"%{p}v{r}_{i}")
        cur = f"%{p}a{r}_0"
        for i in range(1, 8):
            x(f"%{p}mx{r}_{i} = scalar.maxnumf {cur}, %{p}a{r}_{i} : f32")
            cur = f"%{p}mx{r}_{i}"
        x(f"%{p}mb{r} = scalar.bitcast {cur} : f32 to i32")
        x(f"%{p}ms{r} = scalar.shrui %{p}mb{r}, %{p}i23 : i32")
        x(f"%{p}E{r} = scalar.andi %{p}ms{r}, %{p}i255 : i32")            # exponent field (0 for an all-zero block)
        x(f"%{p}ie{r} = scalar.subi %{p}i260, %{p}E{r} : i32")
        x(f"%{p}ib{r} = scalar.shli %{p}ie{r}, %{p}i23 : i32")
        x(f"%{p}iq0{r} = scalar.bitcast %{p}ib{r} : i32 to f32")          # 2^(133 - E)
        x(f"%{p}z{r} = scalar.cmpi eq, %{p}E{r}, %{p}i0 : i32")
        x(f"%{p}iq{r} = scf.select %{p}z{r}, %{p}zero, %{p}iq0{r} : f32")
        x(f"%{p}eb{r} = scalar.trunci %{p}E{r} : i32 to i8")
        byts.append(f"%{p}eb{r}")
        for i in range(8):
            x(f"%{p}s{r}_{i} = scalar.mulf {vals[i]}, %{p}iq{r} : f32")
            x(f"%{p}n{r}_{i} = scalar.roundevenf %{p}s{r}_{i} : f32")
            x(f"%{p}c0{r}_{i} = scalar.maxnumf %{p}n{r}_{i}, %{p}fmin : f32")
            x(f"%{p}c{r}_{i} = scalar.minnumf %{p}c0{r}_{i}, %{p}fmax : f32")
            x(f"%{p}t{r}_{i} = scalar.fptosi %{p}c{r}_{i} : f32 to i32")
            x(f"%{p}m{r}_{i} = scalar.trunci %{p}t{r}_{i} : i32 to i8")
            byts.append(f"%{p}m{r}_{i}")
    for j in range(9):   # 72 bytes = 9 aligned 8-byte stores
        x(f"%{p}w{j} = vector.from_elements {', '.join(byts[8 * j:8 * j + 8])} : vector<8xi8>")
        x(f"%{p}wo{j} = index.constant {8 * j} : index")
        x(f"%{p}wa{j} = index.add {frag}, %{p}wo{j} : index")
        x(f"vector.store %{p}w{j}, {ov}[%{p}wa{j}] : vector<8xi8>, view<[{nout}]xi8>")


def main():
    if len(sys.argv) < 5:
        sys.exit("usage: gen_bfp16_encode.py act|wgt <rows> <ks,ks,...> <passes> [tile] [pad]")
    layout, rows, ks, passes = sys.argv[1], int(sys.argv[2]), [int(v) for v in sys.argv[3].split(",")], int(sys.argv[4])
    tile = int(sys.argv[5]) if len(sys.argv) > 5 else 64
    pad = (sys.argv[6] != "0") if len(sys.argv) > 6 else True
    sys.stdout.write(gen(layout, rows, ks, passes, tile, pad))


if __name__ == "__main__":
    main()
