#!/usr/bin/env python3
"""Emit the GPU BFP16 encoder: an f16 [rows][K] matrix to NPU bfp16ebs8 fragments in the cascade GEMM's stream layout.

Fragment = 8 rows x 8 consecutive k: per row [E u8][8 x int8 m], value = m * 2^(E - 133), 72 bytes.
E is the f32 exponent field of the row block's max |x| (0 for an all-zero block); m = clamp(roundeven(x * 2^(133 - E)), -128, 127).
A slab is 16 rows x KS k-blocks: per k-block the fragments of rows 0-7 then 8-15 (144 bytes), padded to 64 bytes.

The NPU GEMM splits K per pass over the column's rows (K-slices with ks[r] k-blocks each, PK = sum(ks) per pass).
  act: [slice][M block][pass][MP slabs]   rows = tokens, MP = TM / 16 slabs per M block
  wgt: [column][slice][pass][NP slabs]    rows = output features, NP = TN / 16 slabs per NPU column
One work item per fragment; adjacent items take adjacent k-blocks of the same 8 rows (coalesced 16-byte loads).
"""
import sys

WG = 256


def slab_bytes(ks, pad=True):
    return (144 * ks + 63) // 64 * 64 if pad else 144 * ks


def layout_bytes(layout, rows, ks, passes, tile=64, pad=True):
    sb = [slab_bytes(k, pad) for k in ks]
    if layout == "act":
        return sum((rows // tile) * passes * (tile // 16) * b for b in sb)
    return (rows // tile) * sum(passes * (tile // 16) * b for b in sb)


def gen(layout, rows, ks, passes, tile=64, pad=True, tiled=False, k_off=0, k_src=None):
    """layout: "act" | "wgt"; rows: tokens (act) or NPU output features (wgt); ks: k-blocks per K-slice.
    The input is f16 [rows][k_src] (default K), or fragment-major with tiled ([row / 16][k / 16][row % 16][k % 16], the
    afrag GEMMs' input); the encoded K columns are k_off .. k_off + K of it (a K chunk of a wider matrix)."""
    assert layout in ("act", "wgt") and rows % tile == 0 and tile % 16 == 0
    pk = sum(ks)
    kb = passes * pk
    K = 8 * kb
    sub = tile // 16                                   # slabs per M block (act) / per NPU column (wgt)
    items = (rows // 8) * kb
    total = layout_bytes(layout, rows, ks, passes, tile, pad)
    name = f"yah_bfp16_encode_{layout}"
    L = []
    e = L.append
    e(f"// GENERATED by tools/gen_bfp16_encode.py ({layout} rows={rows} ks={ks} passes={passes} tile={tile} pad={int(pad)})"
      " -- edit the generator.")
    e("amdgpu.target<gfx1151> @yah_wave32 {subgroup_size = 32}")
    e("")
    e(f"kernel.def target(@yah_wave32) @{name}() {{")
    e("  %unit = index.constant 1 : index")
    e(f"  %wgs = index.constant {(items + WG - 1) // WG} : index")
    e(f"  %wgsz = index.constant {WG} : index")
    e("  kernel.launch.config workgroups(%wgs, %unit, %unit) workgroup_size(%wgsz, %unit, %unit) : index")
    e("} launch(%x: buffer, %out: buffer) {")
    e("  %base = index.constant 0 : offset")
    ksrc = k_src or K
    assert k_off % 16 == 0 and k_off + K <= ksrc and (not tiled or (rows % 16 == 0 and ksrc % 16 == 0))
    e(f"  %nx = index.constant {rows * ksrc} : index")
    e(f"  %nout = index.constant {total} : index")
    e("  %x_na, %out_na = buffer.assume.noalias %x, %out : buffer, buffer")
    e("  %xv = buffer.view %x_na[%base] : buffer -> view<[%nx]xf16>")
    e("  %ov = buffer.view %out_na[%base] : buffer -> view<[%nout]xi8>")
    e("  %wg = kernel.workgroup.id<x> : index")
    e("  %tid = kernel.workitem.id<x> : index")
    e(f"  %cwg = index.constant {WG} : index")
    e("  %item0 = index.mul %wg, %cwg : index")
    e("  %item = index.add %item0, %tid : index")
    e(f"  %citems = index.constant {items} : index")
    e("  %live = index.cmp ult, %item, %citems : index")
    e("  scf.if %live {")
    for nm, v in (("ckb", kb), ("cK", ksrc), ("c8", 8), ("c2", 2), ("c144", 144), ("c72", 72), ("csub", sub),
                  ("cpk", pk), ("cpass", passes)):
        e(f"    %{nm} = index.constant {v} : index")
    e("    %g8 = index.div %item, %ckb : index")
    e("    %kbi = index.rem %item, %ckb : index")
    frag = emit_offset(e, layout, rows, ks, passes, tile, pad, "%g8", "%kbi")
    # inputs: 8 rows x 8 halves
    e("    %row0 = index.mul %g8, %c8 : index")
    if not tiled:
        e("    %rb = index.mul %row0, %cK : index")
    e("    %kc = index.mul %kbi, %c8 : index")
    if k_off:
        e(f"    %kco = index.constant {k_off} : index")
        e("    %kc0 = index.add %kc, %kco : index")
    kcol = "%kc0" if k_off else "%kc"
    if tiled:   # 8 rows of one 16-row tile, 8 halves of one 16-wide k tile: each row's 8 halves are contiguous
        e("    %c16 = index.constant 16 : index")
        e("    %c256 = index.constant 256 : index")
        e(f"    %ckt = index.constant {ksrc // 16} : index")
        e("    %t16 = index.div %row0, %c16 : index")
        e("    %tr = index.rem %row0, %c16 : index")
        e(f"    %k16 = index.div {kcol}, %c16 : index")
        e(f"    %kr = index.rem {kcol}, %c16 : index")
        e("    %tt0 = index.mul %t16, %ckt : index")
        e("    %tt1 = index.add %tt0, %k16 : index")
        e("    %tb = index.mul %tt1, %c256 : index")
        e("    %trr = index.mul %tr, %c16 : index")
        e("    %tb1 = index.add %tb, %trr : index")
        e("    %xb = index.add %tb1, %kr : index")
        e(f"    %xlast = index.constant {rows * ksrc - 8} : index")   # always in range; for the bound proof
    else:
        e(f"    %xb = index.add %rb, {kcol} : index")
    rstride = 16 if tiled else ksrc

    def load(r):
        e(f"    %ro{r} = index.constant {r * rstride} : index")
        e(f"    %xa{r} = index.add %xb, %ro{r} : index")
        xa = f"%xa{r}"
        if tiled:
            e(f"    %xm{r} = index.min %xa{r}, %xlast : index")
            xa = f"%xm{r}"
        e(f"    %xh{r} = vector.load %xv[{xa}] : view<[%nx]xf16> -> vector<8xf16>")
        return f"%xh{r}"

    emit_encode(e, load, frag, "%ov", "%nout")
    e("  }")
    e("  kernel.return")
    e("}")
    return "\n".join(L) + "\n"


def emit_offset(e, layout, rows, ks, passes, tile, pad, g8, kbi, p="", ind="    "):
    """Emit the byte offset of the fragment of row group g8 (8 rows) and k-block kbi in the stream layout; returns its name.
    The caller defines the index constants %{p}c2, %{p}c144, %{p}c72, %{p}csub (tile / 16), %{p}cpk (sum(ks)) and %{p}cpass."""
    sb = [slab_bytes(k, pad) for k in ks]
    sub = tile // 16
    if layout == "act":
        nblk = rows // tile
        base = [sum(nblk * passes * sub * sb[j] for j in range(i)) for i in range(len(ks))]
    else:
        base = [sum(passes * sub * sb[j] for j in range(i)) for i in range(len(ks))]
        panel = sum(passes * sub * b for b in sb)
    start = [sum(ks[:i]) for i in range(len(ks))]

    def x(line):
        e(ind + line)
    x(f"%{p}g16 = index.div {g8}, %{p}c2 : index")
    x(f"%{p}h = index.rem {g8}, %{p}c2 : index")
    x(f"%{p}blk = index.div %{p}g16, %{p}csub : index")          # M block (act) / NPU column (wgt)
    x(f"%{p}slab = index.rem %{p}g16, %{p}csub : index")
    x(f"%{p}pass = index.div {kbi}, %{p}cpk : index")
    x(f"%{p}o = index.rem {kbi}, %{p}cpk : index")
    # K-slice of o: a compare chain over the cumulative starts
    sel_base, sel_start, sel_sb = f"%{p}cb0", f"%{p}cs0", f"%{p}csb0"
    for i in range(len(ks)):
        x(f"%{p}cb{i} = index.constant {base[i]} : index")
        x(f"%{p}cs{i} = index.constant {start[i]} : index")
        x(f"%{p}csb{i} = index.constant {sb[i]} : index")
    for i in range(1, len(ks)):
        x(f"%{p}ge{i} = index.cmp uge, %{p}o, %{p}cs{i} : index")
        x(f"%{p}sb_{i} = scf.select %{p}ge{i}, %{p}cb{i}, {sel_base} : index")
        x(f"%{p}ss_{i} = scf.select %{p}ge{i}, %{p}cs{i}, {sel_start} : index")
        x(f"%{p}sz_{i} = scf.select %{p}ge{i}, %{p}csb{i}, {sel_sb} : index")
        sel_base, sel_start, sel_sb = f"%{p}sb_{i}", f"%{p}ss_{i}", f"%{p}sz_{i}"
    x(f"%{p}kin = index.sub %{p}o, {sel_start} : index")
    if layout == "act":
        x(f"%{p}r0 = index.mul %{p}blk, %{p}cpass : index")
        x(f"%{p}r1 = index.add %{p}r0, %{p}pass : index")
        x(f"%{p}r2 = index.mul %{p}r1, %{p}csub : index")
        x(f"%{p}rec = index.add %{p}r2, %{p}slab : index")
        x(f"%{p}slo = index.mul %{p}rec, {sel_sb} : index")
        x(f"%{p}off0 = index.add {sel_base}, %{p}slo : index")
    else:
        x(f"%{p}cpanel = index.constant {panel} : index")
        x(f"%{p}po = index.mul %{p}blk, %{p}cpanel : index")
        x(f"%{p}r1 = index.mul %{p}pass, %{p}csub : index")
        x(f"%{p}rec = index.add %{p}r1, %{p}slab : index")
        x(f"%{p}slo = index.mul %{p}rec, {sel_sb} : index")
        x(f"%{p}off1 = index.add {sel_base}, %{p}slo : index")
        x(f"%{p}off0 = index.add %{p}po, %{p}off1 : index")
    x(f"%{p}ko = index.mul %{p}kin, %{p}c144 : index")
    x(f"%{p}ho = index.mul %{p}h, %{p}c72 : index")
    x(f"%{p}off2 = index.add %{p}off0, %{p}ko : index")
    x(f"%{p}frag = index.add %{p}off2, %{p}ho : index")
    return f"%{p}frag"


def emit_encode(e, load, frag, ov, nout, p="", ind="    "):
    """Encode one fragment: load(r) emits row r's 8 halves (vector<8xf16>) and returns its name; 72 bytes go to ov at frag."""
    def x(line):
        e(ind + line)
    x(f"%{p}zero = scalar.constant 0.0 : f32")
    x(f"%{p}i23 = scalar.constant 23 : i32")
    x(f"%{p}i255 = scalar.constant 255 : i32")
    x(f"%{p}i260 = scalar.constant 260 : i32")
    x(f"%{p}i0 = scalar.constant 0 : i32")
    x(f"%{p}fmin = scalar.constant -128.0 : f32")
    x(f"%{p}fmax = scalar.constant 127.0 : f32")
    byts = []
    for r in range(8):
        xh = load(r)
        x(f"%{p}xf{r} = vector.extf {xh} : vector<8xf16> to vector<8xf32>")
        vals = []
        for i in range(8):
            x(f"%{p}v{r}_{i} = vector.extract %{p}xf{r}[{i}] : vector<8xf32> -> f32")
            x(f"%{p}a{r}_{i} = scalar.absf %{p}v{r}_{i} : f32")
            vals.append(f"%{p}v{r}_{i}")
        cur = f"%{p}a{r}_0"
        for i in range(1, 8):
            x(f"%{p}mx{r}_{i} = scalar.maxnumf {cur}, %{p}a{r}_{i} : f32")
            cur = f"%{p}mx{r}_{i}"
        x(f"%{p}mb{r} = scalar.bitcast {cur} : f32 to i32")
        x(f"%{p}ms{r} = scalar.shrui %{p}mb{r}, %{p}i23 : i32")
        x(f"%{p}E{r} = scalar.andi %{p}ms{r}, %{p}i255 : i32")            # exponent field (0 for an all-zero block)
        x(f"%{p}ie{r} = scalar.subi %{p}i260, %{p}E{r} : i32")
        x(f"%{p}ib{r} = scalar.shli %{p}ie{r}, %{p}i23 : i32")
        x(f"%{p}iq0{r} = scalar.bitcast %{p}ib{r} : i32 to f32")          # 2^(133 - E)
        x(f"%{p}z{r} = scalar.cmpi eq, %{p}E{r}, %{p}i0 : i32")
        x(f"%{p}iq{r} = scf.select %{p}z{r}, %{p}zero, %{p}iq0{r} : f32")
        x(f"%{p}eb{r} = scalar.trunci %{p}E{r} : i32 to i8")
        byts.append(f"%{p}eb{r}")
        for i in range(8):
            x(f"%{p}s{r}_{i} = scalar.mulf {vals[i]}, %{p}iq{r} : f32")
            x(f"%{p}n{r}_{i} = scalar.roundevenf %{p}s{r}_{i} : f32")
            x(f"%{p}c0{r}_{i} = scalar.maxnumf %{p}n{r}_{i}, %{p}fmin : f32")
            x(f"%{p}c{r}_{i} = scalar.minnumf %{p}c0{r}_{i}, %{p}fmax : f32")
            x(f"%{p}t{r}_{i} = scalar.fptosi %{p}c{r}_{i} : f32 to i32")
            x(f"%{p}m{r}_{i} = scalar.trunci %{p}t{r}_{i} : i32 to i8")
            byts.append(f"%{p}m{r}_{i}")
    for j in range(9):   # 72 bytes = 9 aligned 8-byte stores
        x(f"%{p}w{j} = vector.from_elements {', '.join(byts[8 * j:8 * j + 8])} : vector<8xi8>")
        x(f"%{p}wo{j} = index.constant {8 * j} : index")
        x(f"%{p}wa{j} = index.add {frag}, %{p}wo{j} : index")
        x(f"vector.store %{p}w{j}, {ov}[%{p}wa{j}] : vector<8xi8>, view<[{nout}]xi8>")


def main():
    if len(sys.argv) < 5:
        sys.exit("usage: gen_bfp16_encode.py act|wgt <rows> <ks,ks,...> <passes> [tile] [pad]")
    layout, rows, ks, passes = sys.argv[1], int(sys.argv[2]), [int(v) for v in sys.argv[3].split(",")], int(sys.argv[4])
    tile = int(sys.argv[5]) if len(sys.argv) > 5 else 64
    pad = (sys.argv[6] != "0") if len(sys.argv) > 6 else True
    sys.stdout.write(gen(layout, rows, ks, passes, tile, pad))


if __name__ == "__main__":
    main()
